### ISSUE TITLE
Is this *really* on CRAN?

### ISSUE THREAD

**Issue by brendan-R** [cloudyr/aws.s3#1]
The `install.packages` line drew my interest (there's a ton of S3 clients on Github, but none that seem to be on CRAN).

Do you have any plans to (re)submit it?

**Comment by leeper** [comment]
This is not on CRAN yet. I will be submitting, but there are lingering issues (sorry, I haven't noted them anywhere). Hopefully it will be done soon! Feel free to submit more pull requests! Any help would be greatly appreciated.
