### ISSUE TITLE
Support for S3Uri Syntax

### ISSUE THREAD

**Issue by ramhiser** [cloudyr/aws.s3#100]
The [S3Uri syntax](http://docs.aws.amazon.com/cli/latest/reference/s3/#path-argument-type) is commonly used in the [AWS CLI tool](http://docs.aws.amazon.com/cli/latest). It would be useful to support the syntax in `aws.s3`.  Here are the four examples from the README represented in the syntax:

```r
# save an in-memory R object into S3
s3save(mtcars, s3_path = "s3://my_bucket/mtcars.Rdata")

# `load()` R objects from the file
s3load(s3_path = "s3://my_bucket/mtcars.Rdata")

# get file as raw vector
get_object(s3_path = "s3://my_bucket/mtcars.Rdata")

# save file locally
save_object(s3_path = "s3://my_bucket/mtcars.Rdata", file = "mtcars.Rdata")

# put local file into S3
put_object(s3_path = "s3://my_bucket/mtcars.Rdata", file = "mtcars.Rdata")
```

**Comment by leeper** [comment]
This seems doable. I'll try to incorporate it.

**Comment by ramhiser** [comment]
Awesome. Let me know if I can help. I can make this happen and submit a PR later today if you'd like.

**Comment by leeper** [comment]
I've just added this. Rather than add a new argument, I decided to just allow this for `object` values, so that the following should work:

```R
get_object(object = "s3://my_bucket/mtcars.Rdata")
```
