### ISSUE TITLE
Return a data frame instead of a list from get_bucket()

### ISSUE THREAD

**Issue by daattali** [cloudyr/aws.s3#102]
This is potentially related/identical to #99 (I couldn't figure out if you're talking about this issue or not)

I previously used the RAmazonS3 package, and their `listBucket()` function returned a nice data frame, where each row had the info for one file in the bucket. It was really convenient. I want to upgrade to using `aws.s3`, and it's a bit annoying to receive the data as a list. From my (limited) experience, `get_bucket()` always returns a list where each element has an identical structure. Was there a reason why a list was preferred over a dataframe if the data is always structured nicely?

**Comment by leeper** [comment]
It's not related to #99 (that's about loading data stored on S3 as, say, a CSV directly into a data frame).

This seems doable. There are reasons to preserve the existing structure (the objects in the list have S3 [in the R sense] classes, which makes it possible to pass them around as the value of `object` arguments in other functions). How about if I add another function, `get_bucket_df()` that returns a data frame instead?

**Comment by daattali** [comment]
Either that, or provide an argument to return as data.frame. I don't have a
very strong opinion on which one since it's your package
