### ISSUE TITLE
Confusing error message when file does not exist

### ISSUE THREAD

**Issue by elinw** [cloudyr/aws.s3#105]
If you request a file that does not exist, for example by using lower case instead of upper case for one of the letters, you get this error from R:

> Error in load(tmp, envir = envir) : 
>   the input does not start with a magic number compatible with loading from a connection
> 

Which, while correct, does not help most people to know what they did wrong.  Also I think that processing should probably stop long before R gets to the point of checking in the environment.
 When we get to R  and eventually we end up here
http://docs.rexamine.com/R-devel/saveload_8c_source.html  at line 2383 which is where the message comes from. 
At that point R is getting something that is not a valid filename or contents. 
However that is just the symptom.

I suspect that the chain of events starts around here in s3load()
```

    r <- get_object(bucket = bucket, object = object, parse_response = FALSE, 
        ...)
    if (inherits(r, "aws-error")) {
        return(r)
    }
```
When an aws_error is returned the process is not stopped. 
Also because the response is not being parsed the 404 status that is being returned is not being interpreted as an error. 

I found that if I changed`parse_response=FALSE` to `parse_response = TRUE` and change `return(r)` to `stop()`  I got a reasonably helpful message when having a typo in the data set name.

Also the same message comes if the bucket doesn't exist. I think this is the same issue, there is this nice code
https://github.com/cloudyr/aws.s3/blob/master/R/bucket_exists.R

Checking if the bucket exists, but it does the exact same thing whether the bucket does or does not exist, `return(r) `.  If I replace `return(r)` with `stop()`  I get both the incorrect message saying that my region can't be found and the correct AWS 404 Not Found. 

>  Error in get_region.default(bucket) : 
>   Cannot detect correct region from bucket In addition: Warning message:
> In parse_aws_s3_response(r, Sig) : Not Found (HTTP 404)

The traceback is

> 6.
> stop("Cannot detect correct region from bucket") at utils.R#45
> 5.
> get_region.default(bucket) at utils.R#39
> 4.
> get_region(bucket) at s3HTTP.R#42
> 3.
> s3HTTP(verb = "GET", bucket = bucket, path = paste0("/", object), 
>     headers = headers, parse_response = parse_response, ...) at get_object.R#49
> 2.
> get_object(bucket = bucket, object = object, parse_response = FALSE, 
>     ...) at s3save.R#82
> 1.
> s3load("mydata.RData", bucket = "misspelledbucket name")

My region is fine.

I think rather than just stopping it might be good to return a better message, but at least with `stop()` you don't get the confusing magic number  message.

**Comment by leeper** [comment]
This is related: https://github.com/cloudyr/aws.s3/issues/86

**Comment by leeper** [comment]
I've modified the entire package (as of https://github.com/cloudyr/aws.s3/commit/7cbfa344b00032e27514f6c7c9314fde775048f4) to generate errors rather returning error objects. And with that breaking change, there's a bump to v0.2.0.
