### ISSUE TITLE
period in package name

### ISSUE THREAD

**Issue by LiNk-NY** [cloudyr/aws.s3#107]
Periods in the package name break convention. What is the motivation for having the period? 
You could have used `camelCase` as in `awsS3`.

**Comment by leeper** [comment]
Whose convention? Package name is allowed under rules in [WRE](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#The-DESCRIPTION-file).

**Comment by LiNk-NY** [comment]
Check `CRAN` and `Bioconductor` to start.

Of course it is allowed but seldom used.
You don't see many packages with periods in the name. Why begin to use it?

**Comment by DavidArenburg** [comment]
Welp, there are 327 such packages on CRAN, some of them even have multiple dots in their names, check this out

```r

library(rvest)
library(stringi)
page <- read_html("https://cran.r-project.org/web/packages/available_packages_by_name.html#available-packages-D")
res <- 
  page %>% 
  html_table(fill = TRUE) %>%
  .[[1]] %>%
  .$X1 %>%
  .[stri_detect_fixed(., ".")]
res

```

**Comment by LiNk-NY** [comment]
Thanks @DavidArenburg for providing that.

You should check the proportion and see that about 3% of the packages include periods in their names, according to your code. That's pretty seldom to me.

Anyway, this seems to be an issue for most of the `cloudyr/aws.*` packages, making it more difficult to change.
