### ISSUE TITLE
S3load "Instance Reachability" Failed

### ISSUE THREAD

**Issue by brobb1** [cloudyr/aws.s3#108]
Hi!

I'm trying to upload a large .RData file. It's a conditional random forest model so to my knowledge I can't split it up. 

On the RStudio AMI I'm trying to upload the .RData file from my S3 bucket. However after setting the environment and running: 

`b<-bucketlist()`
`s3load("CRFModel_ff_V5.RData",bucket=b[1,1])`

The command just runs non-stop, and from the EC2 Management Console I get the status check error:
"Instance reachability check failed"

On Amazon Web Services I have not found any documentation explaining in detail what this error means. I am honestly not sure if this is a problem in the function, how I am using the function, or something wrong with the .RData itself. 

I've run s3load() on smaller .RData files and it worked without a problem.

Any thoughts would be extremely appreciated. 
Thank you very much.

**Comment by leeper** [comment]
My immediate guess is some kind of memory issue, but it's not something I've ever encountered.

There seems to be a general pattern that these convenience functions - especially `s3load()` - is causing trouble on large files, so it's on my agenda to investigate.

**Comment by leeper** [comment]
Closing for now, as I think this is fixed by https://github.com/cloudyr/aws.s3/commit/12332edbdddff484b9f7c999fe31e2baf43d5679
