### ISSUE TITLE
S3 Compatible Storage

### ISSUE THREAD

**Issue by rossvoorhees** [cloudyr/aws.s3#109]
Is possible to use this package for S3 compatible storage. For S3 compatible storage I need to specific an endpoint and then just enter the following:

Access Key Id -
Secret Access Key - 
REST Endpoint (an API endpoint)

**Comment by leeper** [comment]
Can you be more specific about what you mean?

**Comment by rossvoorhees** [comment]
Yes, we an Amazon S3 compatible storage which I provide the Access Key ID,
Secret Access Key and an endpoint such at server name and domain. An
example would be xxxxxxxx401.corp.xxx.net.

http://s3browser.com/s3-compatible-storage.aspx provdes an explanation.

I don't see a way to connect using the aws.s3 package.

On Mon, Jan 30, 2017 at 10:12 PM, Thomas J. Leeper <notifications@github.com

**Comment by leeper** [comment]
This is not currently supported and I don't intend to add it, but I am willing to accept a PR to make the package work - it may only require adding a `baseurl` argument to [`s3HTTP()`](https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R) and passing that through to [`setup_s3_url()`](https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L167) [here](https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L51).

Please feel free to send a PR.
