### ISSUE TITLE
Using the package behind a proxy

### ISSUE THREAD

**Issue by GiulianoFormato** [cloudyr/aws.s3#110]
Hi @leeper , 

I am trying to use the package behind a corporate proxy. I have passed to get_bucket the input "use_proxy()" that should make httr::GET work behind a proxy, but I am getting this issue:

![image](https://cloud.githubusercontent.com/assets/17035500/22688257/b43d8e24-ed2b-11e6-877d-90846781ea92.png)

Have you got any suggestion for this topic?

Many thanks!
Giuliano

**Comment by leeper** [comment]
Would you be able to `traceback()` that error? Looks like it could be a low-level issue in httr, but I'm not 100% sure.

**Comment by GiulianoFormato** [comment]
Sorry for the incomplete question. You are right:
![image](https://cloud.githubusercontent.com/assets/17035500/22690153/a1eccab0-ed34-11e6-9416-8a974d1e595e.png)

It seems to happen when specifying both input parameters "query" and "proxy". Do you have any suggestion on how to workaround this?
I will have a look around as well and if I find anything I will let you know.

Many thanks!

**Comment by leeper** [comment]
Hmm. I've never seen this before and some googling did not generate any obvious answers.

I've put out the bat signal for some help: https://twitter.com/thosjleeper/status/829002274961760257 Hopefully someone will have an answer.

**Comment by hrbrmstr** [comment]
can you wrap the `get_bucket` call with `httr::with_verbose()`? i.e.

    httr::with_verbose(get_bucket(…params…))

also "corporate proxy" … authenticated proxy or just a proxy (and do you know the flavor of proxy server)?

**Comment by GiulianoFormato** [comment]
Hi @hrbrmstr ,
I have tried to wrap the function as you asked:
![image](https://cloud.githubusercontent.com/assets/17035500/22782748/df1a8b44-eec8-11e6-9e52-ebc2fe88a6fe.png)

The output result is the same. Using trace back:

```
10: vapply(elements, encode, character(1))

9: compose_query(url$query)

8: build_url(utils::modifyList(old, new))

7: handle_url(handle, url, ...)

6: GET(url, H, query = query, ...)

5: s3HTTP(verb = "GET", bucket = bucket, query = query, parse_response = parse_response, 
       ...)

4: get_bucket(bucket = AWS$AWS_BUCKET_NAME, region = AWS$AWS_DEFAULT_REGION, 
       key = AWS$AWS_ACCESS_KEY_ID, secret = AWS$AWS_SECRET_ACCESS_KEY, 
       check_region = FALSE, use_proxy(url = proxy$url, port = proxy$port, 
           username = proxy$usr, password = proxy$psw))

3: force(expr)

2: with_config(verbose(...), expr)

1: httr::with_verbose(get_bucket(bucket = AWS$AWS_BUCKET_NAME, region = AWS$AWS_DEFAULT_REGION, 
       key = AWS$AWS_ACCESS_KEY_ID, secret = AWS$AWS_SECRET_ACCESS_KEY, 
       check_region = FALSE, use_proxy(url = proxy$url, port = proxy$port, 
           username = proxy$usr, password = proxy$psw)))

```

As to the proxy authentication, the issue occurs with both the cases. If you need some more information about the proxy I can ask them to our sys admin. In that case, could you please tell me what you need specificly? 
Thanks!

**Comment by leeper** [comment]
I'm closing for now as this is outside the scope of what I can support.
