### ISSUE TITLE
s3sync function not exported

### ISSUE THREAD

**Issue by sahilseth** [cloudyr/aws.s3#111]
Hi,

I would like to use the s3sync function, and seems it is not exported. Is the function not really supported?

Thanks!
Sahil

**Comment by leeper** [comment]
It's untested! Feel free to use it via `aws.s3:::s3sync()` and give some feedback, but I make no promises about it.

**Comment by sahilseth** [comment]
thanks for your quick reply!

I tried, but it did not work.

```
aws.s3:::s3sync(bucket = 'xxxxxxx')
Error in if (attr(b, "Marker") != list()) { : argument is of length zero
```

As a workaround am using,

```
Sys.setenv("AWS_ACCESS_KEY_ID" = "XXXXXXXXX",
             "AWS_SECRET_ACCESS_KEY" = 'XXXXXXXXX')
cmd_sync = sprintf("aws s3 sync s3://%s %s", 
                     bucket, tools::file_path_as_absolute(out_dir))
system(cmd_sync)
```

**Comment by leeper** [comment]
Merge into #20
