### ISSUE TITLE
Deployment Shiny Apps

### ISSUE THREAD

**Issue by Jeremy-Dudek** [cloudyr/aws.s3#113]
Hi all,

Since few days (maybe two weeks), I can't deploy my shiny apps to shinyapps.io since it tells me:

Warning: Error in <Anonymous>: there is no package called ‘aws.s3’

I don't understand and I tried a lot of different ways to solve this issue but I did not success.
I'm a bit surprised since it perfectly works before (and locally).

Thank you,
regards,

**Comment by leeper** [comment]
You need the package installed. Perhaps you're trying to install from CRAN rather than Github.

**Comment by Jeremy-Dudek** [comment]
I'm not sure to understand your point.
Deploying the app on shiny apps.io does not authorize to install the package, only call it. 
That's my point.

**Comment by leeper** [comment]
I don't really know enough about shiny to provide support on this. It sounds like it's an issue on their end; so I would suggest you contact RStudio about it.

**Comment by Jeremy-Dudek** [comment]
Ok, but could you please help me, because it seems I need to install it using devtools::github_install() in order to be able to use it with shinyapps.io

However I have this output when I try :

* installing *source* package 'aws.s3' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error in library.dynam(lib, package, package.lib) : 
  DLL 'xml2' not found: maybe not installed for this architecture?
Erreur : le chargement a échoué
Exécution arrêtée
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Jeremy/Documents/R/win-library/3.3/aws.s3'

Thank you,

**Comment by leeper** [comment]
The error is the fault of [the xml2 package](https://cran.r-project.org/package=xml2) on which aws.s3 depends. You might try updating it, or try the following as a workaround:

```r
devtools::install_github("cloudyr/aws.s3", args = "--no-multiarch")
```
