### ISSUE TITLE
Unable to deploy Shiny app on shinyapps.io when using aws.s3 package

### ISSUE THREAD

**Issue by greysunil** [cloudyr/aws.s3#114]
Preparing to deploy document...DONE
Uploading bundle for document: 159543...Error: Unable to retrieve package records for the following packages:
- "aws.s3"
Execution halted

**Comment by leeper** [comment]
Do you have a question?

**Comment by greysunil** [comment]
Yes. I am Unable to deploy Shiny app on shinyapps.io when using aws.s3 package. Can you please help me? This is what the output shows when I am trying to deploy my shiny app:

*Preparing to deploy document...DONE
Uploading bundle for document: 159543...Error: Unable to retrieve package records for the following packages:

"aws.s3"
Execution halted*

Even though my app works locally.

**Comment by leeper** [comment]
This is a duplicate of #113

**Comment by leeper** [comment]
You can reinstall the package using devtools then try to deploy again. If that doesn't work, the issue is with shiny, so I would suggest reporting the problem there.

**Comment by greysunil** [comment]
Thanks.
