### ISSUE TITLE
s3save() does not see variables defined within a function

### ISSUE THREAD

**Issue by Javdat** [cloudyr/aws.s3#115]
If `s3save()` is called within a function and is passed a variable that is defined in in the same function, `s3save()` can not find it.

```
a <- function(){
    x <- iris
    s3save(x, bucket ="my_bucket", object = "test.RData")
}
```

```
> a()
 Error in save(..., file = tmp) : object ‘x’ not found 
```

But this works:
```
a <- function(){
    s3save(x, bucket ="my_bucket", object = "test.RData")
}
```

Also `s3saveRDS()` is not affected (works as expected):
```
a <- function(){
    x <- iris
    s3saveRDS(x, bucket ="my_bucket", object = "test.RData")
}
```

**Comment by leeper** [comment]
I've just added an `envir` argument to `s3save()` which should resolve this. It works on your examples. Please reinstall from GitHub and let me know if you continue to experience this.

**Comment by Javdat** [comment]
It works as expected with the latest github version. Thank you.
