### ISSUE TITLE
error occurs in get_bucket

### ISSUE THREAD

**Issue by xie67** [cloudyr/aws.s3#119]
When I typed following commands, error occurred. Is there any solutions.
> get_bucket( bucket = 'tsymedia')
Bucket: tsymedia
$Contents
Key:            Feeds/pixel_feed/pixel_feed_20170123225924_part_0.tsv
LastModified:   2017-02-09T20:17:21.000Z
ETag:           "aad0a45bb869966558ccb0e8b9b42fe6"
Size (B):       1430944
Error in x$Owner$DisplayName : $ operator is invalid for atomic vectors

**Comment by xie67** [comment]
I get the Key using:
> x[[1]]$Key
[1] "Feeds/pixel_feed/pixel_feed_20170123225924_part_0.tsv"

However, length(x) is 1000, is that the default return number?

**Comment by leeper** [comment]
Yes, the default return is 1000 objects from the bucket. If you set `max` to a value greater or less than that, the requested number of results will be returned.

You can also use `get_bucket_df()` to work with objects as a data frame rather than a list of objects.
