### ISSUE TITLE
Code coverage service

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.s3#12]
Is coveralls not showing numbers because we haven't authorized them on cloudyr? That would be my impression. They want full read-write access to repos, so I'm a little hesitant to grant that authorization. The alternative would be to switch to codecov.io, which doesn't expect as much repo access. But, I don't have a lot of experience with either service.

Either way, let's get a test coverage shield in the README.

**Comment by cboettig** [comment]
:+1: for codecov.io.  I've been using coveralls recently but have been intending to move my repos over to codecov.io anyway.

**Comment by leeper** [comment]
Okay, this is done as of https://github.com/cloudyr/aws.s3/commit/3e8df6f17624aa29fd28193317088356ec5cd0ba

Here's the coverage report: https://codecov.io/github/cloudyr/aws.s3?ref=master
