### ISSUE TITLE
Issue while reading .rds/.rda file from s3

### ISSUE THREAD

**Issue by aiyerganapathy** [cloudyr/aws.s3#120]
Hi,

I am trying to read a `.rds` /`.rda` file from s3 using `s3load()` and I am getting the following error:
`Error in load(tmp, envir = envir) : 
  the input does not start with a magic number compatible with loading from a connection`

I also tried using s3readRDS to read the `.rds` and I am getting the following error:
```
Error in memDecompress(from = as.vector(r), type = "gzip") : 
  internal error -3 in memDecompress(2)
```

Any suggestions on how to resolve this will be very helpful.

**Comment by millerh1** [comment]
Why did you close this issue? I also have this problem
