### ISSUE TITLE
Unable to Use put_object() to upload File into S3 Bucket

### ISSUE THREAD

**Issue by soleyjh** [cloudyr/aws.s3#121]
Hello!

Please forgive me if my question has already been asked I swear I looked or if this is completely ignorant...my first time using this package!

My code is as follows (with anything uniquely identifying my bucket or id removed):

zz <- rawConnection(raw(0), "w")
write.table(filename, zz, sep='|', quote=FALSE, col.names = FALSE, row.names=FALSE)

put_object(file = rawConnectionValue(zz),
                   bucket = "EXAMPLE1", object = "actives_seg.csv")

---------------------------------------------------------------------------------------------------------

My Error is as follows (with anything uniquely identifying my bucket or id removed):

_List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr ""
 $ HostId   : chr ""
 - attr(*, "headers")=List of 7
  ..$ x-amz-request-id : chr ""
  ..$ x-amz-id-2       : chr ""
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Mon, 20 Mar 2017 20:27:33 GMT"
  ..$ connection       : chr "close"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
 - attr(*, "request_canonical")= chr "PUT\n//"| __truncated__
 - attr(*, "request_string_to_sign")= chr "us-east-1/s3/aws4_request\"| __truncated__
 - attr(*, "request_signature")= chr " Credential=/20170320/us-east-1/s3/aws4_request, SignedHeaders=content-length;host;x-amz-da"| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403)._

**Comment by soleyjh** [comment]
I just solved my own problem.

We have Server Side Encryption. You need to add the:

headers = c('x-amz-server-side-encryption' = 'AES256') option in the put_object function

**Comment by seunaa** [comment]
@leeper thanks for this library, I am also getting the same error mentioned above by @soleyjh. below is my code:

```R
 Sys.setenv("AWS_ACCESS_KEY_ID" = "......",
            "AWS_SECRET_ACCESS_KEY" = "..........",
            "AWS_DEFAULT_REGION" = "eu-west-1" 
            )
 
 get_bucket(bucket = "my_bucket",
            check_region = FALSE,
            verbose = TRUE
            )
 
 put_object(file = "file_path", 
            object = "file_name", 
            bucket = "my_bucket",
            headers = c('x-amz-server-side-encryption' = 'AES256'))
```

`get_bucket()` returns the content of the bucket but `put_object()` throws access denied error with details below:

```R
List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr ""
 $ HostId   : chr ""
 - attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr ""
  ..$ x-amz-id-2       : chr ""
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Tue, 05 Sep 2017 13:23:42 GMT"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
 - attr(*, "request_canonical")= chr "GET\n/"| __truncated__
 - attr(*, "request_string_to_sign")= car ""| __truncated__
 - attr(*, "request_signature")= chr "AWS4-HMAC-SHA256 Credential=| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).
``` 

Credentials and id strings  removed from log log above.

**Comment by cvrnogueira** [comment]
@seunaa did you have any success on this? I am having this error :(
