### ISSUE TITLE
Problem with accessing buckets

### ISSUE THREAD

**Issue by lmavridis** [cloudyr/aws.s3#122]
We currently have production buckets with reduced priviledges in S3 we were running version 0.1.30 successfully and were able to access those buckets.

When we upgraded to version 0.2.1 we started receiving 

> Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
> Forbidden (HTTP 403).

**Comment by leeper** [comment]
Hard to say without more information, but I would guess one of two things:

 - Region handling. This seems to still be causing some problems. What region are the buckets in and how are you specifying that?
 - The path style for the bucket URLs. Do the bucket names have `.` in them? Could try the request again with `path_style = "virtual"` to get to the former (<0.2.0) default

**Comment by leeper** [comment]
@lmavridis Any update on whether you got this working?

**Comment by lmavridis** [comment]
Hi @leeper 

Have retracted the versions for now to before 0.1.30, to work with the aforementioned buckets. We are going to check the behaviour with `path_style = "virtual" ` and update you here

**Comment by kwent** [comment]
Hi,

We are seeing the same issue here in our end. Rollbacking to https://github.com/cloudyr/aws.s3/commit/c71daa6ba3fa38df965550b7fcb251e6492c1b64 is working fine again ... (I picked this sha randomly...)

Here was code to test

```R
devtools::install_github("cloudyr/aws.s3", ref="c71daa6ba3fa38df965550b7fcb251e6492c1b64")
library(aws.s3)

s3HTTP(verb = "HEAD",
       bucket = 'my_bucket',
       key='my_key',
       secret='my_secret')
```

**Comment by leeper** [comment]
@kwent and @lmavridis Can you let me know what region(s) you're working in? And whether your bucket names have any dots `.` in them?

**Comment by kwent** [comment]
My bucket is with no dot like "bucket-name". My region is the default one:
us-east-1. Modifying the path virtual to true didn't fix anything.

**Comment by leeper** [comment]
Flagging this as related to https://github.com/cloudyr/aws.s3/issues/106

**Comment by leeper** [comment]
@kwent And if you set `check_region = FALSE` does it work?

**Comment by lmavridis** [comment]
@leeper Our region is eu-west-1 and there are not dots in the bucket names

**Comment by SkylerFRRS** [comment]
I have this problem since my package aws.s3 was updated to 0.3.5 version. I needed to do the rollback to version 0.3.3 and now it works fine.

**Comment by leeper** [comment]
@skylerfrrs Can you provide more information? I need the exact code you used, with the `verbose =TRUE` argument including all output and `sessionInfo()`.

**Comment by SkylerFRRS** [comment]
To acess S3:
Sys.setenv("AWS_ACCESS_KEY_ID" = "my_AWS_ACCESS_KEY_ID",   
           "AWS_SECRET_ACCESS_KEY" = "my_AWS_SECRET_ACCESS_KEY",
           "AWS_DEFAULT_REGION" = "my_AWS_DEFAULT_REGION"
)
bucket_name<-"bucket_name"  

and testing this:
s3obj<-aws.s3::get_object(bucket = bucket_name, object = "object_dir")

this works perfectly for me!!!

system information:
(...)
other attached packages:
 [1] aws.s3_0.3.3        SparkR_2.1.1  (...)

With aws.s3 version 0.3.5 the function get_object( ) returns an error:
 "Error in parse_aws_s3_response(r, Sig, verbose = verbose) :
Forbidden (HTTP 403)."

**Comment by leeper** [comment]
I believe this will have been fixed via #142. Can you reinstall and confirm?

**Comment by ljodea** [comment]
I am having this exact same error with multiple versions of aws.s3 including 0.3.3 0.3.5 and 0.2. I'm running from an EC2 instance, from a private IP. 

`Sys.setenv("AWS_DEFAULT_REGION" = "ap-southeast-1",
           "AWS_IAM_ROLE_ARN" = "< hidden >",
           "AWS_BUCKET_NAME" = "< hidden >",
           "AWS_ACCESS_KEY_ID" = "< hidden >",
           "AWS_SECRET_ACCESS_KEY" = "< hidden >",
           "AWS_SESSION_TOKEN" = "< hidden >"`

Run this:

`s3HTTP(verb = "GET", bucket = Sys.getenv("AWS_BUCKET_NAME"), query = alist(policy = ""), check_region = TRUE, verbose = TRUE)`

I run versions of the above query, sometimes with check_region = FALSE, sometimes with a different query, sometimes with path_style = "virtual", and it always returns the following:

`S3 Request URL: https://s3-ap-southeast-1.amazonaws.com/< hidden >/
Executing request with AWS credentials
Parsing AWS API response
Client error: (403) Forbidden
List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr "< hidden >"
 $ HostId   : chr "< hidden >"
 - attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr "< hidden >"
  ..$ x-amz-id-2       : chr "< hidden >"
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Thu, 21 Sep 2017 06:10:23 GMT"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
 - attr(*, "request_canonical")= chr "< hidden >"| __truncated__
 - attr(*, "request_string_to_sign")= chr "< hidden >"| __truncated__
 - attr(*, "request_signature")= chr "< hidden >"| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).`

And no there is no "dot" in bucket name.

Session info:

`R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.7.3           purrr_0.2.3           readr_1.1.1           tidyr_0.7.0           tibble_1.3.4          ggplot2_2.2.1         tidyverse_1.1.1      
 [8] config_0.2            redshiftTools_0.1.1   RPostgres_0.1-6       aws.ec2metadata_0.1.3 aws.signature_0.3.6   aws.s3_0.3.3         

loaded via a namespace (and not attached):
 [1] reshape2_1.4.2   haven_1.1.0      lattice_0.20-35  colorspace_1.3-2 yaml_2.1.14      base64enc_0.1-3  blob_1.1.0       rlang_0.1.2      foreign_0.8-69  
[10] glue_1.1.1       DBI_0.7-12       bit64_0.9-7      modelr_0.1.1     readxl_1.0.0     bindrcpp_0.2     bindr_0.1        plyr_1.8.4       stringr_1.2.0   
[19] munsell_0.4.3    gtable_0.2.0     cellranger_1.1.0 rvest_0.3.2      psych_1.7.5      forcats_0.2.0    curl_2.8.1       parallel_3.4.1   broom_0.4.2     
[28] Rcpp_0.12.12     scales_0.5.0     jsonlite_1.5     bit_1.1-12       mnormt_1.5-5     hms_0.3          digest_0.6.12    stringi_1.1.5    grid_3.4.1      
[37] odbc_1.1.1       tools_3.4.1      magrittr_1.5     lazyeval_0.2.0   pkgconfig_2.0.1  xml2_1.1.1       lubridate_1.6.0  assertthat_0.2.0 httr_1.3.1      
[46] R6_2.2.2         nlme_3.1-131     compiler_3.4.1 `

Any idea why this is happening?

**Comment by matt-jay** [comment]
Adding `check_region = F` to calls solved this for me, see https://github.com/cloudyr/aws.s3/issues/175.

**Comment by gm3dmo** [comment]
I experienced this recently too. Write up here:

https://gist.github.com/gm3dmo/418320c79f48005c740e7ae148a3883c

**Comment by david-waterworth** [comment]
Seeing this myself with region='ap-southeast-2', check_region = F fix worked

**Comment by leeper** [comment]
I've changed the default to `check_region = FALSE` (as of https://github.com/cloudyr/aws.s3/commit/280c049a5c13849f44b8a67cb59079ccd922deca). If anyone wants to run some tests and let me know if they encounter problems (more or fewer), that would be great.
