### ISSUE TITLE
Typo in setup_s3_url(): url_stlye vs. url_style

### ISSUE THREAD

**Issue by sebastianbafoodora** [cloudyr/aws.s3#123]
Just recognized this typo in one of the if conditions of the setup_s3_url function in aws.s3/R/s3HTTP.R, see: https://github.com/cloudyr/aws.s3/blob/93325b01de9bd27896cdcb55eacc54bc69383c80/R/s3HTTP.R#L202
Other than that, nice package, thanks 👍

**Comment by leeper** [comment]
Thank you!
