### ISSUE TITLE
Read xml.gz files from AWS to R 

### ISSUE THREAD

**Issue by samistat08** [cloudyr/aws.s3#124]
Hello everyone!

I have bunch of xml zipped files on S3 and I wonder if there is a way to directly read and process them with R, on my local machine. I already connect to S3 and see my buckets, use the following command to get the file 

```R
get_object( bucket = "name",object ='14h16m39s.xml.gz')
```

and I get something like this

```R
[1] 1f 8b 08 00 00 00 00 00 00 00 d4 bd 5b 93 1b b9 b5 2e f8 7e 7e 05 43 2f 33 13 de 49 e2 7e e9 b0 cf 09 49 2d b9 db 96 64 1d 49 b6 ce 9e 17 47 92
 [49] 4c aa 38 2a 91 da ac 92 64 9d 98 1f 3f 00 88 5b 22 93 59 c8 34 41 d6 d8 11 dd 68 b6 9a c9 95 ```

Is it possible to get R directly connected to S3? and how? 
Thanks a lot :)

**Comment by leeper** [comment]
What you get back is a raw vector (think "string of bytes"). You can then do whatever you want with that - either read it as a connection (see `rawConnection()`) using a relevant function or use `save_object()` instead to save it locally and import it as a file.
