### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by jimhester** [cloudyr/aws.s3#126]
Are there any plans to put **aws.s3** on CRAN? I currently have a conditional dependency on it in the devel version of [memoise](https://github.com/hadley/memoise) and was planning a CRAN release.

If **aws.s3** is not going to CRAN soon I can use the cloudyr drat repository in `Additional_repositories :`, so let me know one way or the other.

**Comment by leeper** [comment]
I can probably get it on CRAN in the next few days if need be. What's your release timeline?

**Comment by jimhester** [comment]
I decided to just submit now with the drat repo in `Additional_repositories`, so no rush, but it would be nice to have this on CRAN at some point!

**Comment by leeper** [comment]
Okay, seems a reasonable solution. I'll try to remember to ping you once this is actually on CRAN.

**Comment by leeper** [comment]
I've shipped this to CRAN.

**Comment by jimhester** [comment]
Thanks!
