### ISSUE TITLE
Error when setting max to Inf in get_bucket

### ISSUE THREAD

**Issue by Serenthia** [cloudyr/aws.s3#127]
The documentation says:

> Use \code{max = Inf} to retrieve all objects

however then `pmin(1000, as.integer(max))` produces an NA and a warning, meaning `parse_aws_s3_response` fails.

Please could Inf be supported in order to return all files?

**Comment by leeper** [comment]
Done. Thanks.

**Comment by Serenthia** [comment]
Unfortunately, yesterday's release still has an error in [Line 55 of get_bucket](https://github.com/cloudyr/aws.s3/blob/master/R/get_bucket.R#L55):

`"max-keys" = as.integer(pmin(max - r[["MaxKeys"]], 1000))`
needs to be
`"max-keys" = as.integer(pmin(max - as.integer(r[["MaxKeys"]]), 1000))`

Many thanks
