### ISSUE TITLE
Read all files from a folder in S3 bucket in R

### ISSUE THREAD

**Issue by samistat08** [cloudyr/aws.s3#134]
I am using cloudyr/aws.s3 and connect to my bucket and folder and am able to read one xml file using s3_read. I need to read all files in this folder. If I have these files locally, I will access the list of files easily with dir() and put them in a loop. But I do not know how can I get the list of files in folders on s3 to put them in a loop. 

Thanks a lot for the help in advance

**Comment by leeper** [comment]
Use `get_bucket(max = Inf)` or `get_bucket_df(max = Inf)` to retrieve all object keys for a bucket. You can then loop over the keys, passing each to `get_object()` or another read function.

**Comment by samistat08** [comment]
Thanks a lot Leeper. But it takes like forever to return all keys since I have a huge amount of data in different folders. I need data on one sub folder of a bucket. Should I redesign my buckets in s3 and put every folder in a bucket? seems that s3 does not consider folders inside buckets!

**Comment by leeper** [comment]
@samistat08 Use the `prefix` argument, which will restrict the returned keys to those that begin with the prefix. S3 is a flat file store, so there are no folders and `/` has no special meaning. Thus there are just "pseudo-folders" defined by object keys that start with some characters followed by a `/`. Using the `prefix` should give you to something similar to "all objects from a folder".

**Comment by samistat08** [comment]
I actually used `get_bucket(bucket_name, prefix="folder/subfolder/subsubfolder")` and it works , thanks.

**Comment by leeper** [comment]
Great!

**Comment by srane163** [comment]
After I point my s3 location path to the subsubfolder, I can see 201 csv files in the list but the output of list.files() comes out to be Character(0) and so I am not able to iterate through the list. 

my_Bucket <- get_bucket("Bucket_name")
files <- get_bucket(my_Bucket, prefix="demo/input/test")
fileList <- list.files(path = "files", pattern=".csv", all.files = TRUE, recursive=FALSE)
fileList

> fileList
character(0)

Can you help me with my approach or suggest a solution so that I can iterate through the list using the key names of those 201 csv files, and read all the 201 object files together?  @leeper

**Comment by leeper** [comment]
@srane163 You can't use `list.files()` to see objects in S3 - that's only for local files. Your `files` object is a list of object keys. You can just `lapply(files, get_object)` to get a list of the objects (as raw vectors), which you can then parse using whatever you want.

**Comment by Garglesoap** [comment]
I've noticed the 
my_Bucket <- get_bucket("Bucket_name")
creates an object in which there's a variable called '$LastModified' - is there anyway to extract the file name of last modified for a specific folder? (preferably as character)

**Comment by harsh3264** [comment]
I am only able to fetch 1000 files as limit how do I fetch all the files for a specific day?

**Comment by tamuanand** [comment]
> lapply(files, get_object)


Hi @leeper 

I am new to this and I have a similar issue. 

I need a list.files like example to identify all my S3 subfolders that contain a file with specific pattern and operate on that list with regular R code (use readr on each of these files in that folder path).

Would it be possible for you to share an example of how you would do it - Thanks

> @srane163 You can't use `list.files()` to see objects in S3 - that's only for local files. Your `files` object is a list of object keys. You can just `lapply(files, get_object)` to get a list of the objects (as raw vectors), which you can then parse using whatever you want.
