### ISSUE TITLE
Making objects Public 

### ISSUE THREAD

**Issue by koushiksaha89** [cloudyr/aws.s3#137]
While uploading the objects in the bucket in s3 i want to mark it for public access . Could not find any options in the put_object method.  Opening this ticket for this.

**Comment by leeper** [comment]
Yes, this could be better documented. At present you have to pass it as a header, as described in [the API docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html):

```R
put_object(object, "s3://bucket/objectkey", headers = list(`x-amz-acl` = "public"))
```

I'll update the docs and possibly add an explicit argument for this.

**Comment by koushiksaha89** [comment]
thanks for the update

**Comment by leeper** [comment]
@koushiksaha89 I've added an `acl` argument to `put_object()` and `put_bucket()` so you can now just do:

```R
put_object(object, "s3://bucket/objectkey", acl = "public-read")
```

**Comment by jmorten** [comment]
How does one place an `acl` on an already created object or bucket?

**Comment by leeper** [comment]
Use `put_acl()`. Works on either an object or a bucket.

**Comment by jmorten** [comment]
Sorry, I am confused as what to pass to the function. 

`put_acl(object = 'folder/iris.txt', bucket = 'mybucket', ?????)`

**Comment by leeper** [comment]
Sorry, this has required specifying an ACL body, as described in: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTacl.html

But, I've just sent an update that adds a `put_object()`-style `acl` argument, which will accept canned ACL values. You'll need to pull the latest version from GitHub to get this functionality.
