### ISSUE TITLE
s3saveRDS now creates a "folder" instead of a file

### ISSUE THREAD

**Issue by Serenthia** [cloudyr/aws.s3#139]
Since the last release (0.3.3), s3saveRDS appears to be creating a "folder" (inasmuch as there are folders in S3) instead of a binary file.  I see that the put_folder function has been added, but can't see how that would affect s3saveRDS.

Can confirm that rolling back to 0.3.2 fixes it.

**Comment by leeper** [comment]
Hi Serenthia, can you provide a quick example just so I'm working from the same code as you?

**Comment by Serenthia** [comment]
Of course.  Nothing complex!

```
df <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))
aws.s3::s3saveRDS(x = df, bucket = "s3Bucket", object = "savepath")
```

**Comment by leeper** [comment]
Thanks. At least for me, this works without error (in v0.3.3):

```R
s3saveRDS(x = df, object = "savepath", bucket = "mybucket")
s3readRDS("savepath", bucket = "mybucket")
##   a b
## 1 1 4
## 2 2 5
## 3 3 6
```

And shows up in the S3 console correctly:

![bucket](https://cloud.githubusercontent.com/assets/3505428/26728957/de23e1f2-47a3-11e7-93c8-ccce5ff85d87.png)

**Comment by Serenthia** [comment]
Whereas I get the following:

<img width="240" alt="s3folders" src="https://cloud.githubusercontent.com/assets/346717/26732075/3a285d8e-47ae-11e7-8c16-6562fb2142c4.png">

As I say, rolling back to 0.3.2 creates files as expected.  I can't think of anything else that might be different...  my region is eu-west-1, which shouldn't affect anything.

**Comment by leeper** [comment]
Weird. Can you run this with `verbose = TRUE` and copy in the output? Presumably there is a `/` being appended somewhere in the process. I fear it may be in a way that is platform-dependent. Maybe give me `sessionInfo()` as well?

**Comment by Serenthia** [comment]
I've tracked down the issue and I'm afraid it's on my end.  My wrapper function creates the directory path and has always been putting a "/" at the end.  This hasn't mattered as your code didn't support creating folders.  Now that it does, it correctly assumed that was a directory name!

Apologies for wasting your time and thanks for the investigation.

**Comment by leeper** [comment]
Hey, no problem. Glad you got it worked out.
