### ISSUE TITLE
SSL Cert Error

### ISSUE THREAD

**Issue by sdeshpande** [cloudyr/aws.s3#140]
Hi,

Is there an ability to specify aws flag "--no-verify-ssl" with your package ?
Our computers are behind corporate proxy and without this flag any aws command fails.

Regards,
Saurabh

**Comment by leeper** [comment]
Yes. These options are expressed through libcurl. See `httr::httr_options()` or possibly, `httr::use_proxy()`, which you can pass via the `...` argument to any aws.s3 function.

**Comment by sdeshpande** [comment]
Thank you. I will ask our developers to attempt this and will confirm the results.

**Comment by washcycle** [comment]
This is how I handle corporate CAs.

Sys.setenv("AWS_ACCESS_KEY_ID" = "XXXXXXXXXXXXXXXXXXXXX",
           "AWS_SECRET_ACCESS_KEY" = "XXXXXXXXXXXXXXXXXXX",
           "AWS_DEFAULT_REGION" = "us-west-1",
           #"AWS_SESSION_TOKEN" = ,
           "CURL_CA_BUNDLE" = "corpCA.crt"
           )

**Comment by sdeshpande** [comment]
Thank you

**Comment by jdonnell01** [comment]
Hello,

I tried setting the CURL_CA_BUNDLE environment variable as mentioned above and I get the following error: SSL certificate problem: unable to get local issuer certificate.

Is it supported to leverage the http/verify parameter? (described here: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#verify)

// Use a custom CA bundle
$client = new DynamoDbClient([
    'region'  => 'us-west-2',
    'version' => 'latest',
    'http'    => [
        'verify' => '/path/to/my/cert.pem'
    ]
]);

R implementation would be something such as:
```
    s3saveRDS(x = DATAFRAME,
              object = OBJECT,
              bucket = BUCKET,
              verbose = T,
              check_region = F,
              region = REGION,
              base_url = URL,
              http = list(verify = "path to cert"))
```
