### ISSUE TITLE
Facing problem while saving data to AWs 

### ISSUE THREAD

**Issue by sivasai5148** [cloudyr/aws.s3#141]
I am trying to save data from R Studio  to AWS S3 Bucket .
I had the bucket name like  `s3://abc.analytics/application/saved`
                Access ID like XXXXX
                Secret key like XXXXX

and r object `mtcars` as a dataframe 

currently trying to use this piece of code 

```R
library("aws.s3")
s3save(key = 'XXX',
       secret = 'XXX',
       bucket = 's3://abc.analytics/application/saved',
       mtcars,
       object ='test.Rdata'
      )
Error in save(..., file = tmp, envir = envir) : 
  objects ‘dFDFEW12dS3/23dsCscdD325454Wed’, ‘OMCDS232MM133NN’ not found
```

I am new to R Programming please suggest me if i need to make any changes.
THANKS IN Advance.

**Comment by leeper** [comment]
The problem is the order that you are trying to pass the arguments. Take a look at the documentation in `? s3save` for clarification. It's easier to set your access key and secret access key as environment variables so you don't have to pass them to every function. If you want to pass them as arguments to each function, put them *after* the `bucket` and `object` arguments (i.e., at the very end of the function call).

**Comment by sivasai5148** [comment]
```
library("aws.s3")
Sys.setenv("AWS_ACCESS_KEY_ID" = "OMCDS232MM133NN",
           "AWS_SECRET_ACCESS_KEY" = "dFDFEW12dS3/23dsCscdD325454Wed")

# save an in-memory R object into S3
s3save( mtcars,
        bucket = "s3://abc.analytics//application//saved",
        object ="test.Rdata"
       )
```
changed it accordingly , now i am getting an error  

**Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403)**.

**Comment by leeper** [comment]
You really shouldn't be typing your Access Key and Secret Key into this forum. It is public - other users can use those credentials to steal and/or destroy your data.

What is your bucket actually called? Is it `abc.analytics//application//saved`? I imagine you might instead want:

```R
s3save(mtcars,
        bucket = "abc.analytics",
        object = "/application/saved/test.Rdata"
       )
```

There is no need to escape your `/`.

**Comment by sivasai5148** [comment]
Those are not actual Access Key and Secret Key  
and bucket name is 'abc.analytics'
the location where i need to save file is 's3://abc.analytics//application//saved'
```
s3save(mtcars,
        bucket = "abc.analytics",
        object = "/application/saved/test.Rdata"
       )
```
no luck,same error 
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).

**Comment by leeper** [comment]
Does the object name actually have `//` or is it just `/`?

**Comment by sivasai5148** [comment]
sorry, file to save location is s3://abc.analytics/application/saved

**Comment by leeper** [comment]
Then try (no leading `/` on the object key):

```R
s3save(mtcars,
        bucket = "abc.analytics",
        object = "application/saved/test.Rdata"
       )
```

**Comment by sivasai5148** [comment]
```
s3save(mtcars,
        bucket = "abc.analytics",
        object = "application/saved/test.Rdata"
       )
```
with this i am getting the same error saying 
**Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).**

`s3save(mtcars, object = "s3://abc.analytics/application/saved")`
or
`s3save(mtcars, bucket = "mon.datainsights",object = "s3://mon.datainsights/spotfire/exports")`
when it try these statements getting an error 
**Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).**  

`s3save(mtcars, object = "s3://abc.analytics/application/saved", verbose = TRUE)`
or 
`s3save(mtcars, bucket = "mon.datainsights",object = "s3://mon.datainsights/spotfire/exports", verbose = TRUE)`
with this 
**Error in save(..., file = tmp, envir = envir) : object ‘TRUE’ not found**

**Comment by leeper** [comment]
Can you show me the output of `sessionInfo()` ?

**Comment by sivasai5148** [comment]
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.2      aws.s3_0.3.1         RDCOMClient_0.93-0.2

loaded via a namespace (and not attached):
 [1] httr_1.2.1          R6_2.2.0            withr_1.0.2         base64enc_0.1-3     curl_2.5            memoise_1.1.0       Rcpp_0.12.9         aws.signature_0.2.9 xml2_1.1.1         
[10] git2r_0.18.0        digest_0.6.12

**Comment by sivasai5148** [comment]
any thoughts @leeper ,please help me out

**Comment by leeper** [comment]
Sorry, I gave some incorrect code above. Can you try again with:

```R
s3save(mtcars, object = "s3://abc.analytics/application/saved/test.Rdata", opts = list(verbose = TRUE))
```

You should get output that looks like:

```
Checking bucket region using get_location('abc.analytics')
Executing request using bucket region us-east-1
S3 Request URL: https://s3.amazonaws.com/abc.analytics/application/saved/test.Rdata
Executing request with AWS credentials
Parsing AWS API response
Success: (200) OK
```

or more details on the error.

**Comment by sivasai5148** [comment]
Right ,I got result same like as you pasted.

**Comment by leeper** [comment]
@sivasai5148 Then that means it worked.

**Comment by sivasai5148** [comment]
Ohh nice, up to now i am testing this code in R studio and now i am trying to integrate this in my application and execute there but receiving the below error .
Could you please look into this error and let me know what i have to include to overcome this error 
`Error in .loadNamespaceImpl(package, path, keep.source, partial) : error executing useDynLib for dynamic library 'xml2' from package 'xml2' loaded from C:/Users/SFUSER/Documents/TERR/x86_64-pc-windows-library/4.2 : Error in library.dynam(chname = chname, package = package, lib.loc = ... : Foreign binary xml2 could not be loaded'.
`

**Comment by leeper** [comment]
@sivasai5148  That looks odd. Can you successfully load the xml2 package on its own using `library("xml2")` ?

**Comment by sivasai5148** [comment]
even by specifying library("xml2") it is not working ,i am getting the same error .

**Comment by leeper** [comment]
@sivasai5148 You might want to try reinstalling xml2.

**Comment by sivasai5148** [comment]
I already done that but no luck

**Comment by leeper** [comment]
I would suggest inquiring with the xml2 maintainers here: https://github.com/r-lib/xml2

**Comment by sivasai5148** [comment]
sure i can do that @leeper but we are not using xml2 related functionalities then why it is looking for xml2 package 

even in R studio we are not writing `library("xml2")` and even i unchecked xml2 in the packages tab and not throwing me errors 

just want to understand why it is looking for "xml2"

**Comment by leeper** [comment]
It is used by aws.s3.

**Comment by sivasai5148** [comment]
but in R studio i am not facing this issue .There i have completely deleted the xml2 package but not getting the error  .

**Comment by leeper** [comment]
I think you would benefit from learning a bit about how R packages work. You can't delete a package that this package depends upon and expect it to work. The full list of dependencies is in the package DESCRIPTION file.
