### ISSUE TITLE
403 Access Denied  with R but work with CL

### ISSUE THREAD

**Issue by dkomd** [cloudyr/aws.s3#143]
Hi,
when trying to access get_object(s3://bucket/folderA/folderB/folderC/file.csv) 
I get the following error: 403 Access denied. 

However, when I use the CL with aws cp s3://bucket/folderA/folderB/folderC/file.csv local_file_name.csv  the file is downloaded...

If I am able to download the data with CL doesn't that mean that there is another issue with  get_object request? 

(also: I don't own the bucket, apparently I am just granted access to the s3//:bucket/folderA/folder
C/  but I cannot acess the s3://bucket by itself.

**Comment by leeper** [comment]
Can you give me `sessionInfo()` and rerun the command with the option `verbose = TRUE`?

**Comment by dkomd** [comment]
Here you go: 
List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr "BB124F1DF760468B"
 $ HostId   : chr "ViTcTk246xPpvvenp/8ucLijiGBHUQ4DdReegmV+mEBeJm5Xi6YgTtdrssLKNkbCwDHNGXbjaQQ="
 - attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr "BB124F1DF760468B"
  ..$ x-amz-id-2       : chr "ViTcTk246xPpvvenp/8ucLijiGBHUQ4DdReegmV+mEBeJm5Xi6YgTtdrssLKNkbCwDHNGXbjaQQ="
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Thu, 22 Jun 2017 19:32:33 GMT"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
 - attr(*, "request_canonical")= chr "GET\n/bucket_name/\nlocation=\nhost:s3.amazonaws.com\nx-amz-date:20170622T193234Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8"| __truncated__
 - attr(*, "request_string_to_sign")= chr "AWS4-HMAC-SHA256\n20170622T193234Z\n20170622/us-east-1/s3/aws4_request\na354df86c3c62144e5646cff09787298e3b57877b46ca52b804c31b"| __truncated__
 - attr(*, "request_signature")= chr "AWS4-HMAC-SHA256 Credential= key/20170622/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=0"| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).
> SessionInfo()
Error: could not find function "SessionInfo"
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Ireland.1252  LC_CTYPE=English_Ireland.1252   
[3] LC_MONETARY=English_Ireland.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Ireland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] data.table_1.10.4   plyr_1.8.4          reshape2_1.4.2      rlist_0.4.6.1      
 [5] fbRads_0.2          jsonlite_1.5        bindrcpp_0.1        magrittr_1.5       
 [9] dplyr_0.7.0         httr_1.2.1          aws.signature_0.3.2 aws.s3_0.3.3       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11         bindr_0.1            xml2_1.1.1           bit_1.1-12          
 [5] R6_2.2.1             rlang_0.1.1          stringr_1.2.0        tools_3.3.2         
 [9] lambda.r_1.1.9       futile.logger_1.4.3  openssl_0.9.6        bit64_0.9-7         
[13] assertthat_0.2.0     digest_0.6.12        tibble_1.3.3         futile.options_1.0.0
[17] base64enc_0.1-3      bitops_1.0-6         RCurl_1.95-4.8       curl_2.6            
[21] glue_1.0.0           stringi_1.1.5        httpuv_1.3.3         pkgconfig_2.0.1

**Comment by leeper** [comment]
How are you specifying your AWS credentials? Are they set as the appropriate environment variables? (You didn't include the verbose output, so I can't tell unfortunately.)

**Comment by dkomd** [comment]
I try to set up the environment variable through here: 
Sys.setenv("AWS_ACCESS_KEY_ID" = "key#",
           "AWS_SECRET_ACCESS_KEY" = "secret_key",
           "AWS_DEFAULT_REGION" = ""
)


typing verbose = TRUE  just gives me this :+1: 

Error in parse_aws_s3_response(r, Sig, verbose = verbose) :
 Forbidden (HTTP 403).

**Comment by leeper** [comment]
Folding this into https://github.com/cloudyr/aws.s3/issues/142

**Comment by saikrishnaklu** [comment]
Thanks

**Comment by cvrnogueira** [comment]
I still have this error, without check_region = FALSE it doesn't work. 
But this and the other issue that references this are closed, so they are corrected. 
Does anyone still have this error too?

**Comment by GregoryWiltshire** [comment]
I had this issue today, could write to same s3 bucket with boto3 no problem. 
With cloudyr aws.s3 I get 403 without parameter "check_region = FALSE".

**Comment by agnieszkabaranska** [comment]
@GregoryWiltshire have you figured it out how to do this using R? :)

**Comment by ShivaniKamathBelman** [comment]
I have the same issue. Using R aws.s3 package. I am not able to read file from S3 bucket. 
```Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403)```

**Comment by pitiznz** [comment]
I have had the same issue where:
- some aws.s3 functions such as get_bucket() are working for one bucket but not another (http error 403)
- using system command system aws s3 ls [bucketname] is working for all buckets

One difference between our buckets is user authentication, so this could possibly be causing the error... That said, s3HTTP and save_object are still working when I specify the path to the files im after:

library(aws.s3)
Sys.setenv("AWS_ACCESS_KEY_ID" = [AWS_ACCESS_KEY_ID],
"AWS_SECRET_ACCESS_KEY" = [AWS_SECRET_ACCESS_KEY],
"AWS_DEFAULT_REGION" = [AWS_DEFAULT_REGION])

save_object(object = [path],
                  bucket = [bucket],
                  check_region = FALSE,
                  verbose = TRUE,
                  overwrite = TRUE)

**Comment by jwilliamsholt** [comment]
I'm getting the following error with `s3sync`, but not other package functions that I've tried so far, including `get_bucket`. 

`Checking for existence of bucket 'mybucket'
Client error: (403) Forbidden
Error in s3sync(path = "C:/path/to", "mybucket",  : 
  Bucket 'mybucket' doesn't exist`

**Comment by mjng93** [comment]
Was this ever resolved? Having same issue
