### ISSUE TITLE
read in  csv  file in s3 bucket to dataframe and got an access denied error

### ISSUE THREAD

**Issue by nowherenoid** [cloudyr/aws.s3#145]
I need read a .csv file from my s3 bucket. I used cloudyr/aws.ec2metadata package to read in  my cluster metadata and feed in  the key, secret and token to  system variable. I used Sys.geten() to get them back. Everything is  all right. But when I read in csv  as df,  it only has one observation  :   
<Error><Code>AccessDenied</Code><Message>Access Denied</

Here is my code to read in csv file:
Sys.setenv("AWS_ACCESS_KEY_ID" = AccessKeyId,
           "AWS_SECRET_ACCESS_KEY" = SecretAccessKey,
            "AWS_SESSION_TOKEN" = Token)
bucket = mybucket

filename = myfile
obj <-get_object(paste0(bucket,filename),check_region = FALSE)
df = read.csv(text = rawToChar(obj))

This code worked before, but today when I spawn up my cluster I reinstalled everything, it gave me the error. But I  checked my access, everything seems fine.

**Comment by leeper** [comment]
I believe this has been fixed via #142. Can you reinstall and confirm?

**Comment by nowherenoid** [comment]
Fixed it. Thank you for your time.
