### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by HenrysFork** [cloudyr/aws.s3#146]
Hello, 

I am relatively new to R and AWS and just want to make sure that I correctly set up this API. 

1. Create bucket "foo" in AWS S3 account
2. Create bucket policy
3. Set environment to correct access and secret keys
4. install aws.s3 and include library(aws.s3) 
5. Call s3load(object = "fooObj", bucket="foo")

For some reason I continue to get strange errors including: could not find function "parse_url" in s3_HTTP.
parse_url is in httr which I have installed and included, so I am not sure why I continue getting this error.

Did I miss anything in the set up? Any ideas why I would be unable to find these functions. 

Thanks

**Comment by leeper** [comment]
That all seems right. You can also (1) and (2) directly in R if you want.

I'm not sure why you're seeing those errors. Can you provide the output of `sessionInfo()` for me?
