### ISSUE TITLE
Works with R version 3.2.3?

### ISSUE THREAD

**Issue by huang-pan** [cloudyr/aws.s3#147]
Hello,
  I'm using R version 3.2.3 and am getting this error:

library('aws.s3')
Sys.setenv("AWS_ACCESS_KEY_ID"="myID",
           "AWS_SECRET_ACCESS_KEY"="myKey",
           "AWS_DEFAULT_REGION"="us-west-1")
bucketlist()

Error in setup_s3_url(bucketname, region, path, accelerate, url_style = url_style,  : 
  could not find function "endsWith"

I installed aws.s3 v .3.3 and aws.signature .3.2

Does anyone know what the problem is?

thanks!!

Huang

**Comment by leeper** [comment]
The endsWith function is not available in that version of R. Can you update to a more recent version?

**Comment by huang-pan** [comment]
Hmm, I'll try - not sure I can mess with the setup for my group. Thanks!

**Comment by leeper** [comment]
Okay. If not, let me know and I will re-implement this using [backports](https://github.com/mllg/backports).

**Comment by huang-pan** [comment]
Actually, would it be possible to extend compatibility for aws.s3 to R version 3.2.3?

**Comment by leeper** [comment]
Will try to do so.

**Comment by huang-pan** [comment]
Thanks!!!

**Comment by leeper** [comment]
This should now work on R 3.2.3.

**Comment by huang-pan** [comment]
Thanks!!!

**Comment by tokenmathguy** [comment]
When is the next release to the CRAN planned? I see that the last time CRAN was updated was June 14.

**Comment by yotamyarden** [comment]
+1, can't connect to s3 via R 3.2.3

**Comment by leeper** [comment]
Sorry - all of my open source work has had to fall to the back burner lately. What's the problem with 3.2.3? Are you getting a specific error?

**Comment by yotamyarden** [comment]
Thanks for your swift reply. 
Yes I get the same error: "...could not find function "endsWith", I also found out that the latest R version is not supported on Ubuntu so I am considering to change the operation system.

**Comment by leeper** [comment]
Ah, okay, so only issue is it's not on CRAN with the fix? Will try to get to this in the coming week when I have a moment.

**Comment by yotamyarden** [comment]
I also tried now to remove the CRAN package and install it from source, restart the R server but I get the same error.
