### ISSUE TITLE
Getting an error while saving data into S3 Bucket 

### ISSUE THREAD

**Issue by sivasai5148** [cloudyr/aws.s3#149]
when i am trying to place data into s3 bucket with help of below codes it is throwing me error 

```
library("aws.s3")
Sys.setenv("AWS_ACCESS_KEY_ID" = "keykkk",
           "AWS_SECRET_ACCESS_KEY" = "Secret"
)

library("aws.s3")
zz <- rawConnection(raw(0), "r+")
write.csv(iris, zz)

put_object(file = rawConnectionValue(zz), object = "s3://bucket.name/application/folder/irisrc.csv",opts = list(verbose = TRUE))

```

			        **(or)**

```
library("aws.s3")
 Sys.setenv("AWS_ACCESS_KEY_ID" = "Keykkk",
            "AWS_SECRET_ACCESS_KEY" = "Secretttt"
 )
 
 s3save(iris, object = "s3://bucket.name/application/folder/irisrc.csv", opts = list(verbose = TRUE))
```
when i am trying to place data into s3 bucket with help of below codes it is throwing me  an error saying 

 **error: 'setup_s3_url(bucketname, region, path, accelerate, url_style = url_style,  : could not find function &quot;endsWith&quot;'.**
 
Please look into to code and help me out how can i over come this error 

Thanks in Advance

**Comment by leeper** [comment]
If you pull the latest version from GitHub, it should correct this error, which was recently fixed (https://github.com/cloudyr/aws.s3/issues/147).

**Comment by sivasai5148** [comment]
Thanks for the response, do i need to pull latest version of aws.s3 package (or) R version .Please let me know .
Thanks

**Comment by leeper** [comment]
@sivasai5148 Just `ghit::install_github("cloudyr/aws.s3")`. This should work on any version of R.

**Comment by sivasai5148** [comment]
right now i have AWS S3 with version 0.0.3 ,you want me to upgrade it to 0.3.7 ?

**Comment by leeper** [comment]
You cannot have 0.0.3, as that version has never existed. The current version on GitHub is 0.3.7, yes.

**Comment by sivasai5148** [comment]
sorry i had 0.3.3 and try to  upgrade it to 0.3.7 & and also i had aws.signature with version 0.2.6 & 0.3.5
