### ISSUE TITLE
GET requests for objects are sensitive to trailing /

### ISSUE THREAD

**Issue by almartin82** [cloudyr/aws.s3#15]
for instance, a GET request to `https://1000genomes.s3.amazonaws.com/README.pilot_data` will succeed, but `https://1000genomes.s3.amazonaws.com/README.pilot_data/` will throw a 404.

[right now](https://github.com/cloudyr/aws.s3/blob/4ee021f02ea9d74acab918c3608661a3ba57a52e/R/http.r#L50) we always build the url + '/' + bucket + path, which has the unintended effect of appending a trailing slash to the url, even if the correct url is passed to `s3HTTP`.

**Comment by leeper** [comment]
Right, this is because everything after the base URL [is interpreted by S3 as an object key](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html).
