### ISSUE TITLE
Loading files does not work.

### ISSUE THREAD

**Issue by ARBinit** [cloudyr/aws.s3#150]
I set my environment. I've replaced my actual bucket name with "mybucketname" for my example below. Also using test dataframe mtcars.

s3save(mtcars, bucket = "mybucketname", object = "mtcars.Rdata")

This saves into S3, I can see a file on S3 Amazon site.
when I use:
a <- s3load("mtcars.Rdata", bucket = "mybucketname")
It doesn't error but it just gives me a null for a.

I can see the files there with get_bucket function.

**Comment by leeper** [comment]
The return value is always NULL, just like for the regular `load()` function. Any objects in the file are loaded to the environment specified by `envir`, typically the global environment. Check for them using `ls()`.

**Comment by ARBinit** [comment]
How would I store mtcars as a new variable then? Is there another function I should be using?

**Comment by leeper** [comment]
What do you mean exactly? You can try `s3readRDS()` and `s3saveRDS()` to handle single objects. If you're working with Rdata files, you can also load into a `new.env()` and then manipulate the objects from there.
