### ISSUE TITLE
S3 Instance Profile has been ignored

### ISSUE THREAD

**Issue by kamoor** [cloudyr/aws.s3#152]
Looks like CloudyR package always looking for aws access key and secret but other methods provided in Amazom Credential Provider Chain has been ignored.  

Example:
Due to security reasons We do not use generate access keys and secret for any application installed in EC2, instead we create an IAM instance profile to have EC2 instance RW access to S3. CloudyR package is completely ignoring that profile and always looking for access keys and secret.  

Could you please address this issue. Thank you

**Comment by leeper** [comment]
Are you using the latest versions of all packages from CRAN? Instance metadata is used in all current package versions.

**Comment by kamoor** [comment]
@leeper Thanks for looking in to it. When I install from CRAN, version 0.3.3 is getting pulled which is updated in central repo on Jun 2017. 

https://cran.rstudio.com/src/contrib/aws.s3_0.3.3.tar.gz

Really appreciate your help

**Comment by leeper** [comment]
Can you provide more detail? Like the version of **aws.signature** that you're using. That's the package that actually handles credential finding. The function `aws.signature::locate_credentials()` should find the instance profile if there is one.

**Comment by kamoor** [comment]
To reproduce: create an EC2 instance (I use ubuntu) and assign a role having read/list access on any s3 bucket. I can use aws cli tools and do anything I want at this point. No access key/secret is being setup on EC2(i.e I have not done 'aws configure' at all and expecting to use Instance Profile).

Now I installed RStudio on the same EC2 instance and use aws.s3 to get list of file, See error below:

> library("aws.s3")
> get_bucket("my-bucket")
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr "05BAC15A27847D60"

At the same time, following code work just fine 

_list <- system("aws s3 ls s3://bucket-name/ ")
print(list)_
 

Signature version 4 is used here.

**Comment by leeper** [comment]
What does the function `aws.signature::locate_credentials()` return? And can you supply the output of `sessionInfo()` ?

**Comment by kamoor** [comment]
**> aws.signature::locate_credentials()**
$key
NULL

$secret
NULL

$session_token
NULL

$region
[1] "us-east-1"

**> sessionInfo()**

R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2017.03

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] aws.s3_0.3.3

loaded via a namespace (and not attached):
[1] httr_1.2.1          R6_2.2.2           
[3] tools_3.3.3         base64enc_0.1-3    
[5] Rcpp_0.12.11        aws.signature_0.3.5
[7] xml2_1.1.1          digest_0.6.12

**Comment by leeper** [comment]
Please install the development version of aws.signature from Github. You also need to install aws.ec2metadata (also get this from Github). Without the latter, aws.signature can't tell if you're running on EC2.

**Comment by gliptak** [comment]
I ran into this issue too. ```aws.signature::locate_credentials()``` shows credentials.

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2017.09

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] aws.signature_0.3.5   aws.ec2metadata_0.1.2 aws.s3_0.3.3

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.1  R6_2.2.2        tools_3.4.1
 [5] base64enc_0.1-3 curl_3.1        Rcpp_0.12.15    xml2_1.2.0
 [9] git2r_0.21.0    jsonlite_1.5    digest_0.6.15   ghit_0.2.18
```
The development version install of ```aws.signature``` failed with https://github.com/cloudyr/ghit/issues/29

**Comment by goforgold** [comment]
> Please install the development version of aws.signature from Github. You also need to install aws.ec2metadata (also get this from Github). Without the latter, aws.signature can't tell if you're running on EC2.

Thanks @leeper !

This worked for me. I installed package `aws.ec2metadata` using `package.install`. `aws.signature` was already there which I didn't touch.

It worked like charm.
