### ISSUE TITLE
Error will saving file(csv,xslx,tsv) from local to AWS S3

### ISSUE THREAD

**Issue by sivasai5148** [cloudyr/aws.s3#157]
Hello,

I am unable to upload local file from R studio to AWS S3 using the below code. 
Below are the details for the Code and error message I am receiving in R studio.
I also tried other function and tricks but no luck so far.
Please advise.

Thank You.

Note : Default region is “us-east-1”.

Code used in Rstudio/Spotfire:

```R
> library("aws.s3")
> Sys.setenv("AWS_ACCESS_KEY_ID" = 'KEY',
>            "AWS_SECRET_ACCESS_KEY" = 'SECRET')
> 
> data <- read.csv(file="C:/Users/Test/Desktop/Temp.csv",header=TRUE,sep=",")
> s3save(data,object = "s3://Bucketname/somefolder/sample.csv",opts = list(verbose =TRUE))
Checking bucket region using get_location(' Bucketname’)
Executing request using bucket region us-east-1
S3 Request URL: https://s3.amazonaws.com/ s3://Bucketname/somefolder/sample.csv
Executing request with AWS credentials
Parsing AWS API response
Client error: (403) Forbidden
List of 4
$ Code     : chr "AccessDenied"
$ Message  : chr "Access Denied"
$ RequestId: chr "4685C25F0E5C7A6F"
$ HostId   : chr "X89EGRZlikBM4Cnp/4EiAuWabz+83MJ1ixL5mjwu567DhexNDbUyr8="
- attr(*, "headers")=List of 7
  ..$ x-amz-request-id : chr "4685C25F0E5C7A6F"
  ..$ x-amz-id-2       : chr "X89EGRZlikBM4Cnp/4EiZ8Wabz+8353pJ1ixL5mDhexNDbUyr8="
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Sat, 12 Aug 2017 04:06:08 GMT"
  ..$ connection       : chr "close"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
- attr(*, "class")= chr "aws_error"
- attr(*, "request_canonical")= chr "PUT\n/ Bucketname/somefolder/sample.csv\n\ncontent-length:151\nhost:s3.amazonaws.com\nx-amz-acl:private"| __truncated__
- attr(*, "request_string_to_sign")= chr "AWS4-HMAC-SHA256\n20170T040608Z\n2017812/us-east-1/s3/aws4_request\n5e51f4c7d87dcce70db62e0f5"| __truncated__
- attr(*, "request_signature")= chr "AWS4-HMAC-SHA256 Credential=AKIAICXK7FV7Q/20170812/us-east-1/s3/aws4_request, SignedHeaders=content-leng"| __truncated__
NULL
**Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).**
```

**Comment by leeper** [comment]
Looks like you probably don't have access to the bucket?

Also, `s3save()` like `save()` but for S3. If you want to write a CSV, using `s3write_using()` or `put_object()`.

**Comment by sivasai5148** [comment]
But i am able to get data from the same S3 bucket using get_object().

**Comment by leeper** [comment]
Is this line verbatim from the output or have you edited it?

```
S3 Request URL: https://s3.amazonaws.com/ s3://Bucketname/somefolder/sample.csv
```

Also, can you supply the output of `sessionInfo()`?

**Comment by sivasai5148** [comment]
I replaced the actual names of S3 bucket and Folder name in that URL 

Here is the Session Info Output 
> sessionInfo()
TIBCO Enterprise Runtime for R version 4.3.0 (2017-02-03)
Platform: x86_64-pc-windows

locale:
[1] "LC_CTYPE=en_US"          "LC_NUMERIC=C"
[3] "LC_TIME=en_US"           "LC_COLLATE=en_US"
[5] "LC_MONETARY=en_US"       "LC_MESSAGES=en_US"
[7] "LC_PAPER=en_US"          "LC_NAME=en_US"
[9] "LC_ADDRESS=en_US"        "LC_TELEPHONE=en_US"
[11] "LC_MEASUREMENT=en_US"    "LC_IDENTIFICATION=en_US"


attached base packages:
[1] "stats"     "graphics"  "grDevices" "utils"     "methods"   "base"


loaded via a namespace (and not attached):
[1] "terrUtils_4.3.0-52"

please let me know if you need any additional information
Thanks

**Comment by leeper** [comment]
I need `sessionInfo()` with the aws.s3 package loaded so I can see versions of all dependencies.

**Comment by sivasai5148** [comment]
Please find the Session Information below 
>sessionInfo(package="aws.s3")
TIBCO Enterprise Runtime for R version 4.3.0 (2017-02-03)
Platform: x86_64-pc-windows

locale:
 [1] "LC_CTYPE=en_US"          "LC_NUMERIC=C"
 [3] "LC_TIME=en_US"           "LC_COLLATE=en_US"
 [5] "LC_MONETARY=en_US"       "LC_MESSAGES=en_US"
 [7] "LC_PAPER=en_US"          "LC_NAME=en_US"
 [9] "LC_ADDRESS=en_US"        "LC_TELEPHONE=en_US"
[11] "LC_MEASUREMENT=en_US"    "LC_IDENTIFICATION=en_US"


other attached packages:
[1] "aws.s3_0.3.3"

loaded via a namespace (and not attached):
[1] "base_4.3.0-52"      "grDevices_4.3.0-52" "graphics_4.3.0-52"
[4] "methods_4.3.0-52"   "stats_4.3.0-52"     "terrUtils_4.3.0-52"
[7] "utils_4.3.0-52"

**Comment by leeper** [comment]
I'm guessing this was a region-related issue. If you're still encountering it with the latest version from Github, let me know.
