### ISSUE TITLE
Default changes to overwrite argument

### ISSUE THREAD

**Issue by HugoHehn** [cloudyr/aws.s3#159]
Hi,

Not sure if this is really an issue - rather wanted to get it clarified. 

Saw that functions such as save_object now defaults to overwrite = FALSE. Think this is linked to the switch to httr::write_disk() in the latest commit, but with a cursory glance at the code it looked like the defaults might have been meant to continue being overwrite = TRUE?

Before I start rewriting all of my scripts to enable overwrite I just wanted to check so that this is not a bug that will be corrected in some later release?

Best,
H

**Comment by leeper** [comment]
Oops, that was a mistake. Pushing an update to restore previous default behavior (`overwrite = TRUE`).

**Comment by HugoHehn** [comment]
Thanks a lot! This package is a lifesaver.
