### ISSUE TITLE
How to check if an object exists in s3 bucket

### ISSUE THREAD

**Issue by aiyerganapathy** [cloudyr/aws.s3#160]
Hey, So I wanted to check if an object exists in a s3 bucket. Currently, I wrote a udf which does that, but its not that good. Is there a helper function in this library which can help me achieve this functionality.

**Comment by leeper** [comment]
The function to do this isn't exactly obviously named, but it's `head_object()` (as in a HTTP HEAD request). It returns TRUE if an object exists and FALSE otherwise:

```R
aws.s3::head_object("s3://bucketname/objectkey")
```

That will also return HTTP headers for the object (such as its size and content type), as attributes.

**Comment by aiyerganapathy** [comment]
Thank you for the reply :)
