### ISSUE TITLE
Access to Requester Pays Buckets

### ISSUE THREAD

**Issue by bonartm** [cloudyr/aws.s3#162]
How can I access requester pays buckets (see http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html)?

I tried the following (for the imdb-datasets):

`get_bucket(bucket = "imdb-datasets", headers = list('x-amz-request-payer' = "requester"))` 

but this results in an HTTP 403 answer. 

(using R version 3.4.1, and aws.s3 version 0.3.3)

**Comment by leeper** [comment]
I could be wrong, but I don't think you need that header to list objects, only to download them.

**Comment by edzer** [comment]
I'm also interested in getting access to requester pays buckets. Where this
```
aws s3 ls s3://sentinel-s2-l1c/tiles/58/H/FB/2016/3/6/0/B08.jp2 --request-payer
```
for instance works, these
```
get_bucket(bucket = "sentinel-s2-l1c")
get_bucket(bucket = "sentinel-s2-l1c", headers = list('x-amz-request-payer' = "requester"))
```
(and variations in bucket name) give an AccessDenied 403. 

Are there examples of successful access with requester pays?

**Comment by hrodmn** [comment]
@edzer are you able to access the sentinel-s2-l1c bucket using aws.s3? I am getting a "Permanent Redirect" error when I try to use `get_bucket_df`.

```
aws.s3::get_bucket_df(
  prefix = "tiles/15/T/XL/2019/6/6/0/",
  bucket = "sentinel-s2-l1c", 
  headers = list('x-amz-request-payer' = "requester")
)
```

**Comment by s-u** [comment]
If you get re-direct, you're using the wrong region. AWS always requires you to use the correct region since only the servers in the region know about that bucket.

(If you're daring, you can try the https://github.com/cloudyr/aws.s3/tree/unify-response branch which automatically follows re-directs when the user uses the wrong region).

**Comment by hrodmn** [comment]
@s-u thanks. After I set `Sys.setenv("AWS_DEFAULT_REGION" = "eu-central-1") `get_bucket` worked fine. Is there a logical place to add a more informative error message for the case where the incorrect region is specified?

**Comment by s-u** [comment]
No, as I said, the new version automatically detects this, but in the old version you don't even get an error sometime.

**Comment by natedailey7** [comment]
> I'm also interested in getting access to requester pays buckets. Where this
> 
> ```
> aws s3 ls s3://sentinel-s2-l1c/tiles/58/H/FB/2016/3/6/0/B08.jp2 --request-payer
> ```
> 
> for instance works, these
> 
> ```
> get_bucket(bucket = "sentinel-s2-l1c")
> get_bucket(bucket = "sentinel-s2-l1c", headers = list('x-amz-request-payer' = "requester"))
> ```
> 
> (and variations in bucket name) give an AccessDenied 403.
> 
> Are there examples of successful access with requester pays?

Ditto to this. Does there exist an example of successfully using `aws.s3` to access a requester pays bucket?
