### ISSUE TITLE
Problem with s3source()

### ISSUE THREAD

**Issue by gregflood918** [cloudyr/aws.s3#163]
s3source() is unable to find the temp R file whenever I run it.  

The issue seems to be related to the temp R file.  I receive the error message "no such file or directory" when I run the function, but if I run the following  lines of code directly, it works.

    tmp <- tempfile(fileext = ".R")
    on.exit(unlink(tmp))
    writeBin(object = r, con = tmp)
    source(tmp, ...)

It looks like on.exit is deleting the temporary file before it is sourced

**Comment by leeper** [comment]
Looks like a bug. Thanks for reporting.

**Comment by leeper** [comment]
Closed by: https://github.com/cloudyr/aws.s3/commit/fa911fb6f45b9c98a8db2d8c3aa12c925e136af8
