### ISSUE TITLE
get_bucket() Error

### ISSUE THREAD

**Issue by washcycle** [cloudyr/aws.s3#164]
I've been getting an error when trying to use get_bucket()

    Error in x$Owner$DisplayName : $ operator is invalid for atomic vectors

Not sure how to debug this one as this is a work associated S3 bucket. Never had this problem on my personal S3 bucket so far. 

They are on different regions...

**Comment by washcycle** [comment]
I narrowed down the culprit.

   cat("Owner:         ", x$Owner$DisplayName, "\n") in util.R

my x$Owner doesn't have another list object here it is just a random string  that looks like this,"xxxxxxxxxxxxxxxxacd8a1484xxxxxxxxx4dcf317f4d43xxxxxxxxxxxxxxxxxxxx", obfuscated for security reasons.

**Comment by washcycle** [comment]
I got a fix that I will submit a pull request from...

**Comment by leeper** [comment]
Closed by https://github.com/cloudyr/aws.s3/pull/165

**Comment by EconomiCurtis** [comment]
I had this issue today, with the resolution upgrading aws.s3 (which in turn required updating aws.signature) with `devtools::install_github("cloudyr/aws.s3")`

@leeper  Could I encourage you to update the [`aws.s3`](https://cran.r-project.org/web/packages/aws.s3/index.html) and [`aws.signature`](https://cran.r-project.org/web/packages/aws.signature/index.html) on CRAN? 

These haven't been updated in over 8 months.

**Comment by leeper** [comment]
@EconomiCurtis I'm sure you mean well with that comment, but please know that all development work on these packages is done by one person (me) and this is completely unpaid labor that I get to when I can. I'm in the process of getting an update of aws.signature on CRAN and an update to aws.s3 will come when that has cascaded through CRAN's full process (usually takes a few days).

**Comment by washcycle** [comment]
@EconomicCurtis if you already have that fix consider making a new issue
and making a new pull request. That will help Tom out when he gets to it😄
