### ISSUE TITLE
Reading larger files from S3

### ISSUE THREAD

**Issue by daswesen** [cloudyr/aws.s3#170]
This probably is not a bug but expected behavior but I was wondering how to read larger files from S3? This is the error message I get for a 3 GB file:

`> csvcharobj <- rawToChar(obj)  

Error in rawToChar(obj) : long vectors not supported yet: raw.c:68`

**Comment by leeper** [comment]
What code did you use to call that? and can you give me the full output of `sessionInfo()`?

**Comment by leeper** [comment]
You don't need to convert to character to do this. You could just pass the response from `get_object()` to `rawConnection()`. Alternatively, use `save_object()` to save it locally and then use an efficient importing function like `readr::read_csv()` or `data.table::fread()`.

**Comment by daswesen** [comment]
Thanks. I want to keep the data in RAM rather than creating a local copy on disk. I am struggling to work with rawConnection after reading the help several times, unfortunately, and I apologize for asking you for your help here. 

This command:
obj <-get_object("s3://myBucketName/aFolder/fileName.csv")
con <- rawConnection(obj, "r") 
data2 <- read.table(con, sep=",", header=TRUE)

has this result:
Error in pushBack(c(lines, lines), file, encoding = pbEncoding) : can only push back on text-mode connections

I managed to create a large character by using

data <- readLines(con)

but I haven't managed to get this into a dataframe without R capitulating; in fact, it is even faster to download the file from S3 manually and upload it to R. I guess that's not the way it should be :-)

I will be looking at how to use Apache Spark for this in the future but I was thinking that I should be able to do this without on a machine with lots of RAM, given that the file is not too big.

Your help would be much appreciated!

**Comment by leeper** [comment]
That code looks like it should work. Perhaps try:

```R
obj <- get_object("s3://myBucketName/aFolder/fileName.csv")
data2 <- read.csv(rawConnection(obj))
```

Another option, that might be easier is the `s3read_using()` function:

```R
s3read_using(FUN = read.csv, object = "s3://myBucketName/aFolder/fileName.csv")
```

**Comment by daswesen** [comment]
> data2 <- read.csv(rawConnection(obj))
Error in pushBack(c(lines, lines), file, encoding = pbEncoding) :    can only push back on text-mode connections 

> s3read_using(FUN = read.csv, object = "s3://myBucketName/aFolder/fileName.csv") 
Error in writeBin(httr::content(r, as = "raw"), con = file) :    long vectors not supported yet: connections.c:4123 In addition: Warning message: In inherits(x, "factor") : closing unused connection 3 (obj)

It works great with smaller files but not with files of that size, unfortunately :-/ I'll check whether I can solve this by reading it directly into a Spark cluster. Thanks for your help though!

**Comment by leeper** [comment]
Seems it might be too large to work with R's in-memory connections infrastructure. Sorry.

**Comment by amarchin** [comment]
I get a similar issue when I try to write a data frame to S3:

> Error in writeBin(httr::content(r, as = "raw"), con = file) : 
>   long vectors not supported yet: ../../../../R-3.4.3/src/main/connections.c:4147
> Called from: writeBin(httr::content(r, as = "raw"), con = file)

**Comment by leeper** [comment]
I think the consensus from the httr side of things is to write to disk. There probably isn't a way around it without low-level changes to R. See https://github.com/r-lib/httr/issues/44

**Comment by Christian-Onyango** [comment]
@daswesen did you ever figure it out?
