### ISSUE TITLE
reading mulipart files from s3 using get_object?

### ISSUE THREAD

**Issue by mjpdenver** [cloudyr/aws.s3#174]
Hi,

( A question more than an issue)

I have a dataset in mulitpart format in an s3 bucket.  

0000_part_00.gz
0001_part_00.gz
0002_part_00.gz
....

Typically - I cat the parts together and then read them.  

Is it possible to use get_object to directly read the into R?

Thanks

**Comment by leeper** [comment]
You should be able to just `c()` together the raw vector that comes back from `get_object()`.
