### ISSUE TITLE
s3readRDS cannot work in parallel via mclapply

### ISSUE THREAD

**Issue by tsingdy** [cloudyr/aws.s3#177]
the following sequential code works fine
> objects = c('A', 'B')
> bucket = 'mybucket'
> lapply(objects, function(x) s3readRDS(object = x, bucket = bucket))

but the following parallel code fails with error message "<simpleError in curl::curl_fetch_memory(url, handle = handle): SSL connect error>"
> mclapply(objects, function(x) s3readRDS(object = x, bucket = bucket))

Thanks~

**Comment by leeper** [comment]
I think I need more info to do anything about this, like a `traceback()` after the error occurs.

**Comment by leeper** [comment]
I'm closing as there's not enough information to investigate.

**Comment by davidhaan** [comment]
I get the same error, what do you need to address this issue? The issue for me is that sometimes it works and other times I get this error.  It seems completely random...
