### ISSUE TITLE
"AccessDenied" deleting objects from S3

### ISSUE THREAD

**Issue by dschmeh** [cloudyr/aws.s3#178]
If I want to delete an object from S3 I get the error message  "AccessDenied" from AWS. Downloading the File works fine. Using the same Credentiels with Python it is possible to remove the object.

I tried the following things:
`delete_object("s3://BUCKET/File/file.csv", key = aws_key, secret = aws_secret, session_token =NULL)`
`delete_object("/File/file.csv", "BUCKET", key = aws_key, secret = aws_secret, session_token =NULL)`

Any ideas what the problem could be?
Thanks

**Comment by dschmeh** [comment]
Now have the following solution to the problem:
The following code allows me to delete the objects from the bucket:

```
s3HTTP(verb = "DELETE", 
       bucket = "BUCKETNAME",
       path = "/FOLDER/FILE.csv", parse_response = FALSE,key = aws_key, secret = aws_secret)
```

**Comment by leeper** [comment]
Did you try `delete_object()` with `verbose = TRUE`? That will give you (and me) more information on where the problem lies.

**Comment by dschmeh** [comment]
Using `delete_object()` with `verbose = TRUE` I get the following response from AWS:

`List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr "XXXXXXXXXXXXXX"
 $ HostId   : chr "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
 - attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr "XXXXXXXXXXXXXX"
  ..$ x-amz-id-2       : chr "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Wed, 17 Jan 2018 08:18:48 GMT"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).`

With the Following Code it works:

`s3HTTP(verb = "DELETE", 
       bucket = "BUCKETNAME",
       path = "/FOLDER/FILE.csv", parse_response = FALSE,key = aws_key, secret = aws_secret)`

**Comment by rkunduri** [comment]
delete_object(object = "file.csv", bucket = "BUCKET//File", key = aws_key, secret = aws_secret, session_token =NULL) Try this

**Comment by leeper** [comment]
Have you tried using `get_bucket_policy()` to see what permissions you have on the bucket?

**Comment by leeper** [comment]
I'm going to assume this is due to the old default of `check_region = TRUE`, which has now been changed to `FALSE`. If you're still encountering problems, let me know.

**Comment by JamiroFerrara** [comment]
THANK YOU @ACB-prgm,
