### ISSUE TITLE
Strategy for creating XML request bodies

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.s3#18]
Most of the PUT methods that allow one to configure a bucket or object require XML structures. In a couple of cases I've just used simple string concatenation to build these, but the structures can get quite complicated. How do we want to approach this? Should we:
1. use the XML package to build actual XML objects, 
2. stick with string concatenation, or 
3. force the user to write their own XML?

**Comment by almartin82** [comment]
Maybe we could do a census of what is happening on github with `boto` -- my guess is that most users of the aws.s3 are going to be here for the basic get/put object functions, and that anyone showing up to modify CORS or ACL settings is presumably a skilled devops person.  If that's true, then it leads me to two conclusions:
1) prioritize simplicity `putobject` and `getobject` -- [tinys3](https://www.smore.com/labs/tinys3/) is a good example of a library that makes aws friendly to a new user.
2) prioritize correctness for the XML structures.

I used the [AWS Policy Generator](http://awspolicygen.s3.amazonaws.com/policygen.html) to try to get a sense of what these would look like:
```
{
  "Id": "Policy1437920165253",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1437919794935",
      "Action": [
        "s3:PutBucketLogging"
      ],
      "Effect": "Deny",
      "Resource": "arn:aws:s3:::hpk",
      "Principal": {
        "AWS": [
          "almartin82bk"
        ]
      }
    }
  ]
}
``` 
that's not going to be fun to do with string concatenation, and honestly, I'm guessing the workflow for most people is not to write the XML from scratch, but to use the policy generator to build a few examples, and then modify fields programmatically.  So I guess that means I think 2 (string concatenation) is a dead end, 1 (build XML objects) would result in duplicating the policy generator, and 3 is the best bet (with a nice vignette about how to use the policy generator to build an anchor object, then modify that object in R using the XML package).

**Comment by leeper** [comment]
I definitely agree that we do not want to replicate the policy generator, so I like the idea of a vignette showing how to use that. There are some other instances, though, where a request body is a complex XML structure that has to be generated somewhere: [Bucket tagging](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTtagging.html) is one, and [notifications](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html) is another.

**Comment by cboettig** [comment]
All great ideas here.  Definitely agree that it makes no sense to generate XML with string manipulations when there's already a nice library to do it.  Also agree that the most important functionality will be just to let users provide their own policies via external XML files (whether built via the policy generator or something else).

In addition to providing that option, it's possible we'd want to include some light-weight default policies, or a tool that could tweak a given policy through some common use cases (if that makes sense, not familiar enough with common use cases).

In general, following whatever the super established wrappers or sdks of other languages have done, like boto, seems like a brilliant idea.

**Comment by leeper** [comment]
We can already pass ["Canned ACLs"](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl) during `putbucket` so we probably don't need to set defaults. Those will probably cover a huge number of use cases.

But maybe we can add some examples to `inst` of the more complex structures and use those in a vignette. So, TODO:

- [ ] A few template policies in `inst`
- [ ] Vignette showing ACLs/CORs, using those templates
- [ ] Vignette showing notifications (?)

**Comment by leeper** [comment]
Closing for now.
