### ISSUE TITLE
Documentation: save_object() requires check_region = FALSE for restricted-permission buckets

### ISSUE THREAD

**Issue by tvoipio** [cloudyr/aws.s3#185]
I encountered an issue very similar to #175 and #122 while trying to `save_object()` from an S3 bucket with positive permission list. Setting `check_region = FALSE` circumvented the problem after the reason for the HTTP 403 error was determined using `verbose = TRUE`.

According to the S3 API documentation page to which the documentation of get_location() refers, http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html , GET location is only available to the bucket owner.

Since non-owner accessing objects in a bucket is (IMHO) not a rare edge case, I would like to request that either `check_region` defaults to FALSE or at least that the Details section of in the documentation of `*_object` warns about this behavior and suggests setting verbose = TRUE and/or check_region = FALSE in case a HTTP 403 error is encountered.

CRAN version 0.3.3, R 3.4.0 on darwin15.6.0 x86_64

**Comment by leeper** [comment]
Default (on GitHub) is now `check_region = FALSE`.
