### ISSUE TITLE
Problem reading json files

### ISSUE THREAD

**Issue by martinolmos** [cloudyr/aws.s3#186]
Hi,
I have a problem trying to read some tweets from an S3 bucket. I'm getting the following error:
```
Error: parse error: trailing garbage
          imestamp_ms":"1514406005809"}, {"created_at":"Wed Dec 27 20:
                     (right here) ------^
```
Here is my code:
```
obj <- get_object("s3://my_bucket/myfile") 
charobj <- rawToChar(obj)
myobj <- fromJSON(charobj)
```
And my `sessionInfo()`  :

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
```
Any ideas?
Thanks,

**Comment by leeper** [comment]
Are you sure the JSON is well-formatted? Sounds like it might be an issue with the file or with **jsonlite** rather than **aws.s3**.

**Comment by martinolmos** [comment]
You were right, it was an issue with the json format. Solved.
Thanks,
