### ISSUE TITLE
minio compatibility

### ISSUE THREAD

**Issue by kaneplusplus** [cloudyr/aws.s3#191]
minio claims compatibility with s3. However, it looks like there is an issue with minio and `aws.s3`.

Below is an example of trying to access the "play" server.

Is this a known issue?

```{r}
> Sys.setenv("AWS_ACCESS_KEY_ID" = "Q3AM3UQ867SPQQA43P2F", "AWS_SECRET_ACCESS_KEY" = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
> bucketlist(base_url="play.minio.io:9000")
List of 7
 $ Code      : chr "SignatureDoesNotMatch"
 $ Message   : chr "The request signature we calculated does not match the signature you provided. Check your key and signing method."
 $ Key       : list()
 $ BucketName: list()
 $ Resource  : chr "/"
 $ RequestId : chr "3L137"
 $ HostId    : chr "3L137"
 - attr(*, "headers")=List of 7
  ..$ accept-ranges    : chr "bytes"
  ..$ content-type     : chr "application/xml"
  ..$ server           : chr "Minio/DEVELOPMENT.2018-01-05T16-29-57Z (linux; amd64)"
  ..$ vary             : chr "Origin"
  ..$ x-amz-request-id : chr "15092F3B65031611"
  ..$ date             : chr "Fri, 12 Jan 2018 22:04:41 GMT"
  ..$ transfer-encoding: chr "chunked"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
 - attr(*, "request_canonical")= chr "GET\n/\n\nhost:play.minio.io\nx-amz-date:20180112T220437Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb9242"| __truncated__
 - attr(*, "request_string_to_sign")= chr "AWS4-HMAC-SHA256\n20180112T220437Z\n20180112/us-east-1/s3/aws4_request\nde34c63843b7e32420895767b98867294b36c51"| __truncated__
 - attr(*, "request_signature")= chr "AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20180112/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-d"| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) :
  Forbidden (HTTP 403).
```

**Comment by kaneplusplus** [comment]
The problem was that signature includes the host, but the host is not included in the header.

I've fixed this and I've also made the `base_url` a private variable in the package.

I'll probably have time to test this tomorrow. Barring any problems with the test, I'll send a pull request shortly after.

**Comment by kaneplusplus** [comment]
The pull request #194 has been submitted.

**Comment by leeper** [comment]
Thanks again for this. I think the simplest solution - and the one used by other S3 client libraries - is to use an environment variable (`AWS_S3_ENDPOINT`). I've implemented that here: https://github.com/cloudyr/aws.s3/commit/eade43c4abc6662bf4f0eee1d1af92da0323767c Let me know if you run into trouble with this development version.

**Comment by kaneplusplus** [comment]
Sure, I'll give it a try. Thanks.

**Comment by ningjingzhiyuan507** [comment]
Help! I have the same problem, but I got a different error；

**Comment by ningjingzhiyuan507** [comment]
Thanks!

**Comment by kaneplusplus** [comment]
Can you try my fork at https://github.com/kaneplusplus/aws.s3 and tell us if it works?

**Comment by leeper** [comment]
@ningjingzhiyuan507 Please supply the output of `sessionInfo()` so we can know more about your environment and package versions.

**Comment by ningjingzhiyuan507** [comment]
It got the same error:
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Bad Request (HTTP 400).

Details are as follows:
Checking for credentials in user-supplied values
Checking for credentials in Environment Variables
Using Environment Variable 'AWS_ACCESS_KEY_ID' for AWS Access Key ID
Using Environment Variable 'AWS_SECRET_ACCESS_KEY' for AWS Secret Access Key
Using default value for AWS Region ('us-east-1')
S3 Request URL: http://172.15.0.3:8080/
Executing request with AWS credentials
-> GET / HTTP/1.1
-> host: 172.15.0.3:8080
-> User-Agent: libcurl/7.54.0 r-curl/2.8.1 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> x-amz-date: 20180511T031649Z
-> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
-> Authorization: AWS4-HMAC-SHA256 Credential=O5RWP08F486A6B6JST6/20180511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=c571e148f81573e761c079ccd5964e127e2800ea2f24f07c6169453098d4fdec
-> 
<- HTTP/1.1 400 Bad Request
<- Date: Fri, 11 May 2018 03:16:49 GMT
<- Server: Apache
<- x-amz-request-id: tx00000000000000080444d-005af50b21-31d51-default
<- Accept-Ranges: bytes
<- Content-Length: 81
<- Connection: close
<- Content-Type: application/xml
<- 
Parsing AWS API response
Client error: (400) Bad Request
Class 'aws_error'  atomic [1:1] InvalidArgument
  ..- attr(*, "headers")=List of 7
  .. ..$ date            : chr "Fri, 11 May 2018 03:16:49 GMT"
  .. ..$ server          : chr "Apache"
  .. ..$ x-amz-request-id: chr "tx00000000000000080444d-005af50b21-31d51-default"
  .. ..$ accept-ranges   : chr "bytes"
  .. ..$ content-length  : chr "81"
  .. ..$ connection      : chr "close"
  .. ..$ content-type    : chr "application/xml"
  .. ..- attr(*, "class")= chr [1:2] "insensitive" "list"
  ..- attr(*, "request_canonical")= chr "GET\n/\n\nhost:172.16.0.3:8080\nx-amz-date:20180511T031649Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92"| __truncated__
  ..- attr(*, "request_string_to_sign")= chr "AWS4-HMAC-SHA256\n20180511T031649Z\n20180511/us-east-1/s3/aws4_request\n26e6be3e498f63d40e50574585ab450511f377c"| __truncated__
  ..- attr(*, "request_signature")= chr "AWS4-HMAC-SHA256 Credential=O5RWP08FD486A6B6JST6/20180511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-d"| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Bad Request (HTTP 400).
@kaneplusplus

**Comment by ningjingzhiyuan507** [comment]
@leeper sessionInfo() information as follows:
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.3.8    devtools_1.13.3

loaded via a namespace (and not attached):
 [1] httr_1.3.1          compiler_3.4.1      R6_2.2.2            tools_3.4.1         withr_2.0.0        
 [6] base64enc_0.1-3     curl_2.8.1          memoise_1.1.0       Rcpp_0.12.16        aws.signature_0.4.1
[11] xml2_1.2.0          git2r_0.19.0        digest_0.6.15

**Comment by riazarbi** [comment]
### Short Message:

Just to add to this. Using a clean install of aws.s3 via github/master, bucketlist fails to resolve host. 

I can access minio with the browser with identical URL, so I know that's not the issue. 

Error log looks like `curl:curl_fetch_memory` is using an incorrect url string - it prepends the region to the url and does not append the port.

Any suggestions?

### Details: 

I'm coming in with a clean install of aws.s3, via the github method: 

```
if (!require("remotes")) {
  install.packages("remotes")
}
remotes::install_github("cloudyr/aws.s3")
```

I'm setting the env as follows - 

```
Sys.setenv(AWS_ACCESS_KEY_ID = "K07YD615900UU0IJP6FI",
           AWS_SECRET_ACCESS_KEY = "4I4uT2Qblahblahblah",
           AWS_S3_ENDPOINT = "172.29.100.54:8001")
```

When I exectute either 

```
bucketlist(verbose=T,
                              base_url = "172.29.100.54:8001", 
                              use_https = FALSE)
```

or 

```
bucketlist()
```

I get the same error - 

```
Locating credentials
Checking for credentials in user-supplied values
Checking for credentials in Environment Variables
Using Environment Variable 'AWS_ACCESS_KEY_ID' for AWS Access Key ID
Using Environment Variable 'AWS_SECRET_ACCESS_KEY' for AWS Secret Access Key
Using default value for AWS Region ('us-east-1')
Non-AWS base URL requested.
S3 Request URL: http://us-east-1.172.29.100.54:8001/
Executing request with AWS credentials
Locating credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: us-east-1.172.29.100.54
```

**Comment by riazarbi** [comment]
@kaneplusplus @leeper 

I've tried both the Cloudyr version and the Kaneplusplus version. Kaneplusplus works, cloudyr does not.

@leeper could you please eyeball the code chunks and let me know if I'm doing anything wrong?

## Kaneplusplus version

```
devtools::install_github("kaneplusplus/aws.s3")

# code
Sys.setenv(AWS_ACCESS_KEY_ID = "K07YD615900UU0IJP6FI",
           AWS_SECRET_ACCESS_KEY = "4I4uT2QliwBz/KdtTNxzCKdGmeepmeep",
           AWS_S3_ENDPOINT = "172.29.100.54:8001",
           AWS_S3_REGION = "us-east-1")

aws.s3::bucketlist(verbose=T, 
           base_url = Sys.getenv("AWS_S3_ENDPOINT"), 
           use_https = FALSE)
```

## Cloudyr version

```

devtools::install_github("cloudyr/aws.s3")

# code
Sys.setenv(AWS_ACCESS_KEY_ID = "K07YD615900UU0IJP6FI",
           AWS_SECRET_ACCESS_KEY = "4I4uT2QliwBz/KdtTNxzCKdGpxyxQp/kmeepmeep",
           AWS_S3_ENDPOINT = "172.29.100.54:8001",
           AWS_S3_REGION = "us-east-1")

aws.s3::bucketlist(verbose=T, 
           base_url = Sys.getenv("AWS_S3_ENDPOINT"), 
           use_https = FALSE)

```

## Error with cloudyr

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: us-east-1.172.29.100.54
```

**Comment by ekianjo** [comment]
Hi, I am also a Minio user and I am experiencing the same kind of issues with cloudyr. I managed to get save_object working was cloudyr's version, however delete_object, with the exact same parameters, fails and throws a "could not resolve host" error. 

I would really like to know if it's possible to make it work as is.

**Comment by riazarbi** [comment]
FWIW we ended up wrapping the minio python client into reticulate and it
has been working well.

**Comment by kaneplusplus** [comment]
The original problem was the signature includes the host, but the host is not included in the header. I'm not sure why this works on S3 - it shouldn't. A fix was included in the request but it was not accepted and the solution was to pollute the the user environment with a new variable, rather than polluting package namespace of the R session. 

AWS keeps track of a number of parameters through environment variables but AFAIK AWS_S3_ENDPOINT is not one of them. I think this is an aws.s3 package issue and I'm not convinced an environment variable was the best solution.
