### ISSUE TITLE
get_bucket_df() fails

### ISSUE THREAD

**Issue by ThierryO** [cloudyr/aws.s3#192]
I get the following error when running `get_bucket_df()`. It turns out that the bucket doesn't return the `Owner` list. I'll send a PR with a fix.
```
 Error in names(out) <- c("Key", "LastModified", "ETag", "Size", "Owner_ID",  : 
  'names' attribute [8] must be the same length as the vector [6] 
```

**Comment by tomekziel** [comment]
Related bug: https://github.com/cloudyr/aws.s3/issues/287
