### ISSUE TITLE
The code error for S3Client file in phpStorm

### ISSUE THREAD

**Issue by czhifa** [cloudyr/aws.s3#196]
Kindly check the screen shot for details.
<img width="993" alt="screen shot 2018-01-22 at 3 17 02 pm" src="https://user-images.githubusercontent.com/8645153/35209254-ca6eea3e-ff87-11e7-9e95-a28a46d9d825.png">

**Comment by leeper** [comment]
You're asking in the wrong place. This is repo for an R client for AWS.
