### ISSUE TITLE
Allow reading an object through R connection

### ISSUE THREAD

**Issue by yasushi-saito** [cloudyr/aws.s3#197]
We have a package that reads data through a connection and we are looking for a way to feed S3 files to it. Do you have a plan to add such a support? If that's too complicated, at least we want a way to read a particular byte range of an object.

**Comment by kaneplusplus** [comment]
You can either save it to disk using `save_object` and open a connection. Or, for raw and text data, you can call `rawConnection` or `textConnection` on the return of `get_object`.

**Comment by leeper** [comment]
You can grab particular bytes by passing a header argument. There's an example in `get_object()` documentation: https://github.com/cloudyr/aws.s3/blob/master/R/get_object.R#L37

Or you can do as @kaneplusplus suggests and use a `rawConnection()` of the raw vector returned by `get_object()`.
