### ISSUE TITLE
Fatal Error Pack : LogHttp: Warning: 00000242DBA92F80: request failed, libcurl error: 6 (Couldn't resolve host name)

### ISSUE THREAD

**Issue by BackToNormal** [cloudyr/aws.s3#198]
LogHttp: Warning: 00000242DBA92F80: request failed, libcurl error: 6 (Couldn't resolve host name)
LogHttp: Warning: 00000242DBA92F80: libcurl info message cache 0 (Connection 363 seems to be dead!)
LogHttp: Warning: 00000242DBA92F80: libcurl info message cache 1 (Closing connection 363)
LogHttp: Warning: 00000242DBA92F80: libcurl info message cache 2 (TLSv1.2 (OUT), TLS alert, Client hello (1):)
LogHttp: Warning: 00000242DBA92F80: libcurl info message cache 3 (Could not resolve host: datarouter.ol.epicgames.com)
LogHttp: Warning: 00000242DBA92F80: libcurl info message cache 4 (Closing connection 364)
LogStreaming: Warning: Took 135.07ms to ProcessLoadedPackages
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: begin: stack for UAT
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Fatal error!
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: end: stack for UAT
LogStreaming: Warning: Took 104.03ms to ProcessLoadedPackages
UATHelper: Packaging (Windows (64-bit)): Took 67469.6224921s to run UE4Editor-Cmd.exe, ExitCode=-1073741819
UATHelper: Packaging (Windows (64-bit)): Cook failed. Deleting cooked data.
UATHelper: Packaging (Windows (64-bit)): ERROR: Cook failed.
UATHelper: Packaging (Windows (64-bit)):        (see C:\Users\Oti\AppData\Roaming\Unreal Engine\AutomationTool\Logs\G+Games+UE_4.18\UAT_Log.txt for full exception trace)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Cook Failure

AFTER 2 DAYS OF COMPILE...THIS WAS THE RESULT...WHY?

**Comment by leeper** [comment]
What generated this? Posting error messages with no code is unhelpful. And typing in ALL CAPS is generally considered fairly rude.

**Comment by BackToNormal** [comment]
Well... i don't know what generated this...i want to know what is this error because is the first time i get it...and sorry for the CAPS but i was rly out of my mind because i waited 2 days to compile it...

**Comment by leeper** [comment]
I have no idea what you're talking about.

**Comment by leeper** [comment]
Please just provide an explanation of what you were trying to do and the code you ran that generated this. Along with the output of `sessionInfo()` from the same R session.

**Comment by BackToNormal** [comment]
I wanted to  pack the title (game) for Windows x64 and i just got the errors from the UE4 Editor. 
[UAT_Log.txt](https://github.com/cloudyr/aws.s3/files/1671060/UAT_Log.txt)

**Comment by leeper** [comment]
As far as I can tell, your question has nothing to do with this repo's software (namely, the aws.s3 R package). Please seek help in a more appropriate venue.

**Comment by BackToNormal** [comment]
My question was.. why i get this error? what does it mean?

**Comment by leeper** [comment]
You're showing me a random log file from some software but you haven't said what software, or what operating system, or what action you took that led to that output. It does not look like it is related to R or related to this package.

Show me how it is related to this package (aws.s3) otherwise you're just wasting my time. Sorry if this sounds rude, but I literally have no idea what you're talking about.
