### ISSUE TITLE
Compatibility with DigitalOcean Spaces API

### ISSUE THREAD

**Issue by amoeba** [cloudyr/aws.s3#199]
Some of us are working on adding support in https://github.com/sckott/analogsea for DigitalOcean's new Spaces API which implements Amazon's S3 API. To save duplicated effort, we've mostly been able to use `aws.s3` (Thanks!) to implement all of the API calls. However, creating new Spaces (Buckets) doesn't work via `aws.s3::put_bucket` because of the logic in `aws:::setup_s3_url` regarding virtual- vs. path-based URLs.

I looked at the source and I think this function can be changed in a non-breaking way for `aws.s3` users while still allowing `analogsea` to do what it needs.

There are two relevant sections of `aws.s3::: setup_s3_url`:

https://github.com/cloudyr/aws.s3/blob/8e1dc0d7c5a23c92185d65d69a6b4e6d04c79ceb/R/s3HTTP.R#L223-L227

and

https://github.com/cloudyr/aws.s3/blob/8e1dc0d7c5a23c92185d65d69a6b4e6d04c79ceb/R/s3HTTP.R#L281-L293

I don't think I'm familiar enough with all the reasons for the logic around virtual vs. path URLs so I hesitate to offer a solution but I'd be happy to discuss this and submit a PR if there is a clear path forward. I think the change I'd lobby for would be to let the calling function override the `url_style` argument and honor it unconditionally rather than conditionally overriding it.

**Comment by leeper** [comment]
So digital ocean uses virtual URLs? My impression was that S3 was the only service doing this.

**Comment by amoeba** [comment]
Yep, they use `${REGION}.digitaloceanspaces.com`. [docs](https://developers.digitalocean.com/documentation/spaces/)

**Comment by leeper** [comment]
So, if we dropped the first logical statement (checking whether it is an S3 base URL), everything would work fine for you?

**Comment by amoeba** [comment]
I think so. If you'd like I can test elsewhere and PR if it works.

**Comment by leeper** [comment]
I think this can be safely combined with https://github.com/cloudyr/aws.s3/issues/199
