### ISSUE TITLE
s3write_using

### ISSUE THREAD

**Issue by Rcjuk** [cloudyr/aws.s3#200]
Hi,

Does anyone have an example of passing the encryption header to this function. Tried the following but to no avail.

```R
s3write_using(df, FUN=readr::write_csv, object=file_bucket, bucket=BucketName,
  opts=list(headers = c('x-amz-server-side-encryption' = 'aws:kms')))
```

Am also a noob.

**Comment by leeper** [comment]
Are you getting an error? If so, what is it? And what is the output of `traceback()`?

**Comment by patrick-miller** [comment]
This may not be working because of the underlying reason for my PR #205

**Comment by leeper** [comment]
Yep. Looks like this one should be solved by https://github.com/cloudyr/aws.s3/commit/8e825e2b3976d13e301ca615795b8c13ed4058fa. Will reopen if not.
