### ISSUE TITLE
Reading a csv file from S3:// in R

### ISSUE THREAD

**Issue by Meraki0918** [cloudyr/aws.s3#201]
Hello I have uploaded a csv file from my computer to my personal bucket called Y9. 

I have then used EC2 instance and launched R studio. 

I am trying to read the csv file that I have uploaded in Y9 with the following code. 

```
library("aws.s3")
c<- get_object("s3://1/Y9/data.csv")
cobj <-rawToChar(c)
```

I am getting a error

>  "Error in rawToChar(c): embedded null in string. 

I am new to amazon service.. could any one help me with a piece of code on how I can extract the csv file ?

**Comment by Meraki0918** [comment]
@tomsing1  I tried to read the way you mentioned, but then I am not able to view them as a table. It still looks like a csv file. Should i then mention ("sep, Header ) in read.csv?

**Comment by tomsing1** [comment]
@Meraki0918 
Yes, depending on the format of your csv file, you might need to specify additional arguments.
Can you post the top few lines of your csv file? Then I can help point out which ones might be useful.

**Comment by subhamchand** [comment]
how to download a .docx file then? and do we have a generalization method to read every type of file?
