### ISSUE TITLE
CRAN no longer have precise images, so Travis build fails

### ISSUE THREAD

**Issue by gliptak** [cloudyr/aws.s3#203]
https://cloud.r-project.org/bin/linux/ubuntu/

https://travis-ci.org/cloudyr/aws.s3/jobs/345262016

**Comment by leeper** [comment]
Fixed (via https://github.com/cloudyr/aws.s3/commit/7b9f47be5aca9ac7d9fa32c48a9f01c367b50e89). Thanks!
