### ISSUE TITLE
cloudyr/aws.s3 failed to work if bcrypt lib is also imported 

### ISSUE THREAD

**Issue by dylancis** [cloudyr/aws.s3#204]
The bcrypt library causes aws.s3 to fail for requests once this is loaded.
**Restart your R session and try:**
```
library(aws.s3)  # https://github.com/cloudyr/aws.s3
# library(bcrypt)  # commented on prupose
# config file
appSpecs <- yaml::yaml.load_file("config/app_specs.yaml")
# a3 secret keys
Sys.setenv("AWS_ACCESS_KEY_ID" = appSpecs$awsAccessKey, "AWS_SECRET_ACCESS_KEY" = appSpecs$awsSecretKey)
put_object(file = "global.R", bucket = "dbrs-model-eurmbsinsight-staging-qa", object = "test.txt", check_region = FALSE)

```
_Result is OK:_
> put_object(file = "global.R", bucket = "dbrs-model-eurmbsinsight-staging-qa", object = "test.txt", check_region = FALSE)
[1] TRUE

**Now restart again your R session:**
```
library(aws.s3)  # https://github.com/cloudyr/aws.s3
library(bcrypt)  # now enabled
# config file
appSpecs <- yaml::yaml.load_file("config/app_specs.yaml")
# a3 secret keys
Sys.setenv("AWS_ACCESS_KEY_ID" = appSpecs$awsAccessKey, "AWS_SECRET_ACCESS_KEY" = appSpecs$awsSecretKey)
put_object(file = "global.R", bucket = "dbrs-model-eurmbsinsight-staging-qa", object = "test.txt", check_region = FALSE)
```

_Result is KO:_
> put_object(file = "global.R", bucket = "dbrs-model-eurmbsinsight-staging-qa", object = "test.txt", check_region = FALSE)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.

**Comment by leeper** [comment]
Can you supply the output of traceback() after the error occurs?

**Comment by dylancis** [comment]
sure - here we go:

`Stack trace (innermost first):
    73: curl::curl_fetch_memory
    72: request_fetch.write_memory
    71: request_fetch
    70: request_perform
    69: PUT
    68: s3HTTP
    67: put_object
    66: shipFileToS3 [R/utilities.R#21]
    65: observeEventHandler [D:\Users\cissoud\Documents\dbrs-model-eurmbsinsight-gui/server.R#97]
     1: shiny::runApp
ERROR: [on_request_read] connection reset by peer`

**Comment by leeper** [comment]
What's the `shipFileToS3()` function?

**Comment by dylancis** [comment]
# ship file to   # aws.s3 cloudy R
```
shipFileToS3 <- function(inputFile, bucket, outputFile, subDirectory = NA){
  keyDir <- ifelse(!is.na(subDirectory), paste(subDirectory, outputFile, sep = "/"), outputFile)
  put_object(file = inputFile,
             bucket = bucket, 
             object = keyDir, check_region = FALSE)
}
```

**Comment by leeper** [comment]
I still don't really have enough info to address this. If you can provide a fully reproducible example in a completely minimal environment (e.g., no calls to yaml, no shiny), clean R session (`R --vanilla`), and include the output of `sessionInfo()` and `traceback()`, I may be able to help.
