### ISSUE TITLE
Showing 0kb file size while pushing .csv file from Local Stoarage to s3 bucket Using R

### ISSUE THREAD

**Issue by vinay047** [cloudyr/aws.s3#207]
Hi all,
I used the **put_object** function for uploading  csv file into s3 bucket and  i am able to  push  csv file from local storage to s3 bucket. But when i check my file in s3 bucket it show 0kb file size, I just got the file not the content of the file. Below is the code that is used for pushing file into s3.

library(aws.s3)
 zx <- rawConnection(raw(0), "r+")
put_object(file = rawConnectionValue(zx), bucket = "bucket_name", object = "filename.csv")

Thanks in Advance!!

**Comment by leeper** [comment]
That example code shows you pushing an empty file (i.e., a raw vector of zero length). If you have a file saved locally then the `file` argument should be the path to the file not `rawConnectionValue(zx)`. You don't need `rawConnection()` at all here. See the first example in `? put_object` as guidance.

**Comment by vinay047** [comment]
Thanks a lot @leeper for the prompt response and it works perfectly!!
