### ISSUE TITLE
Error while installing PocketSphinx in python3.6

### ISSUE THREAD

**Issue by vinay047** [cloudyr/aws.s3#209]
Hi,
Tried downloading with pip install pocketsphix but i am facing the below errors.
 
 swig.exe -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    error: command 'swig.exe' failed: No such file or directory 

Thanks in advance!!

**Comment by leeper** [comment]
This is unrelated to this software.
