### ISSUE TITLE
Uploading compressed file

### ISSUE THREAD

**Issue by jeremydmorris** [cloudyr/aws.s3#210]
I'm using this package to archive data to S3 and would like to compress the csv file before it is uploaded. I'm currently using the following code to upload the file.

`to_write <- data.frame(matrix(rnorm(n=100),ncol=2))`
`zz <- rawConnection(raw(0),'r+')`
`readr::write_csv(to_write,path=zz,...)`
`aws.s3::put_object(file=rawConnectionValue(zz),bucket=my_bucket,object='test.csv')`
`close(zz)`

I've tried several things but can't figure out how to write a gzip compressed file. Any help would be appreciated.

**Comment by leeper** [comment]
What part of this isn't working?

**Comment by jeremydmorris** [comment]
The code above works just great, I'd like to upload a gzip compressed file and struggle to figure out how to do that.

**Comment by leeper** [comment]
You can pass any file to the `file` argument. This isn't the right place to ask about how to, in general, create a particular kind of file.
