### ISSUE TITLE
r shiny-  implement reading from S3FS 

### ISSUE THREAD

**Issue by outout** [cloudyr/aws.s3#213]
- [aws s3 ] a question about package functionality

Hi can I setup shiny server to serve files stored on aws s3, for example send signed s3 url and to get back rendered html response. 
Maybe i can discover solution to modify default r shiny content folder and  reading from S3FS a drop-in replacement the File System (FS) implementation  
or any other guideline

**Comment by leeper** [comment]
Probably. Unfortunately, I don't really know anything about Shiny. This package will be useful if you want to interact with S3 via HTTP requests. If you want to mount S3 as a file system, there's not much here that will be useful.
