### ISSUE TITLE
Streaming files form AWS

### ISSUE THREAD

**Issue by tomsing1** [cloudyr/aws.s3#217]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [x] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

I have a very large gzipped compressed text file on AWS and would like to extract the first N rows that match my filtering criteria. 

The `read_using` function is great, but I believe it downloads the complete file first. Is there a way to stream a file from S3, e.g. to read it line by line / in chunks without first retrieving the file and storing it in a temporary location? That way I could stop parsing the file when I have reached N records of interest and would never have to download it in full.

I found the [smart_open](https://pypi.python.org/pypi/smart_open) python module that has this functionality, indicating that this is possible in general.

Thanks for any thoughts!

**Comment by leeper** [comment]
With `get_object()` you can pass a byte range in the `header` argument to retrieve the file by chunk. There's an example of this in `? get_object`. Some higher-level functionality would probably be good here but I don't have time to implement it at the moment.

**Comment by tomsing1** [comment]
Sorry @rachitkinger, I haven't had a chance to look deeper into the `get_object` function and its ability to accept a byte range.

**Comment by rachitkinger** [comment]
@tomsing1 thanks for letting me know.

**Comment by leeper** [comment]
This is now support. `s3connection()` will give you a binary connection from which you can read line by line, or whatever. Let me know if you encounter any problems.

**Comment by tomsing1** [comment]
This is awesome! Thank you so much for adding this functionality. Much appreciated, as is your making the whole suite of cloudyr packages available to the community. 🥇
