### ISSUE TITLE
recursive upload (upload directories to s3)? - question about package functionality

### ISSUE THREAD

**Issue by bheavner** [cloudyr/aws.s3#219]
Is there a mechanism to upload a local directory to s3? 

Something akin to the aws s3 cp --recursive, --include, and --exclude flags?

**Comment by leeper** [comment]
`s3sync()` will do this, but it's two-way by default. I've been meaning to get a clear one-way sync tested.

**Comment by leeper** [comment]
This should now be possible in a one-way fashion (update coming momentarily). Let me know how it works for you.
