### ISSUE TITLE
Specify Custom Endpoint

### ISSUE THREAD

**Issue by jdonnell01** [cloudyr/aws.s3#220]
Is it currently possible to specify a custom endpoint rather than s3.amazonaws.com? The aws.s3 package documentation states to set the AWS_S3_ENDPOINT environment variable to the appropriate host name, however the request still goes to s3.amazonaws.com. I do not see AWS_S3_ENDPOINT as a supported S3 environment variable (https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html). I have set the below environment variables:

Sys.setenv("AWS_ACCESS_KEY_ID" = "access-key",
                 "AWS_SECRET_ACCESS_KEY" = "secret-access-key",
                 "AWS_DEFAULT_REGION" = "region")

**Comment by rvolykh** [comment]
Hello, I'm currently using custom server specified with AWS_S3_ENDPOINT
```
library('aws.s3')
Sys.setenv(AWS_ACCESS_KEY_ID = "my_access_key")
Sys.setenv(AWS_SECRET_ACCESS_KEY = "my_secret_access_key")
Sys.setenv(AWS_S3_ENDPOINT = 'localhost:9000')

print(bucketlist(verbose=T))
```
If `AWS_S3_ENDPOINT` not specified `s3.amazonaws.com` is used
https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L43

**Comment by jdonnell01** [comment]
Thanks @rvolykh. I set the AWS_S3_ENDPOINT environment variable to the appropriate url, however when I try to retrieve the buckets it still says "S3 Request URL: https://s3.amazonaws.com/". What version of AWS.S3 are you using? I only have access to 0.3.3 and it seems that change was made it 0.3.9: https://github.com/cloudyr/aws.s3/blob/master/NEWS.md#awss3-039

**Comment by rvolykh** [comment]
Yes, @jdonnell01 I have ‘0.3.9’

**Comment by leeper** [comment]
This update is not on CRAN yet but hopefully will be soon.

**Comment by jdonnell01** [comment]
Thank you for the update. I am able to explicitly set the base_url in the function call as seen below however now I am receiving a Forbidden (HTTP 403) error. Any ideas how to remediate? 

`print(bucketlist(verbose=T, base_url = Sys.getenv("AWS_S3_ENDPOINT"), region = Sys.getenv("AWS_DEFAULT_REGION")))`

**Comment by leeper** [comment]
Probably a signature error (e.g., wrong credentials being used) or a permission problem on the bucket. Try:

```R
httr::with_verbose(bucketlist(verbose=T, base_url = Sys.getenv("AWS_S3_ENDPOINT"), region = Sys.getenv("AWS_DEFAULT_REGION")))
```

and see if you get more useful information.

**Comment by leeper** [comment]
I'm closing this for the time being. Please post again if you continue to encounter problems.

**Comment by jdonnell01** [comment]
Hi, I am still encountering the 403 error. I am not using a custom hostname:port. The `httr::with_verbose` function produces the following:

`HTTP/1.1 403 Forbidden
Content-Length: 198
Accept-Ranges: bytes
Content-Type: application/xml
Connection: close
 
Parsing AWS API response
Client error: (403) Forbidden`

**Comment by leeper** [comment]
Yes, you can set `use_https = FALSE` in any function call.

**Comment by jdonnell01** [comment]
In testing I believe it may be the version of AWS.S3. When I use version 0.3.8 it seems to work, however when I use the CRAN version (0.3.3) I receive the 403 error. Any idea when the newest version will be pushed to CRAN? Thank you

**Comment by leeper** [comment]
Hopefully later this week.

**Comment by jdonnell01** [comment]
Excellent, thank you.

**Comment by leeper** [comment]
The update is now on CRAN.

**Comment by leeper** [comment]
It's not possible because AWS encourages using V4. You can write your own code if you want by using the v2 authentication function from aws.signature.

**Comment by jdonnell01** [comment]
Ok, so once I create a new signature with the signature_v2_auth function and assign that to a variable am I able to pass that variable to say a get_bucket function?

**Comment by leeper** [comment]
No. That's not possible. Use of V4 is hard-coded in s3HTTP(). What I meant was you could write a full equivalent functions to what's available in this package.

**Comment by jwilliamsholt** [comment]
"Thank you for the update. I am able to explicitly set the base_url in the function call as seen below however now I am receiving a Forbidden (HTTP 403) error. Any ideas how to remediate?"

I'm running into this error. The version I've downloaded from CRAN is 0.3.21. I've used the same credentials to access via AWS CLI.
