### ISSUE TITLE
Signature doesn't match with hostname:port

### ISSUE THREAD

**Issue by rvolykh** [cloudyr/aws.s3#222]
Please specify whether your issue is about:

 - [x] a possible bug

With custom AWS_S3_ENDPOINT it became possible to use hostname:port, but in current signature calculation only hostname is used in `host` (canonical headers) and so custom s3 server responds with `signature doesn't match` because in request it has `host`:`hostname:port`.

Put your code here:

```R
canonical_headers <- c(list(host = p$hostname,
```

PR: https://github.com/cloudyr/aws.s3/pull/221

**Comment by leeper** [comment]
Thanks! Merging this now.
