### ISSUE TITLE
typo in dualstack accelerated URL

### ISSUE THREAD

**Issue by peterfoley** [cloudyr/aws.s3#223]
A URL in s3HTTP.R is missing the first E in accelerate
https://github.com/cloudyr/aws.s3/blob/9058075e2e6be2f9be4464c10cc3e0751d1efcbb/R/s3HTTP.R#L252
The URL should be `s3-accelerate.dualstack.amazonaws.com`, confirmed by https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

**Comment by leeper** [comment]
Thanks!
