### ISSUE TITLE
How to read/Store data in parquet format from/to S3 to my R environment?

### ISSUE THREAD

**Issue by Nikita673** [cloudyr/aws.s3#225]
Currently I am working on AWS, where all the data are stored in parquet format.
How to read the data from s3 to my local system and write that data in to s3 in Parquet format.
Thanks in advance

**Comment by leeper** [comment]
Unfortunately your question isn't about this package. You'll want to look into general tools for working with data in that format. This post looks helpful: https://stackoverflow.com/questions/30402253/how-do-i-read-a-parquet-in-r-and-convert-it-to-an-r-dataframe
