### ISSUE TITLE
curl ssl error when using bucket named with periods?

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.s3#23]
As far I can tell, I have two identically configured buckets, one named `drat` and one named `packages.ropensci.org`.  I can get / copy files to either one using the AWS CLI.  When I try to get or push files to `drat` via `aws.s3`, things are rosy.  When I try `packages.ropensci.org`, I get the error: 

```
 x = getobject("packages.ropensci.org", "index.html", region="us-west-2", key = Sys.getenv("AWS_ACCESS_KEY_ID"), secret = Sys.getenv("AWS_SECRET_ACCESS_KEY"))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK

Enter a frame number, or 0 to exit   

1: getobject("packages.ropensci.org", "index.html", region = "us-west-2", key 
2: s3HTTP(verb = "GET", url = paste0("https://", bucket, ".s3.amazonaws.com/",
3: httr::GET(url, H, ...)
4: request_perform(req, hu$handle$handle)
5: request_fetch(req$output, req$url, handle)
6: request_fetch.write_memory(req$output, req$url, handle)
7: curl::curl_fetch_memory(url, handle = handle)

```

I'm stumped, no idea what is different.  I took a quick look at the headers and url in the debugger but nothing stands out to me there either.  (If you wanna take a look at this exact example I can email you some credentials)

**Comment by almartin82** [comment]
for testing purposes, I suppose the way to test that idea about periods is
to copy drat (and its config), rename it drat.copy, and see if we can push
to it?

(mobile)

**Comment by cboettig** [comment]
Is there such a thing as renaming buckets or copying buckets?  It looks like the closest thing one can do is manually create a new bucket...

**Comment by almartin82** [comment]
There appears to be a CLI
http://stackoverflow.com/questions/4663016/faster-s3-bucket-duplication

Not sure what it does under the hood though

(mobile)

**Comment by cboettig** [comment]
right, but even that is just copying the files over to a new bucket that you have to create (and set permissions for) first.

**Comment by almartin82** [comment]
this one appears to copy the ACL?
https://github.com/cobbzilla/s3s3mirror

**Comment by cboettig** [comment]
same errors. very strange.

**Comment by cboettig** [comment]
Okay, this seems to arise because `getobject` and `putobject` by default use the URL notation of `<BUCKET>.s3.amazonaws.com/index.html`.   Somewhat confusingly, s3HTTP defaults to the other notation, `https://s3-<REGION>.amazonaws.com/<BUCKET>`  Notably this problem with buckets that have `.` in the name goes away when using the subdirectory/path format instead of the subdomain format; e.g. when calling s3HTTP directly without a `url` argument.  

Not sure why that should be, but buckets with `.` in the name seem pretty common (e.g. Amazon seems to require that buckets used for static web hosting use the same name as the forwarding URL).  Anyway, perhaps we should adopt the path style for now in the `object` methods?

**Comment by cboettig** [comment]
Looks like the region reorganization introduced in version 0.1.21 has re-introduced this issue.  Same curl error with buckets that have periods in their names, works fine with other buckets.

**Comment by leeper** [comment]
Love the contradictory advice in [the S3 documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) on this:

> When using virtual hosted–style buckets with SSL, the SSL wildcard certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic. **We recommend that you do not use periods (".") in bucket names.**

@cboettig Is the code and error message you're receiving the same as in the original issue?

**Comment by cboettig** [comment]
Yup, same code (impacts any code that takes a bucket name), same error.  

Ha, thanks Amazon fire the conflicting advice.

**Comment by leeper** [comment]
Some research suggests this is a known S3 "gotcha". Some solutions are [here](http://stackoverflow.com/a/29441009/2338862). Seems every language is forced to implement path-style notation if the bucket name has a dot.

**Comment by cboettig** [comment]
That's a nuisance. At least it sounds like there's a standard workaround to follow here.  I guess that's the query structure we introduced in #24 ?

**Comment by leeper** [comment]
Yea, I'll put something together.

**Comment by leeper** [comment]
So, we basically already have a workaround for this. When you want to perform an operation on a bucket with a dot, you can simply pass the bucket name as the `path` argument to `s3HTTP()` and give an empty character string for `bucket`, like:

```{r}
get_bucket(bucket = "", path = "packages.ropensci.org")
```

For objects, it's the same idea, but you prepend the bucket name to the object key:

```{r}
get_object(bucket = "", object = "packages.ropensci.org/somefile.txt")
```

So the choices are:
 1. document this workaround, or
 2. create an internal logic that does this whenever a bucketname has a dot

**Comment by cboettig** [comment]
Great!  If course 2 is more elegant but I think either would be fine. Thanks!

**Comment by diegoperoni** [comment]
Hi, I've just resolved (.) problem changing uri:
from: "229922685856.dashboard.s3-website-eu-west-1.amazonaws.com"
to: "s3-website-eu-west-1.amazonaws.com/229922685856.dashboard"

but now my bucket request give my a timeout:

get_bucket(
  bucket = 's3-website-eu-west-1.amazonaws.com/229922685856.dashboard',
  key = 'XXXXXXX',
  secret = "XXXXXXXX"
)
[1] "eu-west-1"
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

Someone can help me?
Thanks in advance...

**Comment by ctownsen357** [comment]
@diegoperoni  have you given @leeper 's solution a try?

**Comment by nqbao** [comment]
I am also having the same problem ... Let me see if i can help on this

**Comment by nqbao** [comment]
I can confirm using this workaround works for me

`save_object(object = 'bucket.with.dot/path/to/object/key', bucket = '')`

**Comment by seandavi** [comment]
Just out of curiosity, is there a reason not to default to path-based calls only?

**Comment by leeper** [comment]
I believe this should now be fixed by switching to path-style bucket syntax, which can be toggled back to the old (problematic) default by setting `url_style = "virtual"`. There was a trade-off here relating to needing [to know the bucket region when using path-style syntax](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html) but that has been negated by the `check_region = TRUE` default.
