### ISSUE TITLE
Access Denied while reading data from S3

### ISSUE THREAD

**Issue by aditya-kothari** [cloudyr/aws.s3#230]
Hola!,
 
When I tried to test read a file that’s on our S3 using the steps mentioned [here](https://github.com/cloudyr/aws.s3), I keep getting an error of ACCESS DENIED (full description below). I have also tried all the steps mentioned in issues #122 , #106, #143 and #142 but the issue still remains. Any help on this is greatly appreciated.
 
Background
•	OS – Windows
•	Package – aws.s3 (cloudyR)
Installed it using the below command:

install.packages("aws.s3", repos = c("cloudyr" = "http://cloudyr.github.io/drat"), INSTALL_opts = "--no-multiarch")
 
**R Code:**
 ```
library(aws.s3)
Sys.setenv("AWS_ACCESS_KEY_ID" = "AKXXXXXXXXXXXXXX2A","AWS_SECRET_ACCESS_KEY" = "iXXXXXXXXXXXXXXXXXJf")
obj <-get_object("s3://quasar-ib-vis/asn_ship_units.csv")
```

 **Error:**
 
```
List of 4
$ Code     : chr "AccessDenied"
$ Message  : chr "Access Denied"
$ RequestId: chr "7B8FA50923D9A784"
$ HostId   : chr "xkQQ1J1x+eviFU7AAjjSGffYbo2qwoPbr4TVzJxdX01Ow7m0Ef4yJmd8dXmh2opp59/BpGzLie8="
- attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr "7B8FA50923D9A784"
  ..$ x-amz-id-2       : chr "xkQQ1J1x+eviFU7AAjjSGffYbo2qwoPbr4TVzJxdX01Ow7m0Ef4yJmd8dXmh2opp59/BpGzLie8="
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Wed, 16 May 2018 16:04:35 GMT"
 ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
- attr(*, "class")= chr "aws_error"
- attr(*, "request_canonical")= chr "GET\n/quasar-ib-vis/\nlocation=\nhost:s3.amazonaws.com\nx-amz-date:20180516T160434Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c"| __truncated__
- attr(*, "request_string_to_sign")= chr "AWS4-HMAC-SHA256\n20180516T160434Z\n20180516/us-east-1/s3/aws4_request\n12070919fa3800637b5ed5d1f4e7ba5bb1e10d5c07908eae0968554"| __truncated__
- attr(*, "request_signature")= chr "AWS4-HMAC-SHA256 Credential= AKXXXXXXXXXXXX2A/20180516/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=1"| __truncated__
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).
```

**Session Info**
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.signature_0.4.1 aws.s3_0.3.12      

loaded via a namespace (and not attached):
[1] httr_1.3.1      R6_2.2.2        tools_3.3.1     base64enc_0.1-3 curl_2.6       
[6] Rcpp_0.12.12    xml2_1.1.1      digest_0.6.12

**My analysis**
First I thought the error must be due to S3 considering default region as us-east-1 while my bucket was created in ap-south-1, but even after setting the system env to the below, the same error popped up
 
Sys.setenv("AWS_ACCESS_KEY_ID" = " AK**************2A ","AWS_SECRET_ACCESS_KEY" = " i******************Jf", "AWS_DEFAULT_REGION" = "ap-south-1")

I also tried using with check_region=F, it returns the below:

```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>quasar-ib-vis</Bucket><Endpoint>quasar-ib-vis.s3.amazonaws.com</Endpoint><RequestId>6368A0C266FF959D</RequestId><HostId>yzATdW7hcjF30YM8T1SkTPNbnU45R7OLMMRm8kJu7gV+dcKNnuG1man1owPEiaR2lQOZPvaZTJY=</HostId></Error>"
```

**Comment by leeper** [comment]
Try `obj <-get_object("s3://quasar-ib-vis/asn_ship_units.csv", url_style = "virtual")`

**Comment by wibo-pipping** [comment]
Hi @leeper,
I am actually running into the same issue. 
I tried both with the credentials in a credentials file and set as environment variables but for some reason it keeps throwing the error.

I also tried `obj <-get_object("s3://quasar-ib-vis/asn_ship_units.csv", url_style = "virtual")` but it resulted in the same error

Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).

See my session information here:
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4 readxl_0.1.1      bit64_0.9-5       bit_1.1-12        aws.s3_0.3.11     xlsx_0.5.7       
[7] xlsxjars_0.6.1    rJava_0.9-8      

loaded via a namespace (and not attached):
[1] httr_1.3.1          R6_2.2.2            tools_3.2.5         base64enc_0.1-3     curl_2.5           
[6] Rcpp_0.12.10        aws.signature_0.4.1 xml2_1.1.1          digest_0.6.12

**Comment by leeper** [comment]
Are you sure you have permission to access the bucket?

**Comment by jonasbu11** [comment]
Getting the same error, with this extra info:  We are behind a restrictive proxy requiring certain endpoints.  So definitely the fix _should_ be url_style = virtual .  This is what we have to do for awscli, in fact.  But it seems not working in aws.s3.
Version is 0.3.12 from cran.

**Comment by jonasbu11** [comment]
Additional info:
We got this working using e.g. get_bucket(<bucketname>, check_region = FALSE, url_style = 'virtual')
So it seems the issue for us is check_region

**Comment by leeper** [comment]
`check_region = FALSE` is now the default.
