### ISSUE TITLE
s3sync error in argument check

### ISSUE THREAD

**Issue by tash20** [cloudyr/aws.s3#231]
I encountered an error when using `s3sync()`:

```
> s3sync(bucket = "examplebucket") # This is an existing bucket
Error in formal.args[[as.character(substitute(arg))]] : 
  no such index at level 1
```

This would be a bug when calling `match.arg()` to check an upload/download direction. The following amendment in s3sync.R resolved the issue:

`direction <- match.arg(tolower(direction), c("upload", "download"), several.ok = TRUE)`

**Comment by leeper** [comment]
Thanks!
