### ISSUE TITLE
Add these?

### ISSUE THREAD

**Issue by plroebuck** [cloudyr/aws.s3#234]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [X] a suggested code or documentation change, improvement to the code, or feature request

Put your code here:

```R
## load package
library("aws.s3")

## Returns size of S3 file, or NA if it does not exist
s3file.size <- function (object, bucket, ...) {
  suppressMessages(
    headObj <- head_object(object=object,
                           bucket=bucket,
                           ...)
  )
  if (as.logical(headObj)) {
    as.double(attr(headObj, "content-length"))
  } else {
    as.double(NA)
  }
}

## Returns TRUE if S32 file exists; otherwise, FALSE
s3file.exists <- function (object, bucket, ...) {
  suppressMessages(
    headObj <- head_object(object=object,
                           bucket=bucket,
                           ...)
  )
  as.logical(headObj)
}

```

**Comment by leeper** [comment]
I think you want the `head_object()` function, at least for the second case.

**Comment by plroebuck** [comment]
Not sure I follow you. Code uses `head_object()` already...

**Comment by leeper** [comment]
I'm saying the added value is not clear to me.

**Comment by plroebuck** [comment]
Though `head_object()` exists, it's not exactly an obvious mapping for the package user;
I had to do several google searches, as well as figure out how to not have the output for nonexistent files show up. `s3file.exists()` is quite obvious as to what it does. It's value is **exactly** that. Additionally, my client code is implicitly documented -- doubt most people unfamiliar with your API would equate these two routines, requiring them to have to look up all this same information again.

**Comment by leeper** [comment]
That's helpful. Thank you.

**Comment by leeper** [comment]
Thanks, again. This is now implemented as `object_size()` and `object_exists()`.
