### ISSUE TITLE
How to show progress (via curl)

### ISSUE THREAD

**Issue by plroebuck** [cloudyr/aws.s3#235]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [X] a question about package functionality
 - [X] a suggested code or documentation change, improvement to the code, or feature request

For instance, `s3readRDS` on large files. "httr"/"curl" have ability to do progress callbacks.
But haven't figured out how to pass whatever options are needed down to where they would be used.

**Comment by leeper** [comment]
Good idea. We would just need to add a `progress()` option to [the `GET()` call here](https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L129) and similar functions further down. Might be nice to make it conditional on the [`verbose` argument](https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L44).

**Comment by leeper** [comment]
This is now implemented as a `show_progress` argument to `s3HTTP()`, which defaults to FALSE.
