### ISSUE TITLE
Reading Raster files (images) from S3 Bucket

### ISSUE THREAD

**Issue by adbedada** [cloudyr/aws.s3#236]
I am attempting to read several raster files stored in s3 bucket and stack them together for further analysis. I was able to read them as s3 objects but I'm having issue with creating a RasterLayer Object. 

Here is what the code looks like: 

R
## load package
	library("aws.s3")
     rasters<-get_bucket(bucket="my-bucket")
     rasters<-get_bucket_df(bucket="my-bucket")

and I can see that the names of my file with:
    
    list_files<-rasters$Key

[1] "image_1.tif"       "image_2.tif"         
[3] "image_3.tif"       "image_4.tif"           

In order to create a RasterLayer Object, I would use: 

    for(i in list_files) {assign(unlist(strsplit(i, "[.]"))[1], raster(i))}

But, the following error returns: 

Error in .local(.Object, ...) : 

 >`/home/rstudio/aws_s3_testing/image_1.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

So, instead of checking for the files inside the s3 bucket, the script for creating raster object is checking the local directory(files).  Do you know what might be causing this error?

Thanks for your help.

**Comment by leeper** [comment]
You need to call `get_object()` or `save_object()` for the keys to get the objects locally before doing anything with them.

**Comment by adbedada** [comment]
Thanks@leeper. I finally figured the issue with raster objects. Basically, it has to do with parsing the dataset. There are some other issues I'm still trying to figure out but it has nothing to do with aw.s3. T

**Comment by PriyaDhalwani** [comment]
@adbeda I am facing the same issue while loading images from S3. Could you help me with the solution.
Thanks
