### ISSUE TITLE
Suggest an ideal way to write log on S3

### ISSUE THREAD

**Issue by talegari** [cloudyr/aws.s3#238]
Dear Leeper,

(question about functionality)
- How to log to a file on S3 using `futile.logger` type semantics? ex: `flog.logger("tawny", WARN, appender=appender.file('tawny.log'))`
- How to open a file connection (like `conn <- file("foo.txt", "wt")`) on S3 and write to it (like `writeLines("something", con = conn)`) and then close it (like `close(conn)`)?

Thanks,
Srikanth KS

**Comment by leeper** [comment]
In general, S3 is not a great tool for this kind of thing as there is no way to append data to an S3 object. There are only full file replacement operations. This means a logger would have to copy the entire log locally (i.e., `get_object()`/`save_object()`), append locally, and then replace (i.e., `put_object()`). You might be better off looking at something like **aws.sqs** to create a queue that you can then process or clear later:

```R
library("aws.sqs")

# create a queue
queue <- create_queue("ExampleQueue")
  
# send message to queue
send_msg("ExampleQueue", "This is a test message")
# receive a message
(m <- receive_msg("ExampleQueue", timeout = 0))
  
# delete a message from queue
delete_msg("ExampleQueue", m$ReceiptHandle[1])
  
# delete queue
delete_queue("ExampleQueue")
```
