### ISSUE TITLE
put_bucket error: Argument object must be of type character or raw vector

### ISSUE THREAD

**Issue by SimonPBiggs** [cloudyr/aws.s3#243]
Possible bug in put_bucket.  Using a brand-new AWS (free) account I'm attempting basic operations with S3 storage.  The following code results in the error: **"Error: Argument object must be of type character or raw vector if serialize is FALSE"**

```R
library("aws.s3")

Sys.setenv("AWS_ACCESS_KEY_ID" = "XXX",
           "AWS_SECRET_ACCESS_KEY" = "XXX",
           "AWS_DEFAULT_REGION" = "us-east-1")

bucket_name <- paste(c("investigate-test-", sample(c(0:9, letters), size = 10, replace = TRUE)), collapse = "")

put_bucket(bucket_name)

```

To try to rule out permission problems, I successfully created a bucket with the same name through the AWS CLI: 

*aws s3api create-bucket --bucket investigate-test-i0ci9s8jx8 --region us-east-1*

I have also had success with aws.s3 get_bucket and put_object functions against a bucket created interactively in the AWS S3 UI

Session Info:

R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.3.12

loaded via a namespace (and not attached):
 [1] httr_1.3.1          compiler_3.4.4      R6_2.2.2            tools_3.4.4         base64enc_0.1-3     curl_3.2           
 [7] yaml_2.1.19         Rcpp_0.12.18        aws.signature_0.4.4 xml2_1.2.0          knitr_1.20          digest_0.6.15      
[13] mime_0.5

**Comment by leeper** [comment]
Can you rerun that command as:

```R
httr::with_verbose(put_bucket(bucket_name, verbose = TRUE))
```

and paste in the output (redacting anything sensitive).

**Comment by SimonPBiggs** [comment]
Please see the console output below:

> Checking for credentials in user-supplied values
Checking for credentials in Environment Variables
Using Environment Variable 'AWS_ACCESS_KEY_ID' for AWS Access Key ID
Using Environment Variable 'AWS_SECRET_ACCESS_KEY' for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
S3 Request URL: https://s3.amazonaws.com/investigate-test-ua21z0j39t/
Executing request with AWS credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
Error: Argument object must be of type character or raw vector if serialize is FALSE

**Comment by leeper** [comment]
Thanks. This should be fixed now.

**Comment by MarcinKosinski** [comment]
@leeper I see similar issues and I am using manual bucket creation and `put_folder` function for subdirectories

**Comment by MarcinKosinski** [comment]
```
> httr::with_verbose(put_bucket('text1/text2', verbose = TRUE))
Checking for credentials in user-supplied values
Checking for credentials in Environment Variables
Using Environment Variable 'AWS_ACCESS_KEY_ID' for AWS Access Key ID
Using Environment Variable 'AWS_SECRET_ACCESS_KEY' for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
S3 Request URL: https://s3.amazonaws.com/text1/text2/
Executing request with AWS credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
Error: Argument object must be of type character or raw vector if serialize is FALSE
``

**Comment by nli045** [comment]
I have the same error message when using the `put_object` function
