### ISSUE TITLE
[question] rename object already in S3?

### ISSUE THREAD

**Issue by sheffe** [cloudyr/aws.s3#245]
Hello, I use this package all the time and really enjoy it! Thanks for all your work.

Is it possible to do a simple renaming of objects already on S3 directly from the R interface? I'm working with many (~10k files) that I inadvertently misnamed, and download/re-upload in a get/put/delete process would be a pretty big time/IO loss. [If this is possible and I just missed it in search, I will happily volunteer to write up something in the docs as penance :)]

**Comment by leeper** [comment]
It's not possible to rename. You have to copy and delete. There's not a function for copying currently. Instead, you should be able to use:

```R
put_object("", "s3://bucket/newobject", headers = list("x-amz-copy-source" = "bucket/oldobject"))
delete_object("s3://bucket/oldobject")
```

See https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html

**Comment by sheffe** [comment]
Thanks for the very fast response @leeper ! This looks pretty straightforward.
