### ISSUE TITLE
Documentation update needed on object_exist function

### ISSUE THREAD

**Issue by rzrkal** [cloudyr/aws.s3#249]
Hi guys.

I found in the main README.md the reference of the `object_exist` function, however it seems was deprecated in favor of `head_object`. Making a quick search on repo I find the function is still there but for some reason, does not wok for me .

Cheers

**Comment by leeper** [comment]
What do you mean "does not work"? It is a new function, not a deprecated one.

**Comment by rzrkal** [comment]
Sorry for not being more specific. 
When installing the package on my local machine (mac), the function `object_exists` is there and works fine. Also I can find it on documentation when using `?object_exists`. Something weird is that when running `sessionInfo()` the version is 0.3.19

Now, when installing the package on a remote server (ubuntu) the function does not exists. There is no documentation and, what is for me more strange, is that the version is 0.3.12. According to the repo the latest version is 0.3.12.

When looking for the documentation:
https://cloud.r-project.org/web/packages/aws.s3/aws.s3.pdf
Here it says the latest release is 0.3.12 and there is no `object_exists` function on it, which makes sense with the repo and the documentation I can find.

So I am a little confused, haha.

**Comment by leeper** [comment]
The latest version is not yet on CRAN, so if you're pulling a current Ubuntu binary it won't have all of the latest updates available from GitHub.

Use the `remotes::install_github()` function to get the dev version.

**Comment by rzrkal** [comment]
You are right, that solved everything.
Thanks
