### ISSUE TITLE
Overflow in put_object

### ISSUE THREAD

**Issue by RyanKlaas** [cloudyr/aws.s3#264]
I'm working with some large files that need to get up to S3, inside the put_object.R when using multipart = T, the function calculate_data_size has the as.integer cast in the return. My current object's file.size(data) returns 3009574724 which is outside the range of int. 

Instead it may be good to just have an is.numeric check before the return?
or increasing the cast to a int 64? 
Quick work around for me was to split the object. 

I can write a fork if needed unless I'm overlooking something.
also, bit off topic, any thoughts on parrallelizing the loop?

**Comment by himanshu-sikaria** [comment]
I ran into the same issue while uploading a 13GB file. @leeper can we merge this pull request faster?

**Comment by acolum** [comment]
This issue has been fixed with PR #273.
