### ISSUE TITLE
Access Denied despite permissions in Job Role

### ISSUE THREAD

**Issue by erikor** [cloudyr/aws.s3#269]
The following simple example:

     library(aws.s3)
     get_bucket("interlinked")[[1]]

Works fine for me on my development EC2 instance, and within a docker container running on that instance.  However, it failed when submitted as an AWS Batch job with "Access Denied". This got particularly confusing because the aws cli tools worked fine within my batch jobs as well as in my development environment.

The reason turned out to be that I have IAM Roles defined for both my compute environment (more restrictive) and my jobs (less restrictive, in this case).  EC2 roles are found by `locate_credentials` (via `aws.ec2metadata::metadata`), but not elastic container service task (job) roles. 

The solution was just to give my compute environment role the permissions any job might want.  But it might be useful to note in the docs somewhere that only EC2 roles are supported by the `aws.s3` and related tools.  In the long term, supporting Job Roles might be cool for those of us using `cloudyr` with AWS Batch.

**Comment by erikor** [comment]
also seems related to cloudyr/aws.signature#34

**Comment by s-u** [comment]
And as such should no longer be an issue. If so, please re-open and specify exactly which operation gets denied.
