### ISSUE TITLE
how to disable including row names as a new column in put_object(csv)

### ISSUE THREAD

**Issue by AhuPersonal** [cloudyr/aws.s3#280]
Hi,

I am using put_object to save my dataframe in an s3 bucket. When I do this with the following code:

```
# write to an in-memory raw connection
temp_dataset <- rawConnection(raw(0), "r+")
write.csv(df, temp_dataset)

# upload the object to S3
aws.s3::put_object(file = rawConnectionValue(temp_dataset),object = paste0(paste0("s3://mybucket/myfolder/",Sys.Date(),"/myfile.csv")))

# close connection
close(temp_dataset)
```

In the s3 location, I see the csv file. However, it has 1 more column without a header. The row values  of that column are 1,2,3,4,.... and so on. I assume these are rownames and I don't want to see this new column in my csv file saved in the s3 bucket.

Is there a way to disable this ?

Thanks

**Comment by s-u** [comment]
Noting to do with `aws.s3` - see `?write.csv` in R
