### ISSUE TITLE
R load json files from S3?

### ISSUE THREAD

**Issue by solunsteve** [cloudyr/aws.s3#287]
I have a repository in S3:

```
my_bucket:
    folder1
      subfolder11
        subfolder111
    folder2
      subfolder21
       subfolder221

```
I am trying to connect and load all files in all relevant folders in my bucket. Here is how I am trying to do this:

```
library(aws.s3)
bl <- bucketlist()

### Builds a dataframe of the files in a bucket###
dfBucket <- get_bucket_df(bucket = "my_bucket", prefix = "folder1/", max = Inf)
```
I am getting the following error:

> Error in z[["Owner"]][["ID"]] : subscript out of bounds

Please advise.

**Comment by solunsteve** [comment]
UPDATE: I actually can run this command on other buckets and the issue is focusing on very long file names stored in this particular bucket in S3.

Please advise how to solve it given the new info.

**Comment by solunsteve** [comment]
Reopening, closed by mistake.

**Comment by solunsteve** [comment]
SOLVED BY USING rbindlist(dfBucket)!

**Comment by s-u** [comment]
It looks like this is no longer relevant for the current version.

**Comment by JerePlum99** [comment]
I'm still experiencing this error on version `0.3.21` - which I believe is the current version. As noted above, I can solve with `rbindlist` but wanted to note it still exists.

**Comment by cbatson** [comment]
Occurs on version `0.3.22`. The workaround appears to be along the lines of `as.data.frame(data.table::rbindlist(get_bucket(...)))`.
