### ISSUE TITLE
object methods shouldn't set parsed_response (or other s3HTTP defaults) internally

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.s3#29]
some of the object wrappers like `getobject` set values of arguments to `s3HTTP()` internally in a way that isn't exposed in their own arguments.  e.g. `getobject` explicitly sets `parsed_response = FALSE` in its call to `s3HTTP`, meaning that this argument can no longer be passed through `...` part of the `getobject()` call as one might expect from the documentation.  

As a result, there is no way to get an unparsed response from these functions, as they work by getting an unparsed response from `s3HTTP()` and then parsing it themselves.  

I understand that the default parsing strategy of `s3HTTP` may not be appropriate for all the object methods.  If we cannot modify the s3HTTP parsing strategy to do the right thing in each case and want custom parsing for each `object` method, then maybe we should set the s3HTTP parse method to be FALSE by default, such that the object methods could also respect the `parsed_response = FALSE` argument and return an unparsed http response object when asked to do so?

**Comment by leeper** [comment]
What about just adding a `parse_response` argument to all the functions? If `TRUE`, they just pass the output of `s3HTTP` directly; otherwise they rely on default parsing and any additional function-specific parsing. Seems like the easiest way to do it.

I would think in almost every case the default should be `TRUE`.

**Comment by leeper** [comment]
This doesn't appear to be an issue in current version.
