### ISSUE TITLE
get_objectkey.character() isn't vectorized (get_bucketname.character() neither)

### ISSUE THREAD

**Issue by colman-humphrey** [cloudyr/aws.s3#293]
When calling a method that can accept a vector, e.g. `delete_object`, the vector goes to `get_objectkey`. When it's a character, the first line of the code is `if (grepl("^s3://", x)) {`, which produces a warning, since the `if` statement only checks the first element of the vector.

This isn't a huge problem in general, and should be a somewhat simple fix - and I'm happy to make a pull request! But I guess there are different ways to solve it. For example, `get_objectkey` could be vectorized. Alternatively, we could force all object to be consistent in how they begin (all with bucket or none, say), so at some point an error could be thrown if they weren't consistent, and then `get_objectkey` is doing the right thing (we'd still fix it, but with other changes either elsewhere, or within the function).

Again, happy to make a pull request once it's clear what way this should go.

This issue is about:

 - [x] a possible bug
 - [x] a suggested code or documentation change, improvement to the code, or feature request

The following code should reproduce the warning even though it will also likely throw an error about the bucket not existing (hopefully no-one is using `some_bucket`...).

```R
## load package
library("aws.s3")

## code goes here
delete_object(object = c("file1.csv", "file2.csv"),
              bucket = "some_bucket")

## session info for your system
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.3.20    conflicted_1.0.1

loaded via a namespace (and not attached):
 [1] httr_1.4.0            compiler_3.5.2        R6_2.4.0             
 [4] aws.ec2metadata_0.1.5 tools_3.5.2           base64enc_0.1-3      
 [7] curl_3.3              Rcpp_1.0.1            aws.signature_0.4.5  
[10] memoise_1.1.0         xml2_1.2.0            jsonlite_1.6         
[13] digest_0.6.18         rlang_0.3.4          
```

Thanks again to @leeper for all the hard work!

**Comment by s-u** [comment]
They should be now thanks to 56cb4377
