### ISSUE TITLE
s3read_using fails after ignoring check_region and region inputs

### ISSUE THREAD

**Issue by sheffe** [cloudyr/aws.s3#294]
I’m struggling to get a real reprex together on this -- requires a particular configuration of buckets across regions -- but the diagnosis looks to be pretty straightforward.

The setup: I have two buckets in two regions, e.g. one in `us-east-2` and the other in `us-east-1`. The default region for my account is set to `us-east-2`. `save_object()` calls to the bucket in `us-east-1` work just fine as long as `check_region = TRUE` or `region = “us-east-1”`, which is the expected behavior. 

However, `s3read_using` with any set of options (check_region or explicitly specified region) still fails. I noted in the `s3read_using` function ([line reference here](https://github.com/cloudyr/aws.s3/blob/8c722f8e84ea9f645ea394ef0908cfc003251155/R/s3read_using.R#L61)) that `…` params normally passed to `s3http` are not actually passed in when calling `save_object` and storing the output to a tempfile.

I'll try to get a PR together soon -- should require adding `...` to the `save_object` calls but I'll need to do some testing.

**Comment by fcocquemas** [comment]
The syntax is not necessarily consistent, but I'm having success using `s3read_using(FUN, bucket=b, object=obj, opts = list(region = "us-east-1"))`. Does that solve it for you?
