### ISSUE TITLE
trigger s3 event if an object doesn't exist in bucket

### ISSUE THREAD

**Issue by abbaswattoo** [cloudyr/aws.s3#300]
Can you please guide to trigger Lambda function when an object doesn't exist in S3?

For example https://images.domain.com/example.jpg. 

if want to trigger Lambda function if example.jpg doesn't access.

Thank you.

**Comment by s-u** [comment]
That is not supported by S3 - for a list of supported events see:

https://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html#supported-notification-event-types
