### ISSUE TITLE
[help] s3sync fails

### ISSUE THREAD

**Issue by ignacio82** [cloudyr/aws.s3#304]
I was able to save an object to my bucket by running:

```r
put_object("./bart_base.yaml", bucket = "ignacio/configs", object = "bart_base.yaml")
```

Now I want to synchronize my bucket in an empty rstudio project. I tried the following

```r
aws.s3::s3sync(bucket = "ignacio", direction = "download")
1 local file to sync
Getting bucket 'ignacio'
4 objects retrieved from bucket 'ignacio'
4 bucket objects not found in local directory
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Failed to open file C:\Users\IMartinez\Documents\orchestration\configs\.
```

I tried creating an empty configs folder but that did not solve the problem.

What am I doing wrong?

**Comment by kenahoo** [comment]
@ignacio82 I think this isn't your fault - the `s3sync` function seems broken to me.  I'm about to open another ticket about it.

**Comment by s-u** [comment]
I'm just in the middle of re-factoring `s3sync` - it makes some assumptions that are no longer true, but feel free to file an issue, but don't file PRs as they will conflict with my local changes.

**Comment by s-u** [comment]
@ignacio82 please note that you are using two different bucket names "ignacio/configs" and "ignacio" - they are two different buckets. That said, please test the current version, `s3sync` has been re-factored in the current version so hopefully works better. @kenahoo

**Comment by andrewcstewart** [comment]
Hey @s-u - which version exactly has the refactored `s3sync`?  Because I'm on 0.3.22 (which as far as I can tell is the latest) and am getting the same exact `Error in curl::curl_fetch_disk(url, x$path, handle = handle) :` error.

Happy to create a new ticket.
