### ISSUE TITLE
Providing options to s3write_using

### ISSUE THREAD

**Issue by stevecondylios** [cloudyr/aws.s3#307]
`s3write_using` appears to ignore `opts` provided to it (see [here](https://stackoverflow.com/questions/57052566/how-to-provide-options-when-writing-to-s3-from-r-using-s3write-using)).  There is a workaround [here](https://stackoverflow.com/a/57052685/5783745)

```r
mywrite <- function(x, file) {
     write.csv(x, file, row.names=FALSE)
}

s3write_using(iris, FUN = mywrite, object = "iris.csv", bucket = "some-bucket")
```
Is am not sure if this is a bug or if the `opts` are simply not being provided correctly?

**Comment by s-u** [comment]
You got the options backwards - `opts` is for the S3 side and `...` is for your function, so it's as easy as

```r
s3write_using(iris, FUN = write.csv, object = "iris.csv", bucket = "some-bucket", row.names = FALSE)
```
