### ISSUE TITLE
Show progress on save_object()

### ISSUE THREAD

**Issue by jnolis** [cloudyr/aws.s3#309]
Looking at the documentation, I can see that put_object() has a show_progress option directly embedded in it. I'm having to download some very large objects, so I was hoping for something similar with save_object. I can see that httr has a `httr::progress()` function that can be passed to httr operations. While the `aws.s3::save_object()` has a `...` to take other httr parameters, I can't seem to successfully pass the progress function to it.

Is there a way to have save_object() show progress? Does it already exist and I can't figure it out?

Thank you! This package is great and is immensely useful for what I'm doing.

**Comment by s-u** [comment]
Did you try `save_object(..., show_progress=TRUE)`?
