### ISSUE TITLE
how to check if specific file exists in s3 bucket

### ISSUE THREAD

**Issue by tamuanand** [cloudyr/aws.s3#310]
Hi

I have a specific question - Let's say I have a file called tx2gene.csv in a S3 bucket - how do I use the cloudy3 aws.s3 library to do a check for if that file exists using R code.

`File: s3://<path_to_name>/tx2gene.csv`

Thanks,

**Comment by raymondben** [comment]
`get_bucket(prefix = "tx2gene.csv")` might work, it will return an empty list if the file does not exist. Otherwise `get_bucket()` to list everything in the bucket and check if tx2gene.csv is there.
