### ISSUE TITLE
Maximum number of possible API requests.

### ISSUE THREAD

**Issue by nicocriscuolo** [cloudyr/aws.s3#311]
Hello and thank you for this really useful package.

I created the AWS account and a new bucket, in which I stored a very small .rda file (few Kb). In my online shiny app, I added the code to load that .rda file every time the application is launched through the apposite website.

Is it possible to know if there is a limit of request that can be done through the R package on a daily basis? For example, let's suppose that 1000 thousands users per day (really more than I expect) will see the website. Will the aws.s3 loading function work for everyone or there is a specific limit based on the aws.S3 package?

If there is not such limitation, I think will just have to pay an amount of money based on the total number of request at the end of the month (even though my file is really small, and the AWS pricing is calculated per Gb).

Thank you for your availability.

**Comment by s-u** [comment]
There is no limit. The package cannot track requests, only AWS can.
