### ISSUE TITLE
Invalid token 

### ISSUE THREAD

**Issue by Deamoner** [cloudyr/aws.s3#315]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ X] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

Step 1: Install Library
install.packages("aws.s3", repos = c(cloudyr = "http://cloudyr.github.io/drat"))
Step 2: Load the aws.s3 library:
library("aws.s3",lib.loc="~/R/x86_64-pc-linux-gnu-library/3.5")
Step 3: Set Credentials 
Sys.setenv("AWS_ACCESS_KEY_ID" = "%acceessKey%", "AWS_SECRET_ACCESS_KEY" = "%accessSecret%”, ”AWS_DEFAULT_REGION" = "us-east-1","AWS_SESSION_TOKEN" = "mytoken")
Step 4: Use Library to load data: 
testfile <- get_object("s3://%bucket%/TestFile.txt")

but the InvalidToken error is always inplace of the file. Why would that be?

**Comment by s-u** [comment]
Likely your token is invalid. It works for me with valid token. Note that session tokens do expire.
