### ISSUE TITLE
Change time out time in get_bucket

### ISSUE THREAD

**Issue by JordanCuevas** [cloudyr/aws.s3#319]
I've been using aws.s3 to list the directory of a bucket and download files in the directory. Recently, something has changed on the internet connection of server that this is running on and any calls via get_bucket_df are timing out. The same command still works on my local machine which is on the same network, and I'm still able to interface with s3 from the server through python (boto3). My first step to troubleshoot this problem would be to change the timeout time for get_bucket_df, but I haven't been able to figure out how to do that. Is there an option in the command, or possibly a line of code I can modify in one of the dependencies to reach this goal? Sample code is below:

```R
## load package
library("aws.s3")

## code
> a <- get_bucket_df(bucket=s3_bucket, max=1, key=s3key, secret=s3_secret)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 10000 milliseconds with 0 out of 0 bytes received

## session info
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.3.20

loaded via a namespace (and not attached):
 [1] httr_1.4.1          compiler_3.6.0      R6_2.4.0            tools_3.6.0         base64enc_0.1-3     curl_4.0            Rcpp_1.0.1          aws.signature_0.5.0
 [9] xml2_1.2.1          digest_0.6.19    
```

**Comment by s-u** [comment]
Simply adding `timeout(30)` to the call should increase it to 30 seconds.

**Comment by jdonnell01** [comment]
Hello,

I am having a similar problem and adding a parameter (timeout) to the call does not seem to have any effect and simply adding timeout(30) results in the below error.

**Attempt 1 (No Apparent Effect):**
```
get_bucket(bucket = '<bucket-name>',
                         verbose = F,
                         check_region = F,
                         region = '<region>',
                         base_url = '<endpoint-url>',
                         timeout = httr::timeout(30),
                         max = Inf)
```

**Attempt 2 (Error):**
```
get_bucket(bucket = '<bucket-name>',
                         verbose = F,
                         check_region = F,
                         region = '<region>',
                         base_url = '<endpoint-url>',
                         httr::timeout(30),
                         max = Inf)
```

 Error in vapply(elements, encode, character(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 7

**Comment by JordanCuevas** [comment]
> Hello,
> 
> I am having a similar problem and adding a parameter (timeout) to the call does not seem to have any effect and simply adding timeout(30) results in the below error.
> 
> **Attempt 1 (No Apparent Effect):**
> 
> ```
> get_bucket(bucket = '<bucket-name>',
>                          verbose = F,
>                          check_region = F,
>                          region = '<region>',
>                          base_url = '<endpoint-url>',
>                          timeout = httr::timeout(30),
>                          max = Inf)
> ```
> 
> **Attempt 2 (Error):**
> 
> ```
> get_bucket(bucket = '<bucket-name>',
>                          verbose = F,
>                          check_region = F,
>                          region = '<region>',
>                          base_url = '<endpoint-url>',
>                          httr::timeout(30),
>                          max = Inf)
> ```
> 
> Error in vapply(elements, encode, character(1)) :
> values must be length 1,
> but FUN(X[[1]]) result is length 7

For what it's worth, I've since moved over to the botor package which appears to be more stable.

**Comment by jdonnell01** [comment]
@JordanCuevas thank you - were you ever able to enable a timeout with the AWS.S3 package?

**Comment by JordanCuevas** [comment]
> @JordanCuevas thank you - were you ever able to enable a timeout with the AWS.S3 package?

No, I ended up using the AWS CLI tool and calling it through system() commands in R.
