### ISSUE TITLE
Access to minio from within a docker

### ISSUE THREAD

**Issue by psobczyk** [cloudyr/aws.s3#326]
Please specify whether your issue is about:

 - [X] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

I try to run docker compose with minio and R on top of it. I am able to access minio using python library boto3, but there is an issue with aws.s3

Dockerfile:

```
FROM r-base

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  libcurl4-openssl-dev \
  libpq-dev \
  libssl-dev \
  libxml2-dev \
  libpq-dev \
  pkg-config \
  libgit2-dev

RUN R -e "install.packages(c('aws.s3', 'httr'))"

RUN apt-get install -y python3
RUN apt install -y python3-pip
RUN pip3 install boto3

COPY . ./
```

I build it with

`
docker build . -t segmentation
`

docker-compose.yml

```
version: '3'
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=miniominio"
    command: server /data

  model:
    image: segmentation:latest
    depends_on:
      - minio
```

I run interactively

```
docker-compose run model bash
```

And execute script

```R
library(aws.s3)

httr::with_verbose(bucketlist(verbose=T,  base_url = "http://minio:9000", key = "minio", secret = "miniominio", use_https = FALSE))
```

getting error:

```
Locating credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using default value for AWS Region ('us-east-1')
S3 Request URL: http://http://minio:9000/
Executing request with AWS credentials
Locating credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
Error in curl::curl_fetch_memory(url, handle = handle) :
  Could not resolve host: http
```

When I change endpoint to 127.0.0.1:9000 (which is where minio should be by default)

```R
Sys.setenv("AWS_ACCESS_KEY_ID" = "minio")
Sys.setenv("AWS_SECRET_ACCESS_KEY" = "miniominio")
Sys.setenv("AWS_S3_ENDPOINT" = "127.0.01:9000")

httr::with_verbose(bucketlist(verbose=T, base_url = Sys.getenv("AWS_S3_ENDPOINT"), use_https = FALSE))
```

I get different error:

```
Locating credentials
Checking for credentials in user-supplied values
Checking for credentials in Environment Variables
Using Environment Variable 'AWS_ACCESS_KEY_ID' for AWS Access Key ID
Using Environment Variable 'AWS_SECRET_ACCESS_KEY' for AWS Secret Access Key
Using default value for AWS Region ('us-east-1')
S3 Request URL: http://127.0.01:9000/
Executing request with AWS credentials
Locating credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('us-east-1')
Error in curl::curl_fetch_memory(url, handle = handle) :
  Failed to connect to 127.0.01 port 9000: Connection refused
```

Surprisingly it works in python with boto3

```
import boto3

AWS_ACCESS_KEY_ID='minio'
AWS_SECRET_ACCESS_KEY='miniominio'
endpoint = 'http://minio:9000'

session = boto3.Session(
                aws_access_key_id=AWS_ACCESS_KEY_ID,
                aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
           )
s3 = session.resource('s3', endpoint_url=endpoint)

list(s3.buckets.all())
```

 - the output of `sessionInfo()`

`
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bullseye/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] aws.s3_0.3.12

loaded via a namespace (and not attached):
 [1] httr_1.4.1          compiler_3.6.1      R6_2.4.1
 [4] tools_3.6.1         base64enc_0.1-3     curl_4.2
 [7] Rcpp_1.0.3          aws.signature_0.5.2 xml2_1.2.2
[10] digest_0.6.23
`

**Comment by psobczyk** [comment]
Simple solution:

I just had to remove "http://" from base_url 
This is somewhat strange behaviour but now it works :)

`httr::with_verbose(bucketlist(verbose=T,  base_url = "minio:9000", key = "minio", secret = "miniominio", use_https = FALSE))`

**Comment by psobczyk** [comment]
Still having an issue accessing buckets on minio

This works:
`httr::with_verbose(bucketlist(verbose=T, base_url = 'minio:9000', key = "minio", secret = "miniominio", use_https = FALSE))`

This does not
`httr::with_verbose(get_bucket(bucket = "prd-scored-users", verbose=T, base_url = 'minio:9000', key = "minio", secret = "miniominio", use_https = FALSE))`

I'm getting error:
```
Locating credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using default value for AWS Region ('us-east-1')
Checking bucket region using get_location('prd-scored-users')
Error in curl::curl_fetch_memory(url, handle = handle) :
  error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Which suggests that I'm trying to access something as if I'm trying to access https:// which should not be the case since I use flag `use_https = FALSE)`

**Comment by dbaston** [comment]
Seeing the same error message (error:1408F10B:SSL routines:ssl3_get_record:wrong version number)  trying to access [andrewgaul/s3proxy](https://github.com/gaul/s3proxy).

**Comment by dbaston** [comment]
Looks like the `use_https` isn't being honored when doing the region check: https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L79

So adding `check_region=FALSE` in addition to `use_https=FALSE` seems to be a suitable workaround.

**Comment by s-u** [comment]
`check_region=FALSE` should be the default so this is likely not relevant anymore. It could be argued that `check_region` should pass-through `use_https` but then regions are only used with AWS back-ends which enforce SSL so if someone needs this please file an explicit new issue.
