### ISSUE TITLE
Updating the description file without a valid email breaks the library

### ISSUE THREAD

**Issue by NickBenthem** [cloudyr/aws.s3#331]
Please specify whether your issue is about:

 - [x] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Put your code here:

```R
## load package
library("aws.s3")

## code goes here
# Not Applicable 

## session info for your system
sessionInfo()
```
```Downloading GitHub repo cloudyr/aws.s3@master

✔  checking for file ‘/private/var/folders/y1/_zzs2xzj5sx6x47gysqpxt9c0000gn/T/RtmpsbWUAC/remotes55ff7d8b92c2/cloudyr-aws.s3-c0c5d8d/DESCRIPTION’ ...
─  preparing ‘aws.s3’:
E  checking DESCRIPTION meta-information ...
   Authors@R field gives no person with maintainer role, valid email
   address and non-empty name.

   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.

Error: Failed to install 'aws.s3' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/y1/_zzs2xzj5sx6x47gysqpxt9c0000gn/T/RtmpsbWUAC/remotes55ff7d8b92c2/cloudyr-aws.s3-c0c5d8d/DESCRIPTION’ ... OK
E> * preparing ‘aws.s3’:
E> * checking DESCRIPTION meta-information ... ERROR
E> Authors@R field gives no person with maintainer role, valid email
E> address and non-empty name.
E>
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E>
```

**Comment by ryanb8** [comment]
The CRAN install still seems to work.

**Comment by acolum** [comment]
The CRAN install still works, and the issue in the DESCRIPTION meta-information on GitHub has been resolved. On my end, I've been able to install aws.s3 from GitHub.
@NickBenthem Can you confirm that the GitHub aws.s3 installation works on your end?
