### ISSUE TITLE
bucketlist() Bug

### ISSUE THREAD

**Issue by Timmyy22** [cloudyr/aws.s3#333]
Hi,

I am trying to read out all buckets I have access to: It is exactly one. Unfortunately bucketlist() returns a data frame with 2 lines: The first one is the name of the bucket, the second one is the creation time. 
While debugging I saw that s3HTTP(verb="GET") returns a list in a list with 2 Objects: Name and CreationDate. The bucketlist() function loops over them and puts them into 2 lines. Maybe the AWS API changed, but this is a bug. I am outgoing this with manually using s3HTTP(verb="GET")[[2]]$Name to get a list with all Names.

**Comment by s-u** [comment]
If the account has exactly one bucket, the data frame is incorrect:

```r
> bucketlist()
  c..nz.urbanek.test....2020.03.12T01.08.39.000Z..
1                                  nz.urbanek.test
2                         2020-03-12T01:08:39.000Z
```

This is due to the result not being a list of buckets:

```r
> r[["Buckets"]]
$Name
[1] "nz.urbanek.test"

$CreationDate
[1] "2020-03-12T01:08:39.000Z"

```

Special handling is needed for this case.
