### ISSUE TITLE
403 when using aws.s3_0.3.12.1 but not aws.s3_0.3.20

### ISSUE THREAD

**Issue by scott-mac** [cloudyr/aws.s3#334]
This one is driving me crazy. Two different machines, both WIN10, identical config, each running the same test script, the only difference seems to be the version of the aws.s3 package that is loaded. The machine that works is **aws.s3_0.3.20**  which I'm not even sure how I got that version as I don't see it anywhere in the builds and the latest seems to be **3_0.3.12.1**. I would have installed it as the default anyway.

`install.packages("aws.s3")`

All the requests work in the one but not the other, I get 403 "Access Denied". I doublechecked that my env variables were being set correctly on the failing machine and they're all there as expected. Was there a change in how those were named between versions or something? 

Can anyone point me to this phantom 3_0.3.20 build so I can try explicitly installing that?

**Comment by scott-mac** [comment]
I wanted to post an update to this as I was able to get the failing machine to work. Apologies, I'm still quite new to R so I didn't know where files were extracted to on install etc. What I did was on the machine that was working (the 3_0.3.20) to use the .libTools() command to find the location where it was putting the 3rd party libs. In the aws.s3/R directory there were 3 files (aws.s3, asw.s3.rdb, aws.s3.rdx). I copied those over to the machine that was throwing 403 errors and restarted my R session. It started working immediately. Hopefully this helps track the bug down, thanks

**Comment by douglascm** [comment]
Its not working for me as well, error 403 forbidden

**Comment by doorisajar** [comment]
Unfortunately it looks like 0.3.12.1 was the last version deployed to CRAN, so anyone who updated to it from 0.3.12 before it was delisted will have this problem. 

For now, my advice on a fix is to download the 0.3.12 tarball directly from the CRAN archive and install it locally yourself: 

https://cran.r-project.org/src/contrib/Archive/aws.s3/aws.s3_0.3.12.tar.gz

**Comment by s-u** [comment]
0.3.20 is now on CRAN so I assume this is now fixed

**Comment by doorisajar** [comment]
Tested and working with a fresh install from CRAN. Thanks!
