### ISSUE TITLE
CRAN availability

### ISSUE THREAD

**Issue by lorenzwalthert** [cloudyr/aws.s3#335]
According to [CRANberries](http://dirk.eddelbuettel.com/cranberries/2020/01/30/#aws.s3-0.3.12.1), this package was removed from CRAN on January 30, 2020. When do you think will this package be available from CRAN again? Thanks for all previous work on this package. Also note that insalling HEAD from GitHub currently fails because of a malformed DESCRIPTION: 

```
Error: Failed to install 'aws.s3' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> * checking for file ‘/tmp/RtmpmeI3Cl/remotes168046c1c5ba/cloudyr-aws.s3-c0c5d8d/DESCRIPTION’ ... OK
E> * preparing ‘aws.s3’:
E> * checking DESCRIPTION meta-information ... ERROR
E> Authors@R field gives no person with maintainer role, valid email
E> address and non-empty name.
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E> 
```

To make it work, I needed to install the latest commit that passed CI, like this 
```r
remotes::install_github('cloudyr/aws.s3@8c722f8e84ea9f645ea394ef0908cfc003251155')
```

**Comment by dkincaid** [comment]
Well, for some reason the package has been marked as "orphaned". Is there an alternative package for reading and writing files to S3?

https://github.com/cloudyr/aws.s3/commit/c0c5d8d9e292236183606022e9516bd20d3b29b5

**Comment by lianos** [comment]
@dkincaid there are two that I know of:

1. [botor](https://github.com/daroczig/botor): uses reticulate to wrap the python library
2. [paws](https://github.com/paws-r/paws)

**Comment by s-u** [comment]
Now back on CRAN
