### ISSUE TITLE
Invalid DESCRIPTION file makes the orphaned package uninstallable

### ISSUE THREAD

**Issue by tomsing1** [cloudyr/aws.s3#336]
Thank you so much for the hard work you put into the cloudyr packages.
Sorry to hear that you won't have time to maintain them, totally understandable, though.

You replaced the of the `DESCRIPTION` file with `ORPHANED`. Unfortunately, that makes the DESCRIPTION file invalid and it cannot be installed (from github).

If that was not your intention, e.g. if you would still like to allow users (like myself) you need a bit more time to find alternative solutions, to install the package(s), would you mind undoing that?

```
remotes::install_github("cloudyr/aws.s3")

Error : Invalid DESCRIPTION file

Authors@R field gives no person with maintainer role, valid email
address and non-empty name.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

**Comment by stewartthomasj** [comment]
You can fork the code by clicking on the fork icon to make copy in your own repo, then update DESCRIPTION to put it back to the contents from one of the earlier commits.

OR

You can just use the ref option to point to an earlier commit.

`install_github('cloudyr/aws.s3',ref='46aa3db34b89946205e6f27ce6f745cea4bf4571')`

**Comment by hrodmn** [comment]
How can we appoint a new maintainer? I am willing to help keep this package going but do not know how to join the project.

**Comment by dkincaid** [comment]
We probably can't at this point. We volunteered a year ago to help maintain some of these packages and never got any kind of response. Your best bet is to fork the repo and create your own copy you can use.

**Comment by andybega** [comment]
@hrodmn if you are willing to be the new maintainer, maybe try reopening https://github.com/cloudyr/aws.s3/issues/272? 

Since the package has been archived on CRAN maybe the bar is a bit lower now. It'd be great to keep it on CRAN even if there is not much active development/bug fixing (although that would of course be fantastic too).

**Comment by MarkEdmondson1234** [comment]
I'm sorry I was not monitoring this repo but I can give someone access to admin the package as a @cloudyr admin - who is still interested?  @hrodmn @dkincaid @antoine-sachet @acolum

**Comment by MarkEdmondson1234** [comment]
Tracking who wants to take over admin on this issue https://github.com/cloudyr/aws.s3/issues/339

**Comment by acolum** [comment]
The issue in the DESCRIPTION meta-information has been resolved, and this package can now be installed from GitHub.
