### ISSUE TITLE
Request to take over maintenance

### ISSUE THREAD

**Issue by s-u** [cloudyr/aws.s3#339]
Thomas, I'm offering to take over `aws.s3` and its dependencies (possibly others as well later) so they return back to CRAN.
Cheers,
Simon

**Comment by antoine-sachet** [comment]
Sounds like a good idea!

@MarkEdmondson1234 Sorry to keep pinging you but aws.s3 is one of cloudyr's most popular packages and it should really go back to CRAN. Especially since the package is not even installable in its current state (cf #336)

Regards - Antoine

**Comment by MarkEdmondson1234** [comment]
No problem, sorry I missed this before. Will add @s-u - many thanks for taking it on

**Comment by MarkEdmondson1234** [comment]
Hmm there is @acolum who is listed as an admin of this package as well, would like to get her input too (perhaps @leeper already gave access to her?)

**Comment by MarkEdmondson1234** [comment]
Track it on this issue - I can give someone access to admin the package as a @cloudyr admin - who is still interested?  @hrodmn @dkincaid @antoine-sachet @acolum

**Comment by acolum** [comment]
@MarkEdmondson1234 Leeper already gave access to me, and I'm fine with adding him as an admin. 

@s-u  I've sent you an invite to be an admin on this package.

**Comment by hrodmn** [comment]
I am happy to help out with the effort in a supporting role if that would be helpful to the new maintainers!

**Comment by s-u** [comment]
Ok, I don't want to be in a situation where there are too many cooks - the last merges didn't seem to be helpful to restore the package on CRAN which is really my priority. If you think you already have people who know what they are doing, I'm ok to back out.

**Comment by s-u** [comment]
@MarkEdmondson1234 please note that the issue is who will be the maintainer - that is a well-defined role by CRAN rules, it is separate from who has admin access (even though it's usually a good idea for the maintainer to have repo write access). After 922ff92 Thomas is back the maintainer - it that's the case, that would be great, but did he consent to that?

**Comment by antoine-sachet** [comment]
@acolum I must apologize, I didn't realise you were the maintainer since #272 and certainly did not mean to "kick you out"!

The maintainer must have the role "cre" in the DESCRIPTION file and will be the point of contact for CRAN. I assume Thomas orphaned the package because he was still listed as the maintainer.

If you are still interested in maintaining the package (in the CRAN sense of the word), please make it clear in the DESCRIPTION by giving you the "cre" role. If you're happy to help but no longer interested in being the official maintainer in the CRAN sense of the role, that's completely fine, just let us know :)

My main concern is also putting the package back on CRAN (see #335) which requires the consent of the maintainer and control of the listed email address.

**Comment by s-u** [comment]
@antoine-sachet thanks, I fully agree - that is the necessary requirement from the CRAN side. I would like to point that if @acolum was the maintainer since last November then the package has been made orphan months after she took over. We really need a clear position here - there has been very bad blood after maintenance take-overs of some packages in the past, so I would prefer if Thomas @leeper can make a clear statement. I am available if needed, but if we get someone else with experience in R I'm happy to play a supporting role.

**Comment by MarkEdmondson1234** [comment]
Don't count on Thomas commenting, he is out now and we should leave him to his green pastures :)  

It seems sorted to me now anyhow - @acolum and @s-u are admins, you can make the changes necessary to get the package back on CRAN.  I suggest moving Thomas' credentials to an Author role and for someone to take over the Creator/maintainer role.  CRAN really needs a stable email address so they know who to ask about to address any issues that may come up.

**Comment by acolum** [comment]
In the past several months, I’ve had some unexpected life events and started a Master’s degree while working full time, both of which have impacted my ability to work on this package. I don’t currently have the bandwidth to maintain this package, and I’d be happy if @s-u can take over as the maintainer.

**Comment by s-u** [comment]
@acolum thanks for the clarification. I'll do minor cleanup of the CI builds and push it back to CRAN. Then we can worry about issues and features. Thanks.
