### ISSUE TITLE
Source code without writing and reading from a temporary file

### ISSUE THREAD

**Issue by kaneplusplus** [cloudyr/aws.s3#342]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

Currently, to source remote code, the `s3source()` function gets the object, writes to a temporary file, sources the temporary file, and then unlinks the file. It would be simpler to simply source directly from the return of the `get_object()` function using a raw connection.

It should be noted that this is a minor issue. However, it does simplify the code slightly. Also, as a use case, we are running sensitive code on remote servers we do not own and have a policy that it may not be written to persistent storage, which the current function does.

**Comment by s-u** [comment]
Thanks!
