### ISSUE TITLE
Add path treatment function

### ISSUE THREAD

**Issue by jsameijeiras** [cloudyr/aws.s3#348]
I have a suggested code that I already implemented in my own version of this package. You can check [here](https://github.com/jsameijeiras/aws.s3/blob/path-treatment/R/s3_path.R)

The idea is to be able to read and write files using the path given by s3 of the format: s3://bucket/object.

Thus using the stringr::str_match() there is an easy way to go that is creating a function that separates bucket from the object and then it is pretty easy to implement in code. As an example, I am using this to zip a bunch of files and move them to another folder

As an example:

```R
move_file <- function(s3_input_path, s3_output_path) {
  
  input <- read_s3_path(s3_input_path)
  print(paste0("From File: ",input[2]," from bucket: ",input[1]))
  output <- read_s3_path(s3_output_path)
  print(paste0("To File: ",output[2]," and bucket: ",output[1]))
  
  file_to_move <- s3read_using(read_delim,
                               delim = ";",
                               object = input[2],
                               bucket = input[1])
  
  s3write_using(file_to_move,
                FUN = write_delim,
                delim = ";",
                na = "",
                object = paste0(output[2]),
                bucket = output[1])
  print(input[2],"uploaded to", output[1],output[2])
}

move_file("s3://bucket/tmp/file.csv","s3://new-bucket/notmp/file_zipped.csv.gz")
```
Another example is to use it when reading the file directly just like this:
```R
path <- "s3://bucket/example.json"
json_file <- s3read_using(read_delim, delim = ";", object = s3_path(path)[2],bucket = s3_path(path[1]))
```

**Comment by s-u** [comment]
This is already supported.
