### ISSUE TITLE
Region does automatically get added

### ISSUE THREAD

**Issue by bart1** [cloudyr/aws.s3#350]
I use the package to access a local minio server. This used to work fine but with the newest release I run into an issue where automatically a region gets added to every request. The example below I for example supply no region but then it falls back to the default region. This contrast to the `Readme.md` that says it should be fine to supply `region = ''` to work with other servers. Are there other ways to prevent regions being added to the request?

``` r
aws.s3::s3HTTP(key='asdf', secret='asdf', base_url='localServer.tld', verbose=T, region = '')
#> Locating credentials
#> Checking for credentials in user-supplied values
#> Using user-supplied value for AWS Access Key ID
#> Using user-supplied value for AWS Secret Access Key
#> Using default value for AWS Region ('us-east-1')
#> Non-AWS base URL requested.
#> S3 Request URL: https://us-east-1.localServer.tld/
#> Executing request with AWS credentials
#> Locating credentials
#> Checking for credentials in user-supplied values
#> Using user-supplied value for AWS Access Key ID
#> Using user-supplied value for AWS Secret Access Key
#> Using user-supplied value for AWS Region ('us-east-1')
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: us-east-1.localServer.tld
```

<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by s-u** [comment]
Can you clarify which version are you using? Older versions of `aws.s3` didn't support `region=""` but the current one here (0.3.21+) does.

**Comment by bart1** [comment]
Ah maybe that clarifies, It worked find (without region argument in 0.3.12, It fails with the current cran version, good to know it should work with the newest version

**Comment by bart1** [comment]
Just checked and it indeed works again with the newest version

**Comment by grthr** [comment]
can we get a release with this fix on CRAN?

**Comment by heathyates** [comment]
@s-u Do you know how I can work around region in the newest version? Specifically `aws.s3::bucketlist()` breaks for me now because it takes my endpoint url which should be `https://derp-herp.s3.com/` and does something like this `https://us-east-1.derp-herp.s3.com` which breaks my code because I am using NetApp S3 server technology.
