### ISSUE TITLE
How to use encryption with loading/extracting objects with aws.s3? 

### ISSUE THREAD

**Issue by heathyates** [cloudyr/aws.s3#352]
## Question 

I want to put and get objects from an S3 bucket. I want either the object or the s3 bucket to be encrypted so that others cannot read my objects. How can I do this? Thanks in advance for your patience given the n00b nature of this ask. 

## Challenge

I have read the aws.s3 documentation. There is a put/get/delete encryption method for buckets. However, it is unclear to me how this function can be used to secure my bucket so that only I can load/extract objects from the bucket. 

## Code 

Here is some (pseudo)code I have been using trying to attempt this problem. I have tried the get_encryption type api with aws.s3, but not sure if that is the right approach. 

```R
  ## load package
  library("aws.s3")
  library(datasets)

  sample_data <- datasets::AirPassengers 

  #How do I un-encrypt bucket or objects housed in the bucket? 

  #Here is how I rrite the data to the bucket 
    aws.s3::write_using(sample_data, 
                        FUN = "write.csv", 
                        object = "sample_data.csv", 
                        bucket = "my-bucket") 

    #How do I un-encrypt bucket or objects housed in the bucket? 

    #Here is how I read the code on the bucket
    asw.s3::get_bucket_df(bucket = "my-bucket") 
    aws.s3::s3read_using(read_csv, 
                         col_types = cols(.default = "c"), 
                         object = "sample_data.csv", 
                         bucket = "my-bucket")
```

## References 

I have consulted with the following references: 

- [aws.s3 documentation](https://cloud.r-project.org/web/packages/aws.s3/aws.s3.pdf) 
- [aws.s3 issues](https://github.com/cloudyr/aws.s3/issues) 

Thanks kindly in advance for any comments or suggestions.

**Comment by s-u** [comment]
@heathyates You can simply enable encryption in the AWS console on the bucket. The API to read/write doesn't change, as AWS is managing the encryption automatically using your credentials. Hence all of the above just works. We don't currently have an R function to do this (it's on the ToDo list), but you can use the following to enable `AES-256` encryption:

```r
s3HTTP(verb="PUT", bucket="myBucket", region="us-east-2", query=list(encryption=""),
  request_body='<?xml version="1.0" encoding="UTF-8"?>\n<ServerSideEncryptionConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">\n<Rule>\n<ApplyServerSideEncryptionByDefault><SSEAlgorithm>AES256</SSEAlgorithm></ApplyServerSideEncryptionByDefault>\n</Rule>\n</ServerSideEncryptionConfiguration>\n')
```

**Comment by s-u** [comment]
@heathyates the `*_encryption` functions enable/disable/change encryption. You don't need to change the code that accesses the content, S3 automatically handles the encryption/encryption based on the permissions on the bucket.

**Comment by heathyates** [comment]
Thanks for your reply. If I understand correctly, there are 2 ways to encrypt the bucket? 1) I can use the aws cli S3http() command. 2) I can use the aws.s3 put_encryption command? I am leaning towards aws cli, but wanted to clarify this. After I get this working, I will provide a status update here for the benefit of future users.

**Comment by s-u** [comment]
There are many ways to set the encryption on a bucket - via `aws s3` cli, via the AWS console, via the REST API, via `aws.s3::put_encryption()` ... Them ain point is that it's essentially just a flag on the bucket for AWS to encrypt the contents, the access doesn't change, the AWS servers are simply managing the key access and encryption/decryption automatically. The actual access is still governed by the policies you set.
