### ISSUE TITLE
aws.signature::locate_credentials() reporting wrong region

### ISSUE THREAD

**Issue by andrewcstewart** [cloudyr/aws.s3#357]
Hey there.  I may have encountered a bug.

While troubleshooting some access issues, I discovered that `aws.signature::locate_credentials()` is reporting my region as `us-east-1`, while I can verify that `us-east-1` appears no where in my `.aws` profile, any stray environment variables, Renviorn, etc.

**edit**: I should stress that my profile config explicitly sets my default region to `us-west-2`, which is the region I'd expect to see reported.

Please specify whether your issue is about:

 - [x] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

Put your code here:

```R
## load package
library("aws.s3")

## code goes here
aws.signature::locate_credentials()

$key
[1] "xxx"

$secret
[1] "xxx"

$session_token
NULL

$region
[1] "us-east-1"

## session info for your system
sessionInfo()

R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.9/lib/libopenblasp-r0.3.9.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3        aws.ec2metadata_0.2.0 tools_3.6.3           base64enc_0.1-3       curl_4.3              aws.signature_0.5.2   jsonlite_1.6.1       
[8] digest_0.6.25         packrat_0.5.0    
```

**Comment by s-u** [comment]
Wrong repo - `locate.credentials` in the [aws.signature](https://github.com/cloudyr/aws.signature) package, so please report there. However, please note that `us-east-1` is the default in AWS if you don't specify the region, so this is not a bug if you didn't specify a region in your `credentials` or otherwise.

**Comment by andrewcstewart** [comment]
Sorry about that @s-u - I was following a few different rabbit holes crisscrossing this and that repo while trying to troubleshoot my original error surfaced from `aws.s3`.  I'll repost there.

> However, please note that us-east-1 is the default in AWS if you don't specify the region, so this is not a bug if you didn't specify a region in your credentials or otherwise.

Thanks for the advice.  Yes, I am very much explicitly specifying `us-west-2` in as many areas as I can and in every test `locate.credentials` just ignores it.  Very strange.
