### ISSUE TITLE
Allow direct passage of key and secret into s3read_using()

### ISSUE THREAD

**Issue by ben519** [cloudyr/aws.s3#358]
Thanks for this awesome package. I'm currently using version 0.3.21 on R 4.0.0.

I would like the ability to pass my key and secret directly into `s3read_using()`, avoiding the need to create environment variables. For example, I want to do something like this

```
foo <- aws.s3::s3read_using(
      FUN = function(x) data.table::fread(x, na.strings = ""), 
      bucket = "my-bucket",
      object = "foo.csv",
      key = "abc",
      secret = "def"
    )
```

Currently this generates an "unused arguments" error because ... in the function gets passed on to FUN().

Thanks!

**Comment by s-u** [comment]
The syntax is

```r
foo <- aws.s3::s3read_using(
      FUN = data.table::fread, 
      na.strings = "",
      bucket = "my-bucket",
      object = "foo.csv",
      opts = list(key = "abc",  secret = "def")
    )
```
