### ISSUE TITLE
Headers argument in getobject function

### ISSUE THREAD

**Issue by jeledouget** [cloudyr/aws.s3#36]
Hi,
First, thanks guys for the package, which is working really fine.
I get stuck though because I am unable to use the 'headers' argument in getobject function.
The main use I see personnally is the ability to use Content-Length and Content-Range in order to download only a specified part of a file.
It  would be great if this feature could be implemented in aws.s3.
Thanks again
Jean-Eudes

**Comment by leeper** [comment]
Yes, we definitely need to fix this. Should be simple but for whatever reason we're currently not passing the `header` arguments to the API. I'll try to fix in the next few days.

**Comment by leeper** [comment]
@jeledouget I just pushed a change that should expose the header argument. Can you give it a try and report any problems you encounter?

**Comment by jeledouget** [comment]
@leeper Thanks very much !
It works. I was able to get the behaviour I was looking for. The following line returrns a binary object with the 120 first bytes of my data file :
foo <- getobject(myBucket, myObject, headers = list('Range' = 'bytes=1-120'))

**Comment by leeper** [comment]
@jeledouget Excellent! Glad to hear it. I'm making a note to enhance our documentation to describe how to use headers in this way.

- [ ] Describe extraction of partial files using `header` argument.
