### ISSUE TITLE
How to delete a folder in S3 using aws.s3 pacakge?

### ISSUE THREAD

**Issue by abdkumar** [cloudyr/aws.s3#361]
I tried getting all the files in the directory and delete it. But not helping, so I want to delete the folder. Is any method available in R?

```
files <- get_bucket(str_split[1], prefix = str_split[2])
  
  delete_files <- lapply(files, function(x) x[["Key"]])
  # Loop through file list
  for(file_to_delete in delete_files){
    delete_object(file_to_delete, 
                  str_split[1], 
                  prefix = str_split[[2]])
  }
```

**Comment by s-u** [comment]
S3 doesn't have a concept of folders. It is a flat structure and only by convenience names of the form `foo/bar` are interpreted as folders even though it is just a single string with no special meaning. So you simply delete all objects that you consider as being in a folder. Sometime people create a zero-length file to represent a folder, but, again, it's just an object like any other without any special meaning.

If you have any issues, please describe what exactly you have trouble with - why you think it's not doing what you intended so we can help.

**Comment by abdkumar** [comment]
I have bucket/my_folder/sub_folder/files . I want to delete the sub_folder and get just bucket/my_folder . how to do the same in R ?

**Comment by s-u** [comment]
```r
> (files <- unlist(lapply(get_bucket(bucket), `[[`, "Key"),, FALSE))
[1] "foo.zip"      "foo/bar/1"    "foo/bar/1/2"  "foo/bar/1/3"  "foo/bar/4"   
[6] "iris-dataset" "iris.csv"     "robots.txt"   "test.rds"    

> for (fn in files[grep("^foo/bar/.*", files)]) delete_object(fn, bucket)

> (files <- unlist(lapply(get_bucket(bucket), `[[`, "Key"),, FALSE))
> files
[1] "foo.zip"      "iris-dataset" "iris.csv"     "robots.txt"   "test.rds"    
```

The development version is adding vectorized versions so you shouldn't need to loop in the end and we can optimize the calls.
