### ISSUE TITLE
Enhance putobject to upload content in memory

### ISSUE THREAD

**Issue by mark-thompson** [cloudyr/aws.s3#37]
For those of us who'd like to avoid disk IO where possible.

It seems like this may already be the intended functionality, given https://github.com/cloudyr/aws.s3/blob/master/R/http.r#L117, but doing so now yields errors.

Perhaps there is a plan to implement this when objects are released, but this would be a fairly simple thing to implement now.

**Comment by leeper** [comment]
Thanks!

**Comment by mark-thompson** [comment]
Not a problem! Thank you for the package :)
