### ISSUE TITLE
s3read_using lasts forever reading a VCF file

### ISSUE THREAD

**Issue by HediaTnani** [cloudyr/aws.s3#370]
Hi,

Is there a way to speed the reading process of a VCF file from the 3kricegneome public s3 bucket?

Could this process be parallelized?

And how about reading many VCFs at the same time?

Thanks alot.

```R
## load package
library("aws.s3")

s3read_using(FUN = read.vcf, bucket = '3kricegenome', object = "9311/B183.snp.vcf.gz") 


## session info for your system
sessionInfo()
```

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS
i7 8Gb RAM

**Comment by s-u** [comment]
You may want to contact the author of `read.vcf`. `s3read_using` is just a shortcut for reading the object from S3 into a local temporary file and then calling the function, so there is nothing that can be done in parallel on the `aws.s3` side.
