### ISSUE TITLE
unit testing?

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.s3#4]
Is there a sensible way to go about unit testing (e.g. particularly for methods requiring keys?)  e.g. does AWS provide and testing endpoints with dummy credentials?  Or can we define some dummy credentials for testing purposes (e.g. create and then delete a file) and pass them encrypted to travis?

**Comment by almartin82** [comment]
doesn't look like there are any testing endpoints provided by aws ([source])(https://stackoverflow.com/questions/1375285/amazon-s3-developer-free-account-for-testing-purposes).  there's a [gem](https://github.com/jubos/fake-s3) that simulates s3 responses, but I can't imagine that adding a ruby dependency to travis is worth the overhead?  probably someone will need to generate a locked down set of keys, which can be entered into travis as [environment variables](http://docs.travis-ci.com/user/environment-variables/) or wercker as [protected variables](http://old-devcenter.wercker.com/articles/steps/variables.html).  I will volunteer - almartin at gmail, if you want to coordinate offline!

**Comment by almartin82** [comment]
OK, I added an encrypted aws key and secret to the travis build - we don't need to obfuscate the environment variable name that I used, correct?  I can reference that variable in tests?

wercker uses heroku-style environment variables that you set up via a web interface - haven't used the travis encryption before.

**Comment by cboettig** [comment]
Nice! Right, env var names should be fine.
