### ISSUE TITLE
Uploading Public FIles

### ISSUE THREAD

**Issue by rodrigomurta** [cloudyr/aws.s3#41]
Its possible to upload files with public policy?
Today, after upload the file, I have to go into the AWS interface to make it public.
I tried: `aws.s3::putobject("myFile", "myBucketPath", headers = c(ACL = "public-read"))`
Without success. The file is uploaded, but it's private.

**Comment by leeper** [comment]
@rodrigomurta, I believe the header name should be `"x-amz-acl"` not `ACL`.

**Comment by rodrigomurta** [comment]
@leeper tks! Yes, `"x-amz-acl"` is the correct way.

**Comment by leeper** [comment]
Great! I'm going to open a new issue to make it easier to pass these kinds of arguments.
