### ISSUE TITLE
Expand examples a bit

### ISSUE THREAD

**Issue by JackStat** [cloudyr/aws.s3#42]
I am trying to figure this package out and I am struggling.  Specifically, I was hoping to find some example code for the `s3save` and `s3load` functions.

For `s3save` do you just set up a bucket like so

    ex <- getbucket(
      bucket = 'test-bucket',
      key = "AWS-KEY",
      secret = "AWS-SECRET",
      region = 'us-west-2'
      )

and then use that bucket in the `s3save` function?

    s3save(mtcars, 
      bucket = ex
      , object = "mtcars"
      , opts = list(quote = FALSE))

It seems like I have to put something in opts or it errors out so I put in `quote = FALSE` so it could pass that to the do.call function.

When I run that I get
       No encoding supplied: defaulting to UTF-8.
but nothing shows up in the bucket.

Probably a stackoverflow question but I didn't see any other aws.s3 tagged questions there so I thought this would be a better spot for now

**Comment by leeper** [comment]
Thanks for opening this issue. I've just sent some updates related to this. I think this was a bug that should be fixed. Let me know if it is not working for you. I've added some trivial examples to the doc page for this.
