### ISSUE TITLE
README: Sys.getenv() must be Sys.setenv()

### ISSUE THREAD

**Issue by Dmitrii-I** [cloudyr/aws.s3#43]
In the code below, located in `README.md` file, `Sys.getenv()` should be `Sys.setenv()`:

`Sys.getenv("AWS_ACCESS_KEY_ID" = "mykey",
           "AWS_SECRET_ACCESS_KEY" = "mysecretkey",
           "AWS_DEFAULT_REGION" = "us-east-1")`

**Comment by leeper** [comment]
Thanks. Fixed now.
