### ISSUE TITLE
put_object() bug with s3 buckets that have "Bucket Owner Enforced" setting enabled.

### ISSUE THREAD

**Issue by alexmg64** [cloudyr/aws.s3#435]
- [x] a possible bug

```
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5

Matrix products: default
BLAS:   ***
LAPACK: ***

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.3.21
```

As described in the title, my org has an s3 bucket configured with "Bucket Owner Enforced" setting enabled (ACLs not allowed), which leads to HTTP 400 errors when using get_object().

Relevant portion of the error output:

> List of 4                                                                                                                           
>  $ Code     : chr "AccessControlListNotSupported"
>  $ Message  : chr "The bucket does not allow ACLs"
> 
> Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
>   Bad Request (HTTP 400).

The error seems to originate in this portion of the put_object() code:
`  if (!"x-amz-acl" %in% names(headers)) {
    if (!is.null(acl)) {
      acl <- match.arg(acl, c("private", "public-read", 
        "public-read-write", "aws-exec-read", "authenticated-read", 
        "bucket-owner-read", "bucket-owner-full-control"))
      headers <- c(headers, list(`x-amz-acl` = acl))
    }
    else {
      headers <- c(headers, list(`x-amz-acl` = "private"))
    }
  }`

Where `headers` is an empty list so the else{} block gets evaluated and headers is assigned `x-amz-acl` = "private". As a result, the API request to s3 fails in s3HTTP() at the end of put_object() because s3 buckets with "Bucket Owner Enforced" must make no explicit reference to ACLs. The 'x-amz-acl' = 'private' violates that requirement, so the 400 error occurs. 

When I reproduce my own bastardized version of put_object() that fully removes the `else {
      headers <- c(headers, list(`x-amz-acl` = "private"))` code, the API request is successful and the object is correctly put into s3 as expected.

**Comment by frosforever** [comment]
Less than ideal but does setting `acl = 'bucket-owner-full-control'` in `put_object` help you? That should be the same as setting no ACL for a bucket with ownership policy of `BucketOwnerEnforced`.

**Comment by alexmg64** [comment]
@frosforever not ideal but works just fine. Removing the line from me worked just the same, but explicitly setting `acl = 'bucket-owner-full-control'` is probably safer. Thanks for the tip!
