### ISSUE TITLE
`url` value different than "https://s3.amazonaws.com/"

### ISSUE THREAD

**Issue by chrisd31** [cloudyr/aws.s3#44]
This a question, not an issue.

s3HTTP() uses `url = "https://s3.amazonaws.com/"` when in default region. How can I use a different value like `"https://cgiardata.s3.amazonaws.com/"`?

**Comment by leeper** [comment]
This is a bug. I will try to fix shortly.

**Comment by leeper** [comment]
This should be fixed, so that you can do, e.g.: `getbucket("cgiardata")`. For this particular bucket you may need to do one of the following:

```R
getbucket("cgiardata", key = "")
getbucket("cgiardata", region = "us-west-2")
```

Let me know if it doesn't work for you.
