### ISSUE TITLE
Is it possible to download and load a CSV or other file from S3 into a data table

### ISSUE THREAD

**Issue by Eddolan** [cloudyr/aws.s3#45]
Currently I only see documentation for loading an R object or file into a vector.

**Comment by leeper** [comment]
If you have an .Rdata file in S3, you can use `s3load()` to load all of the objects into memory. If you have something like a CSV, you can use `get_object()` to get a raw vector representation and then either treat that as a rawConnection or convert to character with something like:

```R
read.csv(text = rawToChar(get_object("object", "bucket")))
```

**Comment by Eddolan** [comment]
Gotcha, I had issues playing around with get_object, but it seems the issue stems from not understanding that I needed to add the `region` parameter for S3 HTTP. I'll mark as resolved, but I would like to suggest making the error message here more meaningful. When I omit the `region` parameter on a bucket outside of US-standard for `get_object`, all I get is: `Error: is.response(x) is not TRUE`

**Comment by Eddolan** [comment]
And thanks!

**Comment by leeper** [comment]
@Eddolan Great. I've opened an issue for that (#46) as it should be reporting a standardized out-of-region error when that occurs. Thanks!
