### ISSUE TITLE
Read csv or excel file 

### ISSUE THREAD

**Issue by ElianoMarques** [cloudyr/aws.s3#55]
Hi, I'm trying to read csv or xlsx file from S3 directly using this package. 

I get the file but with a format that I can't understand. 

Do I need to do something different to get_object function to read csv. or xlsx files?

**Comment by leeper** [comment]
`get_object()` returns a raw vector, which is basically R's representation of the bytes that make up a file.

You can convert this into a `rawConnection()` to use in something like `read.csv()` or one of the Excel import packages. If it actually is a text file (like CSV), though, you can also do something like:

```R
obj <- get_object(...) # replace ... with actual code
read.csv(text = rawToChar(obj))
```

to very quickly get it into a data.frame.

**Comment by ElianoMarques** [comment]
Thank you.

**Comment by ElianoMarques** [comment]
Hi, I've tried with csv file and worked fine. But not with xlsx the rawConnection steps doesn't work. In this particular case I would have to persist the file extension as xlsx. Have you faced this issue ? 

```
r = aws.s3::get_object(bucket = "bucket",object = "object.xlsx")
data <- read.xlsx(file = rawConnection(r), sheetIndex = 1)
```
error message: 
```
Error in path.expand(file) : invalid 'path' argument
```

**Comment by leeper** [comment]
It looks like `read.xlsx()` requires a file path rather than a connection, so you'll be better of using `save_object()` to save the file locally and then read in from there. If you don't want to keep the file locally, you could use a temporary file:

```R
tmp <- tempfile(fileext = ".xlsx")
r <- aws.s3::save_object(bucket = "bucket", object = "object.xlsx", file = tmp)
data <- read.xlsx(file = tmp, sheetIndex = 1)
```

**Comment by ElianoMarques** [comment]
Thanks. working. I added as function on top of get_object and save_object, not sure if you want them so that you can add to your package?

**Comment by leeper** [comment]
If you want to share, go ahead and post them here. I'm inclined to keep this package pretty thin, but they might go nicely in a vignette or the README.

**Comment by aiyerganapathy** [comment]
Can anyone help me out with loading a .Rda file from S3? I am currently getting a raw vector of the file, after using `get_object()`.

**Comment by leeper** [comment]
@aiyerganapathy can you open a new issue please? You may also want to look at `s3load()` rather than calling `get_object()` directly.

**Comment by aiyerganapathy** [comment]
@leeper I am really sorry, I am new to posting comments in github issue, so didn't know the protocol. I will try the s3load() method.

**Comment by smirs** [comment]
how about `txt` files? I have difficulties using the same approach introduced above for csv, but for txt. Can you provide help please?
