### ISSUE TITLE
Write CSV into Amazon S3 bucket without storing it on local machine.

### ISSUE THREAD

**Issue by pruthvireddy** [cloudyr/aws.s3#56]
Can anyone help me on how to save a .csv file directly into Amazon s3 without saving it in local ?

- Save a data frame directly into S3 as a csv.

I tried this-

put_object(file = "sub_loc_imp.csv", object = "sub_loc_imp", bucket = "dev-sweep")

it popped an error-

Warning message:
In parse_aws_s3_response(r, Sig) : Forbidden (HTTP 403).

**Comment by leeper** [comment]
The easiest solution is just to save the .csv in a `tempfile()`, which will be purged automatically when  you close your R session.

If you need to only work in memory you can do this by doing `write.csv()` to a rawConnection:

```R
# write to an in-memory raw connection
zz <- rawConnection(raw(0), "r+")
write.csv(iris, zz)
r <- rawConnectionValue(zz)
close(zz) # close the connection

# upload the object to S3
aws.s3::put_object(file = r, bucket = "bucketname", object = "iris.csv")
```

In case you're unsure, you can then check that this worked correctly by downloading the object from S3 and reading it back into R:

```R
# check that it worked
## (option 1: save locally)
save_object(object = "iris.csv", bucket = "bucketname", file = "iris.csv")
read.csv("iris.csv")
## (option 2: keep in memory)
read.csv(text = rawToChar(get_object(object = "iris.csv", bucket = "bucketname")))
```

**Comment by pruthvireddy** [comment]
Hey Thomas,

Thanks for the reply, its a pretty neat solutions. Although I am still facing a problem (slightly unrelated).

This is how I got my bucket.

```
get_bucket(
  bucket = 'name,
  key = "xxx",
  secret = "xxx"
)

```
And this is how i am trying to push my csv.


```
# write to an in-memory raw connection
s3con <- rawConnection(raw(0), "r+")
write.csv(sub_ctr, s3con)
ctr_file <- rawConnectionValue(s3con)
close(s3con) # close the connection

# upload the object to S3
aws.s3::put_object(file = ctr_file, bucket = "name", object = "sub_ctr.csv")

```

it still gave an error

```
$Code
[1] "AccessDenied"

$Message
[1] "Access Denied"

Warning message:
In parse_aws_s3_response(r, Sig) : Forbidden (HTTP 403).

```


Is it the right way to establish connection to my bucket. Or am I totally wrong, is there another approach.
Please help Thomas.

**Comment by leeper** [comment]
That's usually a sign that you don't have access permission for the bucket. I would double check bucket name spelling, but also make sure you're specifying the bucket region if it's not `us-east-1` (which is the default).

**Comment by pruthvireddy** [comment]
Hey Thomas,

I did check my access with my devops, everything was fine there.

region is - us-east-1

was thinking the same, do I have to mention the region in the get_bucket()
? or do we use Amazon CLI and open a connection ?

On Thu, May 19, 2016 at 12:39 PM, Thomas J. Leeper <notifications@github.com
> wrote:

> That's usually a sign that you don't have access permission for the
> bucket. I would double check bucket name spelling, but also make sure
> you're specifying the bucket region if it's not us-east-1 (which is the
> default).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudyr/aws.s3/issues/56#issuecomment-220244708>
>



-- 
Thanks,
Pruthvi Reddy
Business Analyst - Practo Reach

-- 
_____________________________________________________
Download Practo App 
<http://go.onelink.me/1025359428?pid=Email&c=practoemailsignature>

**Comment by leeper** [comment]
If the bucket is in region `us-east-1`, you shouldn't need to mention it.

The other possibility is you have a bucket policy or object ACL in place that is preventing you from adding an object (or overwriting an existing object). You should be able to use `get_policy("bucketname")` to check if you have a policy in place.

**Comment by pruthvireddy** [comment]
Thanks Thomas, will try to dig deeper and find a solution, your solution of saving a CSV is very helpful.

**Comment by sdsifleet** [comment]
Was this ever resolved?

**Comment by leeper** [comment]
@sdsifleet If you're having a new or similar problem, can you please open a new issue with a reproducible example?

**Comment by abhishekupadhyaya** [comment]
I use Pandas to save data as csv. So, the following code works in saving data as csv file in S3 bucket without saving locally.
```
from io import BytesIO

csv_buffer = BytesIO()
csv_df.to_csv(csv_buffer, index=False)

s3client = boto3.client("s3")
response = s3client.put_object(
	Body=csv_buffer.getvalue(),
	ContentType='application/vnd.ms-excel',
	Bucket=bucket,
	Key=output_file_path,
)
```

_Note: csv_df is pandas dataframe object_

**Comment by lastobelus** [comment]
@abhishekupadhyaya correct me if I'm wrong (I'm looking for a streaming solution in ruby, and don't know python well) but is this not also constructing the entire csv object in memory before sending it?

**Comment by MohitPatelNYU** [comment]
Is there a way to save json object into csv file which is stored in s3 without downloading the csv file locally?

**Comment by abhishekshankar891** [comment]
Can any one help me with writing csv to zip file (.zip) and uploading to S3 bucket.Thanks

**Comment by s-u** [comment]
@abhishekshankar891 
```r
write.csv(foo, file="foo.csv")
zip("foo.zip","foo.csv")
aws.s3::put_object(file="foo.zip", bucket="myBucket")
```

**Comment by abhishekshankar891** [comment]
@s-u - Thanks simon for the quick response. I tried your solution but the file getting generated is of few bytes .,which seems not right .Can u provide any other approach .
Thanks

**Comment by s-u** [comment]
It works just fine for me:

```r
> foo=iris
> write.csv(foo, file="foo.csv")
> zip("foo.zip","foo.csv")
updating: foo.csv (deflated 77%)
> file.info("foo.zip")
        size isdir mode               mtime               ctime
foo.zip 1238 FALSE  644 2020-04-28 21:16:04 2020-04-28 21:16:04
> aws.s3::put_object(file="foo.zip", bucket="t1.urbanek")
[1] TRUE
> get_bucket("t1.urbanek","foo.zip")
Bucket: t1.urbanek 

$Contents
Key:            foo.zip 
LastModified:   2020-04-28T09:18:36.000Z 
ETag:           "a05f2f4eb2a7ce1044f31871b7b4460c" 
Size (B):       1238 
Owner:          urbanek 
Storage class:  STANDARD 
> unlink(c("foo.zip","foo.csv"))
> save_object("foo.zip", "t1.urbanek")
[1] "foo.zip"
> (unzip("foo.zip"))
[1] "./foo.csv"
> str(read.csv("foo.csv"))
'data.frame':	150 obs. of  6 variables:
 $ X           : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : chr  "setosa" "setosa" "setosa" "setosa" ...
```

**Comment by abhishekshankar891** [comment]
@s-u - Yes I am trying to do in Lambda function ,it seems you did the part in sagemaker . Sorry for the confusion . Hoping If u can help in that .Thanks
