### ISSUE TITLE
Signature validation error on keys with certain unsafe characters

### ISSUE THREAD

**Issue by PeterAttardo** [cloudyr/aws.s3#64]
We were seeing a signature validation error being returned from the save_object() and put_object() calls (and likely others we didn't test), but not on the get_bucket() call. Eventually I tracked it down to the fact that we have '=' in our keys (storing partitioned Hive tables on S3, so part of the path is '/product_id=1/date=2016-01-01/' for example). get_bucket() puts the prefix in the query parameter, which ends up somewhere in the body of the request; whereas save_object() and put_object() put the key in the path parameter, which then gets appended to the url of the request itself. Manually URL encoding the '=' symbol with '%3D' fixed the issue on the previously failing calls, but for API cleanliness it might be something worth having the library itself handle.

**Comment by leeper** [comment]
I'll take a look. Sounds like we should probably just automatically escape object keys. Should be a simple fix.

**Comment by reinholdsson** [comment]
We have the same issue (`SignatureDoesNotMatch`) with save_object() when s3 path include `=`.
