### ISSUE TITLE
get_torrent.Rd : Permission denied

### ISSUE THREAD

**Issue by 30ps** [cloudyr/aws.s3#66]
Hello,

I am trying to install the aws.s3 library in R but i am getting the following error:

> install.packages("aws.s3", repos = c("cloudyr" = "http://cloudyr.github.io/drat"), INSTALL_opts = "--no-multiarch")
installing the source package ‘aws.s3’

trying URL 'http://cloudyr.github.io/drat/src/contrib/aws.s3_0.1.28.tar.gz'
Content type 'application/octet-stream' length 26103 bytes (25 KB)
downloaded 25 KB

Warning in file(name, "wb") :
  cannot open file 'aws.s3/man/get_torrent.Rd': Permission denied
Error in file(name, "wb") : cannot open the connection
Warning in install.packages :
  running command '"C:/Users/511316/DOCUME~1/R/R-33~1.1/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\511316\Documents\R\R-3.3.1\library" C:\Users\511316\AppData\Local\Temp\RtmpqMMtwR/downloaded_packages/aws.s3_0.1.28.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘aws.s3’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\511316\AppData\Local\Temp\RtmpqMMtwR\downloaded_packages’
> library(aws.s3)
Error in library(aws.s3) : there is no package called ‘aws.s3’

Is there a workaround this problem?

Thanks

**Comment by leeper** [comment]
I am not able to reproduce this. Can you try again to just ensure this wasn't a fluke?
