### ISSUE TITLE
aws.s3 installation fails due to Windows line breaks in configure file

### ISSUE THREAD

**Issue by AitorF** [cloudyr/aws.s3#69]
The command `install.packages("aws.s3", repos = c(cloudyr = "http://cloudyr.github.io/drat"))`
fails with the message:

> sh: ./configure: /bin/bash^M: bad interpreter

due to Windows line breaks in ./configure file. Removing line breaks and executing ./configure manually runs the script.

**Comment by leeper** [comment]
Are you on OS X?

**Comment by AitorF** [comment]
Red hat

**Comment by leeper** [comment]
If this issue is still affecting you, please try to reinstall **xml2** from CRAN and open a new issue if this doesn't work.
