### ISSUE TITLE
functions print region name

### ISSUE THREAD

**Issue by RoyalTS** [cloudyr/aws.s3#70]
Perhaps I'm using the package wrong but when I run

    put_object(file = 'file.txt',
               object = 'file.txt',
               bucket = credentials[['BUCKET_NAME']],
               region = credentials[['AWS_DEFAULT_REGION']],
               key = credentials[['AWS_ACCESS_KEY_ID']],
               secret = credentials[['AWS_SECRET_ACCESS_KEY']])

I see

    [1] "eu-central-1"
    [1] TRUE

printed in the console. The second of these is what the function actually returns. The first seems to be something that's printed inside the function. Is there any way suppress this print?

**Comment by leeper** [comment]
I think that was an accidental inclusion of an earlier debugging effort. Are you using the latest version from GitHub?

**Comment by RoyalTS** [comment]
Ah, the one removed in a8fa247ac95315a3ad7e8e9d5d02d618fe1fd0f6, I guess? Will install the latest version then. Thanks!

**Comment by leeper** [comment]
Indeed.

**Comment by RoyalTS** [comment]
That did the trick. Thanks!
