### ISSUE TITLE
Issue while installing aws.s3 package ubuntu

### ISSUE THREAD

**Issue by mart1mas** [cloudyr/aws.s3#72]
Hello,
While installing aws.s3 package through R console I am getting the following error log :

```

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xml2’ 1.0.0 is being loaded, but > 1.0.0 is required
ERROR: lazy loading failed for package ‘aws.s3’

```

Do you have any suggestion ?

Thank you for your help

Martin

**Comment by leeper** [comment]
You need the development version of xml2 from github. Try: `ghit::install_github("hadley/xml2")` or `devtools::install_github("hadley/xml2")`
