### ISSUE TITLE
customize URL

### ISSUE THREAD

**Issue by dancohen21** [cloudyr/aws.s3#74]
Amazon S3 API becoming a de facto standard interface for cloud storages and many hosting providers allow you to connect to their storages using s3-compatible APIs. Some examples are: Virtustream, Dreamhost, HostEurope, Dunkel Storage, Eucalyptus/Walrus as well as many others.

In order to connect to s3-compatible storage you need the following details:
    Access Key Id - also known as a username.
    Secret Access Key - also known as a password.
    REST Endpoint (an API endpoint) - an address used to send requests to, it is usually provided with the username and password, it can also be found in storage documentation or obtained from the support. 

Please Add an optional parameter to specify the endpoint URL

**Comment by leeper** [comment]
It's not currently within the scope of this package to support other cloud services. If you want to provide a pull request that modifies the code to make it more generally useful, I will consider it but it is not a priority for me.
