### ISSUE TITLE
max 1000 items returned by get_bucket

### ISSUE THREAD

**Issue by hennar** [cloudyr/aws.s3#75]
I need to return > 1000 items from a get_bucket request. Is there a way I can implement this?

**Comment by leeper** [comment]
You can use the `marker` argument. See [the API documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) if it's unclear:

> Specifies the key to start with when listing objects in a bucket. Amazon S3 returns object keys in UTF-8 binary order, starting with key after the marker in order.

You should be able to just specify the name of the last object key returned, like `get_bucket("bucket", marker = "filename.whatever")`.

Let me know if that doesn't work.
