### ISSUE TITLE
Save/load a list of object names

### ISSUE THREAD

**Issue by berdaniera** [cloudyr/aws.s3#76]
I use aws.s3 with shiny and would like to programmatically access user-selected files.

If I pass a variable name into s3save() and s3load() it tries to find an object with that name, not the value assigned to the name. For example:

``` r
myobject <- data.frame(var1=c(1,2,3))
varname <- "myobject"
s3save(varname, object="myobject.Rda", bucket="mybucket")
```

does not save myobject.

The base save() has an option to "list" the character names of the objects. As another implementation, library() has a "character.only" option.

**Comment by leeper** [comment]
Is it not possible to pass `myobject` as an object? I imagine you could do something like `s3save(get(varname), object="myobject.Rda", bucket="mybucket")` to achieve that.
