### ISSUE TITLE
Trouble getting up & running: "Couldn't Resolve Host Name"

### ISSUE THREAD

**Issue by inquotes** [cloudyr/aws.s3#77]
I've recently launched an instance, installed rstudio server, uploaded a sample file to my s3 account. I'm fairly new to this, but I have been able to successfully read in some data from my s3 bucket using RCurl package. I came across cloudyr/aws.s3 when I was struggling to write data back to my s3 bucket.

I've installed everything correctly as far as I can tell (devtools, aws.s3, and I believe the development version of xml2) but I continue to run into this error:

`sys.setenv(my access key and secret and region)`
`get_bucket(bucket = '1000genomes')`
`Error in curl::curl_fetch_memory(url, handle = handle) :`
`Couldn't resolve host name`

What causes this issue? I'm not sure if it is aws.s3 or my configuration of my instance & s3 bucket, and I'm not expert enough to really know where to investigate next.  Any guidance would be appreciated so I can stop banging my head against the wall.

**Comment by leeper** [comment]
Can you include the output of `sessionInfo()` for me?

**Comment by inquotes** [comment]
Absolutely:
 `>session_info()`
`Session info ------------------------------------------------------------`
` setting  value                       `
` version  R version 3.2.2 (2015-08-14)`
` system   x86_64, linux-gnu           `
` ui       RStudio (0.99.903)          `
` language (EN)                        `
` collate  en_US.UTF-8                 `
` tz       <NA>                        `
` date     2016-10-28                  `
`   								   `
`Packages ----------------------------------------------------------------`
` package       * version    date       source                         `
` aws.s3        * 0.1.30     2016-10-28 Github (cloudyr/aws.s3@0a99733)`
` aws.signature   0.2.5      2016-08-09 cran (@0.2.5)                  `
` base64enc       0.1-3      2015-07-28 cran (@0.1-3)                  `
` curl          * 2.2        2016-10-21 CRAN (R 3.2.2)                 `
` devtools      * 1.12.0     2016-06-24 CRAN (R 3.2.2)                 `
` digest          0.6.10     2016-08-02 CRAN (R 3.2.2)                 `
` httr          * 1.2.1      2016-07-03 CRAN (R 3.2.2)                 `
` memoise         1.0.0      2016-01-29 CRAN (R 3.2.2)                 `
` R6              2.2.0      2016-10-05 CRAN (R 3.2.2)                 `
` Rcpp            0.12.7     2016-09-05 CRAN (R 3.2.2)                 `
` withr           1.0.2      2016-06-20 CRAN (R 3.2.2)                 `
` xml2          * 1.0.0.9001 2016-10-28 Github (hadley/xml2@86f8939)   `


Thanks you!

**Comment by inquotes** [comment]
Sorry here is the real sessionInfo() format you requested:
`R version 3.2.2 (2015-08-14)`
`Platform: x86_64-redhat-linux-gnu (64-bit)`
`Running under: Amazon Linux AMI 2016.09`

`locale:`
` [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              `
` [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    `
` [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   `
` [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 `
` [9] LC_ADDRESS=C               LC_TELEPHONE=C            `
`[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       `

`attached base packages:`
`[1] stats     graphics  grDevices utils     datasets  methods   base  `   

`other attached packages:`
`[1] httr_1.2.1      curl_2.2        xml2_1.0.0.9001 aws.s3_0.1.30  `
`[5] devtools_1.12.0`

`loaded via a namespace (and not attached):`
`[1] R6_2.2.0            tools_3.2.2         base64enc_0.1-3    `
`[4] withr_1.0.2         rstudioapi_0.6      Rcpp_0.12.7        `
`[7] aws.signature_0.2.5 memoise_1.0.0       digest_0.6.10      `

**Comment by rmenke-prosper** [comment]
We are having the same exact issue?

**Comment by leeper** [comment]
Are you setting a default region? The examples may not work without specifying an explicit `region` argument in every call, or setting the default region to `us-east-1`.

**Comment by rmenke-prosper** [comment]
I'm setting my default region with this command:

Sys.setenv("AWS_ACCESS_KEY_ID" = "mykey", 
           "AWS_SECRET_ACCESS_KEY" = "mysecret", 
           "AWS_DEFAULT_REGION" = "us-west-1")

**Comment by leeper** [comment]
@rmenke-prosper You appear to be using a very old version of **curl**. I would recommend running `update.packages()` and trying again.

**Comment by rmenke-prosper** [comment]
Still no luck, even with updated curl package.
`> s3save(test, bucket = "hadoopdatapipe/dm/dm-test/", object = "dm-test3.Rdata")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.2 (Maipo)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.1.26 curl_2.2      RJDBC_0.2-5   rJava_0.9-8   DBI_0.5-1    

loaded via a namespace (and not attached):
[1] httr_1.2.1          R6_2.2.0            tools_3.3.0         base64enc_0.1-3     Rcpp_0.12.7         aws.signature_0.2.5 xml2_1.0.0          digest_0.6.10 `

**Comment by leeper** [comment]
Do you get that error only with that bucket or in general? Bucket name with /s in them are probably not a good idea, if you can avoid them.

**Comment by inquotes** [comment]
I'm closing this issue as I was able to get connected to s3 & read in bucket names, etc.

**Comment by seunaa** [comment]
Hi @inquotes @leeper @rmenke-prosper could you please share how you have worked around this problem? I am having the same issue. Thanks

**Comment by siimleetberg** [comment]
Hi,

Had the same issue with one specific bucket in `eu-west-1` region. After digging around in the aws.s3 code I managed to switch on verbose mode and found out that the particular bucket region is reported to be `EU` instead of `eu-west-1` and AWS says this is expected behaviour.

`> get_bucket("bucket-name", region = "eu-west-1", verbose = T)
Checking bucket region using get_location('bucket-name')
Executing request using bucket region EU
S3 Request URL: https://s3-EU.amazonaws.com/bucket-name/
Executing request with AWS credentials
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name`

The problem is that `aws.s3`  uses bucket specific region instead of the one defined explicity, but you can disable it. See [](https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L50)
The workaround for this is
`get_bucket("bucket-name", region = "eu-west-1", verbose = T, check_region = F)`

**Comment by seunaa** [comment]
@siimleetberg thanks a lot for sharing this. I was able to try you suggestion today. after passing access key and secret access key to the Sys.setenv function, I used your get_bucket code snippet (adding the check_region = F) and that solved the issues.

**Comment by SujuanWu** [comment]
@leeper  Hello Leeper, I also met the same issue, and I also try to run  " get_bucket("mybucket", region = "cn-north-1",check_region = F)"    or  "get_bucket("mybucket", region = "cn-north-1",verbose = T)", the error still appeared. 
<img width="398" alt="image" src="https://github.com/cloudyr/aws.s3/assets/143523384/10c95ba3-0ae1-4517-8021-e860b5e899f2">
 my session infor is below:
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:   /opt/R/R_4.0.2/lib64/R/lib/libRblas.so
LAPACK: /opt/R/R_4.0.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.3.21

loaded via a namespace (and not attached):
 [1] httr_1.4.7          compiler_4.0.2      R6_2.5.1            tools_4.0.2         base64enc_0.1-3     curl_5.0.2          aws.signature_0.6.0
 [8] xml2_1.3.5          digest_0.6.27       renv_0.14.0
