### ISSUE TITLE
load credentials from .aws/credentials file

### ISSUE THREAD

**Issue by JanLauGe** [cloudyr/aws.s3#78]
Hello!
First of all, thanks for a great package that is making my life so much easier! Keep up the good work!

Enhancement suggestion:
Using this package, for a while I 'hard-coded' my AWS credentials into the code. This is hardly ideal so instead I started reading them from the .aws/credentials file. I have working code for this, would that be of interest to the community?

Happy to put in a pull request, but as per CONTRIBUTING.md I thought I'd bring this up here first.

Cheers!

**Comment by leeper** [comment]
Thanks. This is already a supported feature in the underlying package that handles credentials. See here: https://github.com/cloudyr/aws.signature

**Comment by JanLauGe** [comment]
Haha, oops!
Thanks for clarifying :)
