### ISSUE TITLE
R Version

### ISSUE THREAD

**Issue by rossvoorhees** [cloudyr/aws.s3#79]
I tried to install the package and am getting the message that it won't run on R version 3.2.2
Which version is required for this package?

**Comment by leeper** [comment]
Can you provide the exact error?

**Comment by rossvoorhees** [comment]
Sure.

Warning in install.packages :
  package ‘aws.s3’ is not available (for R version 3.2.2)

**Comment by leeper** [comment]
How are you trying to install this? The package is not on CRAN, so you need to use `install_github()`. Is that what you're doing?

**Comment by rossvoorhees** [comment]
I tried this as suggested. 
install.packages("aws.s3", repos = c("cloudyr" = "http://cloudyr.github.io/drat"))

Then I get this error which appears its looking for a version of xml2. What's interesting is the package version is the one its looking for.
* R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'xml2' 1.0.0 is being loaded, but > 1.0.0 is required
ERROR: lazy loading failed for package 'aws.s3'
* removing 'C:/Program Files/R/R-3.2.2/library/aws.s3'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.2.2\library" C:\Users\RVOORH~1\AppData\Local\Temp\4\Rtmp8UDjMy/downloaded_packages/aws.s3_0.1.30.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘aws.s3’ had non-zero exit status

**Comment by leeper** [comment]
Try installing the xml2 package first. You'll need the development version from GitHub

```R
install_github("hadley/xml2")
```

**Comment by rossvoorhees** [comment]
Thanks! I was finally able to get aws.s3 installed. There were quite a few dependencies on the version of R and installing specific packages. I found that R version 3.2.3 and rTools 3.3  was the winning combination.
