### ISSUE TITLE
TRUE When I use put_object() with nothing being saved to S3

### ISSUE THREAD

**Issue by inquotes** [cloudyr/aws.s3#82]
Hello again,

From a closed thread I found this code as a solution to saving CSVs to S3 without saving it locally...I tried following this. When I run `put_object` commend I get a "TRUE" value returned but nothing shows up in the S3 bucket I specified. I tried saving the CSV to my EC2 instance and _then_ using put_object and got the same "TRUE" value but no new file saved.

I'm not receiving any errors and I don't believe this is a policy issue as I have set the policy on the bucket to allow for put, get and delete objects.

Are there any more examples of the put_object function at work beyond what is in the readme?

Thanks!

```# write to an in-memory raw connection
zz <- rawConnection(raw(0), "r+")
write.csv(iris, zz)

# upload the object to S3
aws.s3::put_object(file = rawConnectionValue(zz), bucket = "bucketname", object = "iris.csv")

# close the connection
close(zz)```

**Comment by leeper** [comment]
So the short-term fix is just to make sure you're specifying the correct bucket region in your request.

**Comment by leeper** [comment]
This should now issue an error.
