### ISSUE TITLE
Convert s3_bucket$Size to number

### ISSUE THREAD

**Issue by nqbao** [cloudyr/aws.s3#83]
The current type of s3_bucket$Size is character. Should we convert it to number for convenient?

For example in my use case i need to check for the size and compare it with local existing file.

**Comment by leeper** [comment]
Good idea. Should be simple to add an `as.numeric()` conversion line here: https://github.com/cloudyr/aws.s3/blob/master/R/BUCKET.R#L39-L42

**Comment by leeper** [comment]
I've just patched this. It will now return a numeric.

**Comment by nqbao** [comment]
Great, i will use the latest master now.
