### ISSUE TITLE
Throw error when it fails to save_object / put_object

### ISSUE THREAD

**Issue by nqbao** [cloudyr/aws.s3#86]
The current behavior is whenever there is a failure, the `aws_error` class is return. Can we make this behavior more strict, like using `stop` instead.

Right now i have to do something like this to check whether an action is successful or not. 

```
        r = save_object(item$Key, bucket = s3InputBucket, file = localAbsPath)

        if (class(r) == "aws_error") {
            cat(paste("Download error, code = ", r$Code, "message = ", r$Message))
            stop()
        }
```

We can also mimic the behavior of `dir.create` when `showWarnings` is set, the `aws_error` is returned instead.

**Comment by leeper** [comment]
Yes, good idea. Behavior should be consistent across functions, though, so I'll have to make changes in quite a few places.

**Comment by nqbao** [comment]
I can also help with that

**Comment by elinw** [comment]
This is really the same thing as on my issue, I was thinking that maybe it would make sense to consistently use tryCatch() on those places where aws_error is a possbility.

**Comment by elinw** [comment]
Do you want help with that?

**Comment by leeper** [comment]
I've modified the entire package to generate errors rather returning error objects. And with that breaking change, there's a bump to v0.2.0.
