### ISSUE TITLE
get_bucket doesn't handle second and subsequent CommonPrefix response correctly

### ISSUE THREAD

**Issue by sz-cgt** [cloudyr/aws.s3#88]
Calling `get_bucket()` with a delimiter often results in more than one CommonPrefix element in the response.  These end up as multiple elements in the response list, each with the same name.  Because the CommonPrefix elements are returned as attributes of the returned object, this means only one is ever included.

The following patch fixes that, returning a vector of values for the CommonPrefix attribute instead.

```
diff --git a/R/BUCKET.R b/R/BUCKET.R
index a203800..048f2ee 100644
--- a/R/BUCKET.R
+++ b/R/BUCKET.R
@@ -43,6 +43,9 @@ get_bucket <- function(bucket,
         }
         att <- r[names(r) != "Contents"]
         r[names(r) != "Contents"] <- NULL
+        cp <- att[names(att) == "CommonPrefixes"]
+        att[names(att) == "CommonPrefixes"] <- NULL
+        att$CommonPrefixes <- as.character(cp)
         out <- structure(r, class = "s3_bucket")
         attributes(out) <- c(attributes(out), att)
     }

```

**Comment by leeper** [comment]
Thanks. I will try to incorporate soon.
