### ISSUE TITLE
memCompress Error on s3saveRDS

### ISSUE THREAD

**Issue by jaguerrero77** [cloudyr/aws.s3#89]
Hello,

I have experienced a problem when using s3saveRDS with large files (around 200Mb). Here is the error:

> Error in memCompress(from = serialize(x, connection = NULL), type = "gzip") : 
>   long vectors not supported yet: connections.c:5942

The function is working ok for smaller files (50Mbytes), however it systematically fails on large ones.
I have seen a similar issue, but related to the read counterpart.
Any ideas /workaround to this?
Thanks in advance!

**Comment by leeper** [comment]
I think this is a fundamental R issue. If you save the object to disk first, you may be able to get around this by calling `put_object()`. If not, it's probably not possible without implementing multi-part uploads (https://github.com/cloudyr/aws.s3/issues/80).

**Comment by leeper** [comment]
Merging with #59
