### ISSUE TITLE
install fails on Win10-64bit to include dependencies, manual install of dependencies works and then install works

### ISSUE THREAD

**Issue by davidpitkin** [cloudyr/aws.s3#90]
I am running Windows 10, 1607 (OS Build 14393.576), 

R version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch       

> install.packages("aws.s3", repos = c("cloudyr" = "http://cloudyr.github.io/drat"), INSTALL_opts = "--no-multiarch")
Installing package into ‘C:/Users/David/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependencies ‘httr’, ‘base64enc’, ‘curl’ are not available
also installing the dependencies ‘xml2’, ‘aws.signature’

trying URL 'http://cloudyr.github.io/drat/bin/windows/contrib/3.3/xml2_1.0.0.9000.zip'
Content type 'application/zip' length 1732124 bytes (1.7 MB)
downloaded 1.7 MB

package ‘xml2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\David\AppData\Local\Temp\RtmpeGLmSa\downloaded_packages
installing the source packages ‘aws.signature’, ‘aws.s3’

trying URL 'http://cloudyr.github.io/drat/src/contrib/aws.signature_0.2.6.tar.gz'
Content type 'application/octet-stream' length 10245 bytes (10 KB)
downloaded 10 KB

trying URL 'http://cloudyr.github.io/drat/src/contrib/aws.s3_0.1.34.tar.gz'
Content type 'application/octet-stream' length 27417 bytes (26 KB)
downloaded 26 KB

ERROR: dependency 'base64enc' is not available for package 'aws.signature'
* removing 'C:/Users/David/R/win-library/3.3/aws.signature'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\David\R\win-library\3.3" C:\Users\David\AppData\Local\Temp\RtmpeGLmSa/downloaded_packages/aws.signature_0.2.6.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘aws.signature’ had non-zero exit status
ERROR: dependencies 'httr', 'base64enc', 'curl', 'aws.signature' are not available for package 'aws.s3'
* removing 'C:/Users/David/R/win-library/3.3/aws.s3'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\David\R\win-library\3.3" C:\Users\David\AppData\Local\Temp\RtmpeGLmSa/downloaded_packages/aws.s3_0.1.34.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘aws.s3’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\David\AppData\Local\Temp\RtmpeGLmSa\downloaded_packages’

I installed base64enc, httr, curl, and aws.signature from the Rstudio Install prompt and it then worked.

> install.packages("aws.s3", repos = c("cloudyr" = "http://cloudyr.github.io/drat"), INSTALL_opts = "--no-multiarch")
Installing package into ‘C:/Users/David/R/win-library/3.3’
(as ‘lib’ is unspecified)
installing the source package ‘aws.s3’

trying URL 'http://cloudyr.github.io/drat/src/contrib/aws.s3_0.1.34.tar.gz'
Content type 'application/octet-stream' length 27417 bytes (26 KB)
downloaded 26 KB

* installing *source* package 'aws.s3' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (aws.s3)

The downloaded source packages are in
	‘C:\Users\David\AppData\Local\Temp\RtmpeGLmSa\downloaded_packages’
>

**Comment by leeper** [comment]
So you got it working in the end?

**Comment by davidpitkin** [comment]
Yes, worked in the end.
