### ISSUE TITLE
Can't install aws.s3 package on OS X, wants xml2 > 1.0.0 but that's the latest on CRAN

### ISSUE THREAD

**Issue by davidpitkin** [cloudyr/aws.s3#92]
From the aws.s3 installer on Mac OS X 10.10, R 3.3.2

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xml2’ 1.0.0 is being loaded, but > 1.0.0 is required
ERROR: lazy loading failed for package ‘aws.s3’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/aws.s3’

Latest on CRAN is 1.0.0 https://cran.r-project.org/web/packages/xml2/index.html

**Comment by nqbao** [comment]
You will need to use the development version of `xml2` package. Try the following command.

`devtools::install_github("hadley/xml2")`

**Comment by leeper** [comment]
**xml2** has been updated on CRAN, so this should be resolved within a day or so (once Windows binaries are built by the CRAN team).
