### ISSUE TITLE
GZ / Compressed Files & Get_Object

### ISSUE THREAD

**Issue by inquotes** [cloudyr/aws.s3#94]
I am able to successfully read in my buckets, and CSV files from those buckets, but I've run into a scenario where I will need to decompress a few csv.gz files as well.

When I use get_object on this type of file, I receive an atomic data type, no longer a raw type. I was hoping to use something like gzfile to decompress the file. 

Is this possible with this package?

**Comment by leeper** [comment]
That sounds odd. `get_object()` should only return a raw vector. Any chance you could try to debug that a little for me or make a really simple example?

**Comment by VictorMayrink** [comment]
@inquotes the raw data returned by `get_object` have some attributes and many functions that manipulate raw data outputs errors caused by these attributes. Use `as_raw()`, see the code below:

```
> bin <- get_object(filename, bucket = s3conn)  
> writeBin(bin, "bin.csv.gz")
Error in writeBin(bin, "bin.csv.gz") : can only write vector objects
> writeBin(as.raw(bin), "bin.csv.gz")
#No errors
```
