### ISSUE TITLE
curl memory error with large files

### ISSUE THREAD

**Issue by grwhumphries** [cloudyr/aws.s3#95]
Hey, thanks for this great library.  I'm getting a curl error when trying to load a large file (256 mB). 

`Zstate.S3 <- get_object('MCMCzstate.rda','penguinmap')
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer`

Any thoughts on what might be going on here? Thanks in advance

**Comment by grwhumphries** [comment]
edit;

I used s3load(), and it loaded just fine.  However, get_object kept throwing that error at me.

**Comment by leeper** [comment]
Hmm, that's kind of odd because `s3load()` calls `get_object()` internally. Does the error only occur with that file?
