### ISSUE TITLE
How to upload file with SSE?

### ISSUE THREAD

**Issue by alartin** [cloudyr/aws.s3#96]
Hi all,
I failed to upload file to S3 since our S3 is configured to use SSE. Is there any support for that? Thanks!

**Comment by leeper** [comment]
You'll have to pass the relevant info as `headers` in `put_object()`. This page has details on what they need to look like: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html under the subheading "Server-Side Encryption Specific Request Headers".

**Comment by kadrach** [comment]
```R
  put_object(file = fl,
             object = s3_object_name,
             bucket = bucket,
             headers = c('x-amz-server-side-encryption' = 'AES256')) ## copy compressed file to S3
```

**Comment by alartin** [comment]
@kadrach Not work:In parse_aws_s3_response(r, Sig) : Bad Request (HTTP 400)
The provided 'x-amz-content-sha256' header does not match what was computed.
But many thanks to your reply

**Comment by kadrach** [comment]
You may need to adjust the header to suit your bucket policy. Above example works with
```javascript
{
  "Version": "2012-10-17",
  "Id": "EnforceServersideEncryption",
  "Statement": [
    {
      "Sid": "DenyIncorrectEncryptionHeader",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::some-bucket/*",
      "Condition": {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "AES256"
        }
      }
    }
  ]
}
```
