### ISSUE TITLE
Iterating through 1000's of objects in a bucket

### ISSUE THREAD

**Issue by grobins** [cloudyr/aws.s3#97]
I have a bucket that is partitioned by "/source/year/month/day/number_string.txt"

I need to be able to iterate through all objects that match a particular day, there are around 50,000 objects per day.  When I perform get_bucket() I only get a list of 1000 objects, is there anyway to extend this so I can do some regex and find the object I'm interested in, then download it.

**Comment by leeper** [comment]
Results are paginated. Use the `marker` argument to grab the next page of objects.

**Comment by ThierryO** [comment]
I'm facing a similar problem. How about adding a loop when `max > 1000`.

**Comment by leeper** [comment]
This will be solved by #104, thanks to @ThierryO.
