### ISSUE TITLE
Clarify use_credentials in README

### ISSUE THREAD

**Issue by ramhiser** [cloudyr/aws.s3#98]
The README describes loading AWS credentials from `~/.aws/credentials` via `use_credentials()`. Without a bit of digging, it is unclear that the function refers to `aws.signature::use_credentials()`. Moreover, no mention of `aws.signature` is made at all.

Perhaps a reference to [AWS's configuration](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) doc is warranted as well, given that the credentials file is a common way to store credentials.

**Comment by dzubo** [comment]
You just saved my time, thanks!
Yes, I think it's definitely worth mentioning in the README.
