### ISSUE TITLE
Convenience functions for loading data frames

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.s3#99]
This came up on Twitter and seems useful, but will be a little complicated. It requires [rio-style](https://cran.r-project.org/web/packages/rio/index.html) file type inference in order to call the correct function. It might be best to just suggest rio (but not all import functions used by rio support connections, which is what would make sense if `get_object()` is the underlying function).

**Comment by daattali** [comment]
FYI: I currently have an article on RStudio's shiny website that describes how to use external storage. My article uses `RAmazonS3`, which is an outdated and broken package. I want to update the article to use `aws.s3`, so once this feature is implemented your package will be on rstudio's page :)

**Comment by leeper** [comment]
I think I'm not going to add further high-level functionality here. rio can handle file types better so no need to invent the wheel. 

@daattali For your site, maybe the following will do:

```R
library("aws.s3")
Sys.setenv("AWS_ACCESS_KEY_ID" = "mykey")
Sys.setenv("AWS_SECRET_ACCESS_KEY" = "mysecret")

saveData <- function(data, s3BucketName) {
  # Create a unique file name
  fileName <- sprintf("%s_%s.csv", as.integer(Sys.time()), digest::digest(data))
  # Upload the data to S3
  put_object(
    object = I(paste0(
      paste(names(data), collapse = ","), 
      "\n",
      paste(data, collapse = ",")
    )),
    bucket = s3BucketName, 
    object = fileName
  )
}

loadData <- function(s3BucketName) {
  # Get a list of all files
  files <- get_bucket_df(s3BucketName)[["Key"]]
  # Read all files into a list
  data <- lapply(files, function(x) {
      raw <- rawConnection(get_object(bucket = s3BucketName, object = x))
      read.csv(raw, stringsAsFactors = FALSE)
      close(raw)
  })
  # Concatenate all data together into one data.frame
  data <- do.call(rbind, data)
  data  
}

```

**Comment by daattali** [comment]
@leeper how do I add a file to S3 given text rather than a file? I tried the code that I currently have working with the other package (similar to the code you gave), but I can't. Whenever I wrap my "text file" in an `I()` and then call `put_object()`, I get an error

`no applicable method for 'get_objectkey' applied to an object of class "AsIs"`

(If I don't wrap it in an `I()` it also doesn't work).

**Comment by leeper** [comment]
@daattali I had a mistake in the above code (called the file argument object). Fixed now. You might see that error if you do not specify an object key but it shouldn't occur otherwise.

**Comment by daattali** [comment]
I did notice that small error, and when I was trying it I fixed the
arguments. That wasn't the problem. When I replaced the 'file' argument
with an actual file path, it worked, but when I tried providing a string,
it doesn't. I'm not on my computer anymore, but the error was something
about the response parsing

**Comment by leeper** [comment]
I suspect if you wrap the contents in `charToRaw()` you won't encounter this. The error is coming from efforts to infer object keys from a filename passed as a character string to `file`.

**Comment by daattali** [comment]
Unfortunately that doesn't seem to work either. Maybe I'm doing something
wrong.... if you can get that to work, pushing a file by only giving its
contents, then let me know. I've updated my article anyway already to use
aws.s3 and for now I'm creating a temp file, it'd just be nicer if that
intermediate step didn't have to happen

---
Founder & Lead Consultant
AttaliTech Ltd
http://attalitech.com

**Comment by leeper** [comment]
@daattali Here's a modification that should work:

```R
saveData <- function(data, s3BucketName, objectKey) {
  # Create a unique file name
  if (missing(objectKey)) {
    objectKey <- sprintf("%s_%s.csv", as.integer(Sys.time()), digest::digest(data))
  }
  # Upload the data to S3
  put_object(
    file = charToRaw(paste0(
      paste(names(data), collapse = ","), "\n",
      paste(unname(apply(data, 1, paste, collapse = ",")), collapse = "\n")
    )),
    bucket = s3BucketName, 
    object = objectKey
  )
}
saveData(mtcars, "thisisatestbucket2", objectKey = "mtcars_test.csv")

obj <- rawToChar(get_object("s3://thisisatestbucket2/mtcars_test.csv"))
str(read.csv(text = obj))
## 'data.frame':   32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : int  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : int  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : int  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : int  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: int  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: int  4 4 1 1 2 1 4 2 2 4 ...
```

**Comment by daattali** [comment]
Thanks, I'm not sure what I was doing wrong, but it does work
